// Code generated by foundry generate; DO NOT EDIT.
// Source: models.go.

package officequeries

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	relation "github.com/weiloon1234/Foundry-Go/database/relation"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
	time "time"
)

// EmployeeFieldSet exposes fields owned by the unaliased model.
type EmployeeFieldSet = EmployeeScopedFieldSet[Employee]

var foundryEmployeeFields foundryquery.Memo[EmployeeFieldSet]

// EmployeeFields returns immutable field descriptors, built once per process.
func EmployeeFields() EmployeeFieldSet {
	return foundryEmployeeFields.Get(func() EmployeeFieldSet {
		return EmployeeFieldsAt(foundryquery.DeclareModelScope[Employee]("office_employees"))
	})
}

// EmployeeScopedFieldSet preserves typed field operators in a declared query scope.
type EmployeeScopedFieldSet[FoundryScope any] struct {
	// ID describes office_employees.id.
	ID foundryquery.ScalarField[FoundryScope, model.ID[Employee]]
	// OfficeID describes office_employees.office_id.
	OfficeID foundryquery.ScalarField[FoundryScope, model.ID[Office]]
	// Name describes office_employees.name.
	Name foundryquery.TextField[FoundryScope, string]
	// Salary describes office_employees.salary.
	Salary foundryquery.ExactField[FoundryScope, int64]
	// HiredAt describes office_employees.hired_at.
	HiredAt foundryquery.OrderedField[FoundryScope, time.Time]
}

// EmployeeFieldsAt binds these record fields to an alias or joined scope.
func EmployeeFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, Employee]) EmployeeScopedFieldSet[FoundryScope] {
	return EmployeeScopedFieldSet[FoundryScope]{
		ID:       foundryquery.NewScalarField[FoundryScope, model.ID[Employee]](scope.Table(), "id", codec.ID[Employee]()),
		OfficeID: foundryquery.NewScalarField[FoundryScope, model.ID[Office]](scope.Table(), "office_id", codec.ID[Office]()),
		Name:     foundryquery.NewTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
		Salary:   foundryquery.NewExactField[FoundryScope, int64](scope.Table(), "salary", codec.Signed[int64]()),
		HiredAt:  foundryquery.NewOrderedField[FoundryScope, time.Time](scope.Table(), "hired_at", codec.Time()),
	}
}

// EmployeeNullableFieldSet preserves typed field operators in a declared query scope.
type EmployeeNullableFieldSet[FoundryScope any] struct {
	// ID describes office_employees.id.
	ID foundryquery.NullableField[FoundryScope, model.ID[Employee]]
	// OfficeID describes office_employees.office_id.
	OfficeID foundryquery.NullableField[FoundryScope, model.ID[Office]]
	// Name describes office_employees.name.
	Name foundryquery.NullableTextField[FoundryScope, string]
	// Salary describes office_employees.salary.
	Salary foundryquery.NullableExactField[FoundryScope, int64]
	// HiredAt describes office_employees.hired_at.
	HiredAt foundryquery.NullableOrderedField[FoundryScope, time.Time]
}

// EmployeeNullableFieldsAt binds these record fields to an alias or joined scope.
func EmployeeNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, Employee]) EmployeeNullableFieldSet[FoundryScope] {
	return EmployeeNullableFieldSet[FoundryScope]{
		ID:       foundryquery.NewNullableField[FoundryScope, model.ID[Employee]](scope.Table(), "id", codec.ID[Employee]()),
		OfficeID: foundryquery.NewNullableField[FoundryScope, model.ID[Office]](scope.Table(), "office_id", codec.ID[Office]()),
		Name:     foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
		Salary:   foundryquery.NewNullableExactField[FoundryScope, int64](scope.Table(), "salary", codec.Signed[int64]()),
		HiredAt:  foundryquery.NewNullableOrderedField[FoundryScope, time.Time](scope.Table(), "hired_at", codec.Time()),
	}
}

// EmployeeQuery preserves model-specific keys through fluent query derivation.
type EmployeeQuery struct{ foundryquery.Query[Employee] }

// foundryEmployeeModelQuery holds the immutable declaration, hydration codecs and field metadata, built once on first use.
var foundryEmployeeModelQuery foundryquery.Memo[foundryquery.Query[Employee]]

func foundryEmployeeBuildQuery() foundryquery.Query[Employee] {
	foundryCodec0 := codec.ID[Employee]()
	foundryCodec1 := codec.ID[Office]()
	foundryCodec2 := codec.String[string]()
	foundryCodec3 := codec.Signed[int64]()
	foundryCodec4 := codec.Time()
	return foundryquery.ForModel(foundryquery.Define[Employee]("office_employees", "id", []foundryquery.Column{foundryquery.Column{Name: "id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "office_id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "name", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "salary", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "hired_at", Nullable: false, DatabaseDefault: false}}, func(row database.Row) (Employee, error) {
		var item Employee
		if err := row.Scan(
			foundryCodec0.Scan(&item.ID),
			foundryCodec1.Scan(&item.OfficeID),
			foundryCodec2.Scan(&item.Name),
			foundryCodec3.Scan(&item.Salary),
			foundryCodec4.Scan(&item.HiredAt),
		); err != nil {
			return Employee{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("id", foundryCodec0, func(item Employee) model.ID[Employee] { return item.ID }),
		foundryquery.NewModelField("office_id", foundryCodec1, func(item Employee) model.ID[Office] { return item.OfficeID }),
		foundryquery.NewModelField("name", foundryCodec2, func(item Employee) string { return item.Name }),
		foundryquery.NewModelField("salary", foundryCodec3, func(item Employee) int64 { return item.Salary }),
		foundryquery.NewModelField("hired_at", foundryCodec4, func(item Employee) time.Time { return item.HiredAt }),
	).WithObserverHooks((EmployeeHooks{}).foundryWriteHooks, false).WithRetrievalHooks((EmployeeRetrievalHooks{}).foundryRetrievalHooks, false))
}

// QueryOfficeEmployees starts a complete-model query for office_employees with generated hydration.
func QueryOfficeEmployees() EmployeeQuery {
	return EmployeeQuery{foundryEmployeeModelQuery.Get(foundryEmployeeBuildQuery)}
}

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (Employee) FoundryQuery() foundryquery.Query[Employee] { return QueryOfficeEmployees().Query }

// FoundryReference retains Employee and its concrete stored primary key for framework integrations.
// It reads ID directly, never calls an accessor, and performs no database lookup.
func (m Employee) FoundryReference() model.Reference[Employee, model.ID[Employee]] {
	return model.NewReference[Employee]("office_employees", m.ID, codec.ID[Employee]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m Employee) FoundryIdentity() (model.Identity, error) { return m.FoundryReference().Identity() }

// WithTrashed derives a new Employee query without changing its source.
func (q EmployeeQuery) WithTrashed() EmployeeQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new Employee query without changing its source.
func (q EmployeeQuery) OnlyTrashed() EmployeeQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new Employee query without changing its source.
func (q EmployeeQuery) WithoutTrashed() EmployeeQuery { q.Query = q.Query.WithoutTrashed(); return q }

// WithoutGlobalScope derives a new Employee query without changing its source.
func (q EmployeeQuery) WithoutGlobalScope(scopes ...foundryquery.GlobalScope[Employee]) EmployeeQuery {
	q.Query = q.Query.WithoutGlobalScope(scopes...)
	return q
}

// WithoutGlobalScopes derives a new Employee query without changing its source.
func (q EmployeeQuery) WithoutGlobalScopes() EmployeeQuery {
	q.Query = q.Query.WithoutGlobalScopes()
	return q
}

// WithScopeContext derives a new Employee query without changing its source.
func (q EmployeeQuery) WithScopeContext(ctx context.Context) EmployeeQuery {
	q.Query = q.Query.WithScopeContext(ctx)
	return q
}

// Where derives a new Employee query without changing its source.
func (q EmployeeQuery) Where(predicates ...foundryquery.Predicate[Employee]) EmployeeQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new Employee query without changing its source.
func (q EmployeeQuery) WhereHas(relation foundryquery.ExistenceRelation[Employee]) EmployeeQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new Employee query without changing its source.
func (q EmployeeQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Employee]) EmployeeQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new Employee query without changing its source.
func (q EmployeeQuery) OrderBy(orders ...foundryquery.Order[Employee]) EmployeeQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new Employee query without changing its source.
func (q EmployeeQuery) Limit(count int) EmployeeQuery { q.Query = q.Query.Limit(count); return q }

// Offset derives a new Employee query without changing its source.
func (q EmployeeQuery) Offset(count int) EmployeeQuery { q.Query = q.Query.Offset(count); return q }

// With derives a new Employee query without changing its source.
func (q EmployeeQuery) With(relations ...foundryquery.Relation[Employee]) EmployeeQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new Employee query without changing its source.
func (q EmployeeQuery) WithRelationLimits(limits foundryquery.RelationLimits) EmployeeQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q EmployeeQuery) Find(ctx context.Context, executor database.Executor, key model.ID[Employee]) (foundryvalue.Optional[Employee], error) {
	return q.Where(EmployeeFields().ID.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q EmployeeQuery) RequireFind(ctx context.Context, executor database.Executor, key model.ID[Employee]) (Employee, error) {
	return q.Where(EmployeeFields().ID.Eq(key)).RequireFirst(ctx, executor)
}

// EmployeeLockedQuery preserves typed keys while requiring transaction-scoped reads.
type EmployeeLockedQuery struct {
	foundryquery.LockedQuery[Employee]
}

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EmployeeQuery) ForUpdate() EmployeeLockedQuery {
	return EmployeeLockedQuery{q.Query.ForUpdate()}
}

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EmployeeQuery) ForNoKeyUpdate() EmployeeLockedQuery {
	return EmployeeLockedQuery{q.Query.ForNoKeyUpdate()}
}

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EmployeeQuery) ForShare() EmployeeLockedQuery { return EmployeeLockedQuery{q.Query.ForShare()} }

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EmployeeQuery) ForKeyShare() EmployeeLockedQuery {
	return EmployeeLockedQuery{q.Query.ForKeyShare()}
}

// WithTrashed derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithTrashed() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) OnlyTrashed() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithoutTrashed() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// WithoutGlobalScope derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithoutGlobalScope(scopes ...foundryquery.GlobalScope[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutGlobalScope(scopes...)
	return q
}

// WithoutGlobalScopes derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithoutGlobalScopes() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutGlobalScopes()
	return q
}

// WithScopeContext derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithScopeContext(ctx context.Context) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithScopeContext(ctx)
	return q
}

// Where derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) Where(predicates ...foundryquery.Predicate[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) OrderBy(orders ...foundryquery.Order[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) Limit(count int) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) Offset(count int) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) With(relations ...foundryquery.Relation[Employee]) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) NoWait() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.NoWait()
	return q
}

// SkipLocked derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) SkipLocked() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked Employee query without changing its source.
func (q EmployeeLockedQuery) Wait() EmployeeLockedQuery {
	q.LockedQuery = q.LockedQuery.Wait()
	return q
}

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q EmployeeLockedQuery) Find(ctx context.Context, tx *database.Tx, key model.ID[Employee]) (foundryvalue.Optional[Employee], error) {
	return q.Where(EmployeeFields().ID.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q EmployeeLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key model.ID[Employee]) (Employee, error) {
	return q.Where(EmployeeFields().ID.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q EmployeeQuery) Create(ctx context.Context, writer database.Transactor, draft EmployeeDraft) (Employee, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return Employee{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q EmployeeQuery) Upsert(ctx context.Context, writer database.Transactor, draft EmployeeDraft, conflict foundryquery.Conflict[Employee]) (foundryvalue.Optional[Employee], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[Employee]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q EmployeeQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []EmployeeDraft) ([]Employee, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q EmployeeQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []EmployeeDraft, conflict foundryquery.Conflict[Employee]) ([]Employee, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q EmployeeQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []EmployeeDraft, conflict *foundryquery.Conflict[Employee]) ([]Employee, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q EmployeeQuery) foundryCreateMutations(drafts []EmployeeDraft) ([]foundryquery.Mutation[Employee], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[Employee], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q EmployeeQuery) Update(ctx context.Context, writer database.Transactor, key model.ID[Employee], draft EmployeeDraft) (Employee, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return Employee{}, err
	}
	return q.Where(EmployeeFields().ID.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete removes one typed primary key within this query's filters and returns its complete pre-deletion model.
func (q EmployeeQuery) Delete(ctx context.Context, writer database.Transactor, key model.ID[Employee]) (Employee, error) {
	return q.Where(EmployeeFields().ID.Eq(key)).Query.Remove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q EmployeeQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []EmployeeDraft) ([]Employee, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q EmployeeQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, Employee) (EmployeeDraft, error)) ([]Employee, error) {
	var callback func(context.Context, *database.Tx, Employee) (foundryquery.Mutation[Employee], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Employee) (foundryquery.Mutation[Employee], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q EmployeeQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Employee, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; omitted fields default from the query's top-level equality filters and global scopes, and the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q EmployeeQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create EmployeeDraft) (Employee, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// CreateOrFirst creates a model through its normal lifecycle and, when a unique constraint rejects it, returns the first primary-ordered model matching the query instead. The insert runs in its own savepoint, so a concurrent creation of the same unique key is resolved under READ COMMITTED rather than reported. The query must select the row holding the conflicting key; a created model must satisfy it.
func (q EmployeeQuery) CreateOrFirst(ctx context.Context, writer database.Transactor, create EmployeeDraft) (Employee, error) {
	return q.Query.InsertOrFirst(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q EmployeeQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create EmployeeDraft, draft func(context.Context, *database.Tx, Employee) (EmployeeDraft, error)) (Employee, error) {
	var callback func(context.Context, *database.Tx, Employee) (foundryquery.Mutation[Employee], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Employee) (foundryquery.Mutation[Employee], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// EmployeeInsertFromBuilder selects stored SQL values into Employee through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type EmployeeInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, Employee]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p EmployeeInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertEmployeeFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertEmployeeFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) EmployeeInsertFromBuilder[FoundryScope] {
	return EmployeeInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (Employee{}).FoundryQuery())}
}

// SelectID supplies the stored SQL value for id. It cannot also be supplied by Values.
func (p EmployeeInsertFromBuilder[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, model.ID[Employee]]) EmployeeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EmployeeFields().ID, v))
	return p
}

// SelectOfficeID supplies the stored SQL value for office_id. It cannot also be supplied by Values.
func (p EmployeeInsertFromBuilder[FoundryScope]) SelectOfficeID(v foundryquery.Expression[FoundryScope, model.ID[Office]]) EmployeeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EmployeeFields().OfficeID, v))
	return p
}

// SelectName supplies the stored SQL value for name. It cannot also be supplied by Values.
func (p EmployeeInsertFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) EmployeeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EmployeeFields().Name, v))
	return p
}

// SelectSalary supplies the stored SQL value for salary. It cannot also be supplied by Values.
func (p EmployeeInsertFromBuilder[FoundryScope]) SelectSalary(v foundryquery.Expression[FoundryScope, int64]) EmployeeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EmployeeFields().Salary, v))
	return p
}

// SelectHiredAt supplies the stored SQL value for hired_at. It cannot also be supplied by Values.
func (p EmployeeInsertFromBuilder[FoundryScope]) SelectHiredAt(v foundryquery.Expression[FoundryScope, time.Time]) EmployeeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EmployeeFields().HiredAt, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p EmployeeInsertFromBuilder[FoundryScope]) Values(draft EmployeeDraft) EmployeeInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p EmployeeInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p EmployeeInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Employee, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// EmployeeUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type EmployeeUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, Employee]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p EmployeeUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdateEmployeeFrom preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func UpdateEmployeeFrom[FoundryScope any](destination EmployeeQuery, source foundryquery.ProjectionSource[FoundryScope]) EmployeeUpdateFromBuilder[FoundryScope] {
	return EmployeeUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p EmployeeUpdateFromBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Employee]]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(EmployeeFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p EmployeeUpdateFromBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Employee]]]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(EmployeeFields().ID, v))
	return p
}

// SelectOfficeID assigns a stored source value to office_id; Values cannot also supply it.
func (p EmployeeUpdateFromBuilder[FoundryScope]) SelectOfficeID(v foundryquery.Expression[FoundryScope, model.ID[Office]]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EmployeeFields().OfficeID, v))
	return p
}

// SelectName assigns a stored source value to name; Values cannot also supply it.
func (p EmployeeUpdateFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EmployeeFields().Name, v))
	return p
}

// SelectSalary assigns a stored source value to salary; Values cannot also supply it.
func (p EmployeeUpdateFromBuilder[FoundryScope]) SelectSalary(v foundryquery.Expression[FoundryScope, int64]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EmployeeFields().Salary, v))
	return p
}

// SelectHiredAt assigns a stored source value to hired_at; Values cannot also supply it.
func (p EmployeeUpdateFromBuilder[FoundryScope]) SelectHiredAt(v foundryquery.Expression[FoundryScope, time.Time]) EmployeeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EmployeeFields().HiredAt, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p EmployeeUpdateFromBuilder[FoundryScope]) Values(draft EmployeeDraft) EmployeeUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p EmployeeUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p EmployeeUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Employee, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// EmployeeDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type EmployeeDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, Employee]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p EmployeeDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeleteEmployeeUsing preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func DeleteEmployeeUsing[FoundryScope any](destination EmployeeQuery, source foundryquery.ProjectionSource[FoundryScope]) EmployeeDeleteUsingBuilder[FoundryScope] {
	return EmployeeDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p EmployeeDeleteUsingBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Employee]]) EmployeeDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(EmployeeFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p EmployeeDeleteUsingBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Employee]]]) EmployeeDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(EmployeeFields().ID, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p EmployeeDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p EmployeeDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Employee, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// WithoutModelHooks acknowledges that set-based writes on this query skip per-model hooks and observers; per-model writes on it are rejected.
func (q EmployeeQuery) WithoutModelHooks() EmployeeQuery {
	q.Query = q.Query.WithoutModelHooks()
	return q
}

// UpdateAll assigns the draft to every model matching this query (filters, global scopes and soft-delete visibility) in one UPDATE and returns the affected count. Managed update timestamps and field mutators apply once; per-model hooks, observers and change capture do not run.
func (q EmployeeQuery) UpdateAll(ctx context.Context, writer database.Transactor, draft EmployeeDraft) (int64, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return 0, err
	}
	return q.Query.PatchAll(ctx, writer, mutation)
}

// DeleteAll physically deletes every model matching this query in one statement and returns the affected count. Per-model hooks do not run.
func (q EmployeeQuery) DeleteAll(ctx context.Context, writer database.Transactor) (int64, error) {
	return q.Query.RemoveAll(ctx, writer)
}

// Increment adjusts one numeric field of every matching model by a typed delta, such as EmployeeFields().Field.By(1), with an optional extra draft, in one UPDATE. SQL NULL stays NULL. Per-model hooks do not run.
func (q EmployeeQuery) Increment(ctx context.Context, writer database.Transactor, adjustment foundryquery.Adjustment[Employee], extra ...EmployeeDraft) (int64, error) {
	if len(extra) > 1 {
		return 0, foundryfault.New(foundryfault.Invalid, "numeric adjustment accepts at most one extra draft")
	}
	var mutation foundryquery.Mutation[Employee]
	if len(extra) == 1 {
		var err error
		if mutation, err = extra[0].foundryMutation(false); err != nil {
			return 0, err
		}
	}
	return q.Query.AdjustAll(ctx, writer, adjustment, false, mutation)
}

// Decrement adjusts one numeric field of every matching model by a typed delta, such as EmployeeFields().Field.By(1), with an optional extra draft, in one UPDATE. SQL NULL stays NULL. Per-model hooks do not run.
func (q EmployeeQuery) Decrement(ctx context.Context, writer database.Transactor, adjustment foundryquery.Adjustment[Employee], extra ...EmployeeDraft) (int64, error) {
	if len(extra) > 1 {
		return 0, foundryfault.New(foundryfault.Invalid, "numeric adjustment accepts at most one extra draft")
	}
	var mutation foundryquery.Mutation[Employee]
	if len(extra) == 1 {
		var err error
		if mutation, err = extra[0].foundryMutation(false); err != nil {
			return 0, err
		}
	}
	return q.Query.AdjustAll(ctx, writer, adjustment, true, mutation)
}

// FoundryUpdateMutation supplies the typed update-draft adapter for framework integrations such as pivot updates. Omitted fields stay unchanged; no mutators or database calls run here.
func (d EmployeeDraft) FoundryUpdateMutation() (foundryquery.Mutation[Employee], error) {
	return d.foundryMutation(false)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d EmployeeDraft) FoundryCreateMutation(defaults foundryquery.Mutation[Employee]) (foundryquery.Mutation[Employee], error) {
	values, err := foundryquery.ReadCreateDefaults((Employee{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[Employee]{}, err
	}
	if !d.fieldID.IsSet() {
		v, err := foundryquery.MutationValue[Employee, model.ID[Employee]](values, "office_employees", "id")
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d.fieldID = v
	}
	if !d.fieldOfficeID.IsSet() {
		v, err := foundryquery.MutationValue[Employee, model.ID[Office]](values, "office_employees", "office_id")
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d.fieldOfficeID = v
	}
	if !d.fieldName.IsSet() {
		v, err := foundryquery.MutationValue[Employee, string](values, "office_employees", "name")
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d.fieldName = v
	}
	if !d.fieldSalary.IsSet() {
		v, err := foundryquery.MutationValue[Employee, int64](values, "office_employees", "salary")
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d.fieldSalary = v
	}
	if !d.fieldHiredAt.IsSet() {
		v, err := foundryquery.MutationValue[Employee, time.Time](values, "office_employees", "hired_at")
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d.fieldHiredAt = v
	}
	return d.foundryMutation(true)
}
func (d EmployeeDraft) foundryMutation(create bool) (foundryquery.Mutation[Employee], error) {
	if create && !d.fieldID.IsSet() {
		id, err := model.NewID[Employee]()
		if err != nil {
			return foundryquery.Mutation[Employee]{}, err
		}
		d = d.SetID(id)
	}
	var assignments []foundryquery.Assignment[Employee]
	if v, set := d.fieldID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Employee]("office_employees", "id", codec.ID[Employee](), v))
	}
	if v, set := d.fieldOfficeID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Employee]("office_employees", "office_id", codec.ID[Office](), v))
	}
	if v, set := d.fieldName.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Employee]("office_employees", "name", codec.String[string](), v))
	}
	if v, set := d.fieldSalary.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Employee]("office_employees", "salary", codec.Signed[int64](), v))
	}
	if v, set := d.fieldHiredAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Employee]("office_employees", "hired_at", codec.Time(), v))
	}
	return foundryquery.Change(assignments...), nil
}

// EmployeeRelationSet requires typed descriptors matching every declared relation slot.
type EmployeeRelationSet struct {
	Region foundryquery.OneRelation[Employee, Region]
}

var foundryEmployeeRelations foundryquery.Memo[EmployeeRelationSet]

func foundryEmployeeBuildRelations() EmployeeRelationSet {
	relations := (Employee{}).DefineRelations()
	relations.Region = relations.Region.Bind("Region", QueryOfficeEmployees().Query, (Region{}).FoundryQuery(), func(m Employee) relation.One[Region] { return m.Region }, func(m Employee, loaded relation.One[Region]) Employee { m.Region = loaded; return m })
	return relations
}

// EmployeeRelations binds handwritten key declarations to generated model metadata and typed slots.
// DefineRelations runs once per process; its immutable descriptors are shared.
func EmployeeRelations() EmployeeRelationSet {
	return foundryEmployeeRelations.Get(foundryEmployeeBuildRelations)
}

// EmployeeDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type EmployeeDraft struct {
	fieldID       foundryvalue.Optional[model.ID[Employee]]
	fieldOfficeID foundryvalue.Optional[model.ID[Office]]
	fieldName     foundryvalue.Optional[string]
	fieldSalary   foundryvalue.Optional[int64]
	fieldHiredAt  foundryvalue.Optional[time.Time]
}

// ID returns the typed mutation state for id.
func (d EmployeeDraft) ID() foundryvalue.Optional[model.ID[Employee]] { return d.fieldID }

// SetID returns a new draft with id explicitly set.
func (d EmployeeDraft) SetID(v model.ID[Employee]) EmployeeDraft {
	d.fieldID = foundryvalue.Set(v)
	return d
}

// UnsetID omits id without requesting a zero or null write.
func (d EmployeeDraft) UnsetID() EmployeeDraft {
	d.fieldID = foundryvalue.Optional[model.ID[Employee]]{}
	return d
}

// OfficeID returns the typed mutation state for office_id.
func (d EmployeeDraft) OfficeID() foundryvalue.Optional[model.ID[Office]] { return d.fieldOfficeID }

// SetOfficeID returns a new draft with office_id explicitly set.
func (d EmployeeDraft) SetOfficeID(v model.ID[Office]) EmployeeDraft {
	d.fieldOfficeID = foundryvalue.Set(v)
	return d
}

// UnsetOfficeID omits office_id without requesting a zero or null write.
func (d EmployeeDraft) UnsetOfficeID() EmployeeDraft {
	d.fieldOfficeID = foundryvalue.Optional[model.ID[Office]]{}
	return d
}

// Name returns the typed mutation state for name.
func (d EmployeeDraft) Name() foundryvalue.Optional[string] { return d.fieldName }

// SetName returns a new draft with name explicitly set.
func (d EmployeeDraft) SetName(v string) EmployeeDraft { d.fieldName = foundryvalue.Set(v); return d }

// UnsetName omits name without requesting a zero or null write.
func (d EmployeeDraft) UnsetName() EmployeeDraft {
	d.fieldName = foundryvalue.Optional[string]{}
	return d
}

// Salary returns the typed mutation state for salary.
func (d EmployeeDraft) Salary() foundryvalue.Optional[int64] { return d.fieldSalary }

// SetSalary returns a new draft with salary explicitly set.
func (d EmployeeDraft) SetSalary(v int64) EmployeeDraft {
	d.fieldSalary = foundryvalue.Set(v)
	return d
}

// UnsetSalary omits salary without requesting a zero or null write.
func (d EmployeeDraft) UnsetSalary() EmployeeDraft {
	d.fieldSalary = foundryvalue.Optional[int64]{}
	return d
}

// HiredAt returns the typed mutation state for hired_at.
func (d EmployeeDraft) HiredAt() foundryvalue.Optional[time.Time] { return d.fieldHiredAt }

// SetHiredAt returns a new draft with hired_at explicitly set.
func (d EmployeeDraft) SetHiredAt(v time.Time) EmployeeDraft {
	d.fieldHiredAt = foundryvalue.Set(v)
	return d
}

// UnsetHiredAt omits hired_at without requesting a zero or null write.
func (d EmployeeDraft) UnsetHiredAt() EmployeeDraft {
	d.fieldHiredAt = foundryvalue.Optional[time.Time]{}
	return d
}

// IsEmpty reports whether no fields have been selected for mutation.
func (d EmployeeDraft) IsEmpty() bool {
	return !d.fieldID.IsSet() && !d.fieldOfficeID.IsSet() && !d.fieldName.IsSet() && !d.fieldSalary.IsSet() && !d.fieldHiredAt.IsSet()
}

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (EmployeeDraft) Format(state fmt.State, _ rune) { _, _ = state.Write([]byte("Employee draft")) }

// EmployeeFieldChanges contains typed changes for persisted fields only.
type EmployeeFieldChanges struct {
	// ID retains the typed change for id.
	ID lifecycle.FieldChange[model.ID[Employee]]
	// OfficeID retains the typed change for office_id.
	OfficeID lifecycle.FieldChange[model.ID[Office]]
	// Name retains the typed change for name.
	Name lifecycle.FieldChange[string]
	// Salary retains the typed change for salary.
	Salary lifecycle.FieldChange[int64]
	// HiredAt retains the typed change for hired_at.
	HiredAt lifecycle.FieldChange[time.Time]
}

// EmployeeChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type EmployeeChanges struct {
	before, after foundryvalue.Optional[Employee]
	fields        EmployeeFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c EmployeeChanges) Operation() foundryvalue.Optional[lifecycle.Operation] { return c.operation }

// Before returns the persisted model before the operation, or absence for creation.
func (c EmployeeChanges) Before() foundryvalue.Optional[Employee] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c EmployeeChanges) After() foundryvalue.Optional[Employee] { return c.after }

// Fields returns model-specific field changes by value.
func (c EmployeeChanges) Fields() EmployeeFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c EmployeeChanges) Assigned() bool {
	return c.fields.ID.Assigned() || c.fields.OfficeID.Assigned() || c.fields.Name.Assigned() || c.fields.Salary.Assigned() || c.fields.HiredAt.Assigned()
}

// Changed reports whether any persisted field is changed.
func (c EmployeeChanges) Changed() bool {
	return c.fields.ID.Changed() || c.fields.OfficeID.Changed() || c.fields.Name.Changed() || c.fields.Salary.Changed() || c.fields.HiredAt.Changed()
}

// String and GoString keep model snapshots out of routine diagnostics.
func (EmployeeChanges) String() string     { return "Employee changes" }
func (c EmployeeChanges) GoString() string { return c.String() }

// CompareEmployee is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func CompareEmployee(before, after foundryvalue.Optional[Employee], assigned EmployeeDraft) (EmployeeChanges, error) {
	before = foundryEmployeeSnapshot(before)
	after = foundryEmployeeSnapshot(after)
	var changes EmployeeChanges
	var err error
	changes.fields.ID, err = lifecycle.CompareModelField(codec.ID[Employee](), before, after, assigned.fieldID.IsSet(), func(item Employee) model.ID[Employee] { return item.ID })
	if err != nil {
		return EmployeeChanges{}, fmt.Errorf("compare Employee.ID: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.ID.Changed() || changes.fields.ID.Assigned()) {
		return EmployeeChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.OfficeID, err = lifecycle.CompareModelField(codec.ID[Office](), before, after, assigned.fieldOfficeID.IsSet(), func(item Employee) model.ID[Office] { return item.OfficeID })
	if err != nil {
		return EmployeeChanges{}, fmt.Errorf("compare Employee.OfficeID: %w", err)
	}
	changes.fields.Name, err = lifecycle.CompareModelField(codec.String[string](), before, after, assigned.fieldName.IsSet(), func(item Employee) string { return item.Name })
	if err != nil {
		return EmployeeChanges{}, fmt.Errorf("compare Employee.Name: %w", err)
	}
	changes.fields.Salary, err = lifecycle.CompareModelField(codec.Signed[int64](), before, after, assigned.fieldSalary.IsSet(), func(item Employee) int64 { return item.Salary })
	if err != nil {
		return EmployeeChanges{}, fmt.Errorf("compare Employee.Salary: %w", err)
	}
	changes.fields.HiredAt, err = lifecycle.CompareModelField(codec.Time(), before, after, assigned.fieldHiredAt.IsSet(), func(item Employee) time.Time { return item.HiredAt })
	if err != nil {
		return EmployeeChanges{}, fmt.Errorf("compare Employee.HiredAt: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryEmployeeSnapshot(snapshot foundryvalue.Optional[Employee]) foundryvalue.Optional[Employee] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[Employee]{}
	}
	return foundryvalue.Set(Employee{
		ID:       item.ID,
		OfficeID: item.OfficeID,
		Name:     item.Name,
		Salary:   item.Salary,
		HiredAt:  item.HiredAt,
	})
}

// EmployeeHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type EmployeeHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[Employee], *EmployeeDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *EmployeeDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, Employee, *EmployeeDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, Employee) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, Employee) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, Employee) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, EmployeeChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, EmployeeChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, EmployeeChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, EmployeeChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, EmployeeChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, EmployeeChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, EmployeeChanges) error
}

// EmployeeObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type EmployeeObserver = lifecycle.Observer[Employee, EmployeeHooks]

// NewEmployeeObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewEmployeeObserver(observer string) EmployeeObserver {
	return lifecycle.NewObserver[Employee, EmployeeHooks](observer)
}

// RegisterEmployeeObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterEmployeeObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer EmployeeObserver, construct func(foundation.Resolver) (func() EmployeeHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (EmployeeHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[Employee], error) {
	factories, err := lifecycle.ObserverFactories[Employee, EmployeeHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[Employee]{}, err
	}
	var allHooks []EmployeeHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Employee]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[Employee]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Employee]{}, err
	}
	return foundryquery.WriteHooks[Employee]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[Employee], mutation foundryquery.Mutation[Employee]) (foundryquery.Mutation[Employee], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			var draft EmployeeDraft
			draft.fieldID, err = foundryquery.MutationValue[Employee, model.ID[Employee]](values, "office_employees", "id")
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			draft.fieldOfficeID, err = foundryquery.MutationValue[Employee, model.ID[Office]](values, "office_employees", "office_id")
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			draft.fieldName, err = foundryquery.MutationValue[Employee, string](values, "office_employees", "name")
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			draft.fieldSalary, err = foundryquery.MutationValue[Employee, int64](values, "office_employees", "salary")
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			draft.fieldHiredAt, err = foundryquery.MutationValue[Employee, time.Time](values, "office_employees", "hired_at")
			if err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[Employee]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Employee]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Employee]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[Employee]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[Employee]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Employee]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Employee]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Employee]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Employee]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Employee]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[Employee]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[Employee], mutation foundryquery.Mutation[Employee]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft EmployeeDraft
			if values.Has("office_employees", "id") {
				var zero model.ID[Employee]
				draft.fieldID = foundryvalue.Set(zero)
			}
			if values.Has("office_employees", "office_id") {
				var zero model.ID[Office]
				draft.fieldOfficeID = foundryvalue.Set(zero)
			}
			if values.Has("office_employees", "name") {
				var zero string
				draft.fieldName = foundryvalue.Set(zero)
			}
			if values.Has("office_employees", "salary") {
				var zero int64
				draft.fieldSalary = foundryvalue.Set(zero)
			}
			if values.Has("office_employees", "hired_at") {
				var zero time.Time
				draft.fieldHiredAt = foundryvalue.Set(zero)
			}
			changes, err := CompareEmployee(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// EmployeeRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type EmployeeRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, Employee) error
}

// EmployeeRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type EmployeeRetrievalObserver = lifecycle.Observer[Employee, EmployeeRetrievalHooks]

// NewEmployeeRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewEmployeeRetrievalObserver(observer string) EmployeeRetrievalObserver {
	return lifecycle.NewRetrievalObserver[Employee, EmployeeRetrievalHooks](observer)
}

// RegisterEmployeeRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterEmployeeRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer EmployeeRetrievalObserver, construct func(foundation.Resolver) (func() EmployeeRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (EmployeeRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[Employee], error) {
	factories, err := lifecycle.RetrievalObserverFactories[Employee, EmployeeRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[Employee]{}, err
	}
	var allHooks []EmployeeRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Employee]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[Employee]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Employee]{}, err
	}
	return foundryquery.RetrievalHooks[Employee]{Retrieved: func(ctx context.Context, executor database.Executor, item Employee) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// EmployeeAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type EmployeeAuditPolicy struct {
	_ [0]*Employee
	// ID controls the audit representation of stored office_employees.id.
	ID record.Disclosure
	// OfficeID controls the audit representation of stored office_employees.office_id.
	OfficeID record.Disclosure
	// Name controls the audit representation of stored office_employees.name.
	Name record.Disclosure
	// Salary controls the audit representation of stored office_employees.salary.
	Salary record.Disclosure
	// HiredAt controls the audit representation of stored office_employees.hired_at.
	HiredAt record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Updates, soft deletes and restorations record assigned or changed fields plus the key; create and delete record every field.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes EmployeeChanges) Audit(policy EmployeeAuditPolicy) (record.Model[Employee, model.ID[Employee]], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[Employee, model.ID[Employee]]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[Employee, model.ID[Employee]]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "id", policy.ID)
	if err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	if err = record.Capture(builder, "id", codec.ID[Employee](), changes.fields.ID, policy.ID); err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	if err = record.Capture(builder, "office_id", codec.ID[Office](), changes.fields.OfficeID, policy.OfficeID); err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	if err = record.Capture(builder, "name", codec.String[string](), changes.fields.Name, policy.Name); err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	if err = record.Capture(builder, "salary", codec.Signed[int64](), changes.fields.Salary, policy.Salary); err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	if err = record.Capture(builder, "hired_at", codec.Time(), changes.fields.HiredAt, policy.HiredAt); err != nil {
		return record.Model[Employee, model.ID[Employee]]{}, err
	}
	return builder.Build()
}

// EmployeeAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type EmployeeAuditFieldSet struct {
	_ [0]*Employee
	// ID retains stored office_employees.id after write mutators; read accessors do not replace audit values.
	ID foundryvalue.Optional[record.FieldChange[model.ID[Employee]]]
	// OfficeID retains stored office_employees.office_id after write mutators; read accessors do not replace audit values.
	OfficeID foundryvalue.Optional[record.FieldChange[model.ID[Office]]]
	// Name retains stored office_employees.name after write mutators; read accessors do not replace audit values.
	Name foundryvalue.Optional[record.FieldChange[string]]
	// Salary retains stored office_employees.salary after write mutators; read accessors do not replace audit values.
	Salary foundryvalue.Optional[record.FieldChange[int64]]
	// HiredAt retains stored office_employees.hired_at after write mutators; read accessors do not replace audit values.
	HiredAt foundryvalue.Optional[record.FieldChange[time.Time]]
}

// EmployeeAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func EmployeeAuditFields(history record.Model[Employee, model.ID[Employee]]) (EmployeeAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	var fields EmployeeAuditFieldSet
	fields.ID, err = record.ReadField(view, "id", codec.ID[Employee]())
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	fields.OfficeID, err = record.ReadField(view, "office_id", codec.ID[Office]())
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	fields.Name, err = record.ReadField(view, "name", codec.String[string]())
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	fields.Salary, err = record.ReadField(view, "salary", codec.Signed[int64]())
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	fields.HiredAt, err = record.ReadField(view, "hired_at", codec.Time())
	if err != nil {
		return EmployeeAuditFieldSet{}, err
	}
	return fields, nil
}

// EmployeeAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func EmployeeAuditing(policy EmployeeAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[Employee]()
		if err != nil {
			return err
		}
		return RegisterEmployeeObserver(registrar, pool, NewEmployeeObserver(name), func(resolver foundation.Resolver) (func() EmployeeHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() EmployeeHooks {
				write := func(ctx context.Context, tx *database.Tx, changes EmployeeChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return EmployeeHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
