// Code generated by foundry generate; DO NOT EDIT.
// Source: client.go.

package outgoing

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
	sync "sync"
)

// CreateAccountJSON describes the concrete CreateAccount JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func CreateAccountJSON() foundrycontract.JSON[CreateAccount] { return foundryCreateAccountJSON() }

var foundryCreateAccountJSON = sync.OnceValue(func() foundrycontract.JSON[CreateAccount] {
	return foundrycontract.DefineJSON[CreateAccount](foundrycontract.Schema{Root: "foundry.test/consumer/outgoing.CreateAccount", Types: []foundrycontract.Type{
		{ID: "foundry.test/consumer/outgoing.CreateAccount", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "name", Type: "string", Required: true},
			},
		},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
})

// CreateAccountValidationFieldSet retains concrete DTO and value types for validation.
type CreateAccountValidationFieldSet struct {
	// Name validates the declared JSON property "name".
	Name foundryvalidation.Field[CreateAccount, string]
}

// CreateAccountValidationFields returns typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func CreateAccountValidationFields() CreateAccountValidationFieldSet {
	return foundryCreateAccountValidationFields()
}

var foundryCreateAccountValidationFields = sync.OnceValue(func() CreateAccountValidationFieldSet {
	return CreateAccountValidationFieldSet{
		Name: foundryvalidation.DefineField("name", func(input CreateAccount) string {
			return input.Name
		}),
	}
})
