// Code generated by foundry generate; DO NOT EDIT.
// Source: http.go.

package articles

import (
	foundryhttp "github.com/weiloon1234/Foundry-Go/http"
	model "github.com/weiloon1234/Foundry-Go/model"
	sync "sync"
)

// ArticlePathDescriptor binds the declared pattern to concrete ArticlePath fields.
// Reuse this descriptor for route registration and named URL generation.
func ArticlePathDescriptor() foundryhttp.Path[ArticlePath] { return foundryArticlePathDescriptor() }

var foundryArticlePathDescriptor = sync.OnceValue(func() foundryhttp.Path[ArticlePath] {
	return foundryhttp.DefinePath[ArticlePath]("/articles/{article}",
		foundryhttp.Param[ArticlePath, model.ID[Article]]("article", foundryhttp.URLType("github.com/weiloon1234/Foundry-Go/model.ID[foundry.test/consumer/articles.Article]", foundryhttp.ModelIDPath[Article]()), func(path *ArticlePath) *model.ID[Article] { return &path.Article }),
	)
})
