// Code generated by foundry generate; DO NOT EDIT.
// Source: http.go.

package articles

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	i18n "github.com/weiloon1234/Foundry-Go/i18n"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
	sync "sync"
)

// ArticleInputJSON describes the concrete ArticleInput JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func ArticleInputJSON() foundrycontract.JSON[ArticleInput] { return foundryArticleInputJSON() }

var foundryArticleInputJSON = sync.OnceValue(func() foundrycontract.JSON[ArticleInput] {
	return foundrycontract.DefineJSON[ArticleInput](foundrycontract.Schema{Root: "foundry.test/consumer/articles.ArticleInput", Types: []foundrycontract.Type{
		{ID: "foundry.test/consumer/articles.ArticleInput", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "author", Type: "string", Required: true},
				{Name: "seo", Type: "github.com/weiloon1234/Foundry-Go/value.Optional[foundry.test/consumer/articles.SEO]", Required: false},
				{Name: "slug", Type: "string", Required: true},
				{Name: "summary", Type: "go:3b116365e8100fa0774841a4f3971426d59a3d3b2a85917e7c2c2cd61ae68f67", Required: true},
				{Name: "title", Type: "go:3b116365e8100fa0774841a4f3971426d59a3d3b2a85917e7c2c2cd61ae68f67", Required: true},
			},
		},
		{ID: "foundry.test/consumer/articles.SEO", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "canonical", Type: "github.com/weiloon1234/Foundry-Go/value.Optional[string]", Required: false},
				{Name: "keywords", Type: "github.com/weiloon1234/Foundry-Go/value.Optional[[]string]", Required: false},
			},
		},
		{ID: "github.com/weiloon1234/Foundry-Go/value.Optional[[]string]", Kind: foundrycontract.Kind("alias"), Nullable: false,
			Element: "go:4af101177fe720bf0766557228231c42b38635920ef7206f518a04030b3dcdf0",
		},
		{ID: "github.com/weiloon1234/Foundry-Go/value.Optional[foundry.test/consumer/articles.SEO]", Kind: foundrycontract.Kind("alias"), Nullable: false,
			Element: "foundry.test/consumer/articles.SEO",
		},
		{ID: "github.com/weiloon1234/Foundry-Go/value.Optional[string]", Kind: foundrycontract.Kind("alias"), Nullable: false,
			Element: "string",
		},
		foundrycontract.JSONMapType[map[i18n.LocaleID]string]("go:3b116365e8100fa0774841a4f3971426d59a3d3b2a85917e7c2c2cd61ae68f67", "string", "github.com/weiloon1234/Foundry-Go/i18n.LocaleID", foundrycontract.StringJSONKey[i18n.LocaleID]()),
		{ID: "go:4af101177fe720bf0766557228231c42b38635920ef7206f518a04030b3dcdf0", Kind: foundrycontract.Kind("array"), Nullable: true,
			Element: "string",
		},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
})

// ArticleInputValidationFieldSet retains concrete DTO and value types for validation.
type ArticleInputValidationFieldSet struct {
	// Author validates the declared JSON property "author".
	Author foundryvalidation.Field[ArticleInput, string]
	// SEO validates the declared JSON property "seo".
	SEO foundryvalidation.Field[ArticleInput, foundryvalue.Optional[SEO]]
	// Slug validates the declared JSON property "slug".
	Slug foundryvalidation.Field[ArticleInput, string]
	// Summary validates the declared JSON property "summary".
	Summary foundryvalidation.Field[ArticleInput, map[i18n.LocaleID]string]
	// Title validates the declared JSON property "title".
	Title foundryvalidation.Field[ArticleInput, map[i18n.LocaleID]string]
}

// ArticleInputValidationFields returns typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func ArticleInputValidationFields() ArticleInputValidationFieldSet {
	return foundryArticleInputValidationFields()
}

var foundryArticleInputValidationFields = sync.OnceValue(func() ArticleInputValidationFieldSet {
	return ArticleInputValidationFieldSet{
		Author: foundryvalidation.DefineField("author", func(input ArticleInput) string {
			return input.Author
		}),
		SEO: foundryvalidation.DefineField("seo", func(input ArticleInput) foundryvalue.Optional[SEO] {
			return input.SEO
		}),
		Slug: foundryvalidation.DefineField("slug", func(input ArticleInput) string {
			return input.Slug
		}),
		Summary: foundryvalidation.DefineField("summary", func(input ArticleInput) map[i18n.LocaleID]string {
			return input.Summary
		}),
		Title: foundryvalidation.DefineField("title", func(input ArticleInput) map[i18n.LocaleID]string {
			return input.Title
		}),
	}
})
