// Code generated by foundry generate; DO NOT EDIT.
// Source: models.go:18.

package linkqueries

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	relation "github.com/weiloon1234/Foundry-Go/database/relation"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
	time "time"
)

// MemberFieldSet exposes fields owned by the unaliased model.
type MemberFieldSet = MemberScopedFieldSet[Member]

// MemberFields returns independent immutable field descriptors.
func MemberFields() MemberFieldSet {
	return MemberFieldsAt(foundryquery.DeclareModelScope[Member]("link_members"))
}

// MemberScopedFieldSet preserves typed field operators in a declared query scope.
type MemberScopedFieldSet[FoundryScope any] struct {
	// ID describes link_members.id.
	ID foundryquery.ScalarField[FoundryScope, model.ID[Member]]
	// Name describes link_members.name.
	Name foundryquery.TextField[FoundryScope, string]
	// Alias describes link_members.alias.
	Alias foundryquery.NullableTextField[FoundryScope, string]
	// DeletedAt describes link_members.deleted_at.
	// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
	DeletedAt foundryquery.NullableOrderedField[FoundryScope, time.Time]
}

// MemberFieldsAt binds these record fields to an alias or joined scope.
func MemberFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, Member]) MemberScopedFieldSet[FoundryScope] {
	return MemberScopedFieldSet[FoundryScope]{
		ID:        foundryquery.NewScalarField[FoundryScope, model.ID[Member]](scope.Table(), "id", codec.ID[Member]()),
		Name:      foundryquery.NewTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
		Alias:     foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "alias", codec.String[string]()),
		DeletedAt: foundryquery.NewNullableOrderedField[FoundryScope, time.Time](scope.Table(), "deleted_at", codec.Time()),
	}
}

// MemberNullableFieldSet preserves typed field operators in a declared query scope.
type MemberNullableFieldSet[FoundryScope any] struct {
	// ID describes link_members.id.
	ID foundryquery.NullableField[FoundryScope, model.ID[Member]]
	// Name describes link_members.name.
	Name foundryquery.NullableTextField[FoundryScope, string]
	// Alias describes link_members.alias.
	Alias foundryquery.NullableTextField[FoundryScope, string]
	// DeletedAt describes link_members.deleted_at.
	// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
	DeletedAt foundryquery.NullableOrderedField[FoundryScope, time.Time]
}

// MemberNullableFieldsAt binds these record fields to an alias or joined scope.
func MemberNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, Member]) MemberNullableFieldSet[FoundryScope] {
	return MemberNullableFieldSet[FoundryScope]{
		ID:        foundryquery.NewNullableField[FoundryScope, model.ID[Member]](scope.Table(), "id", codec.ID[Member]()),
		Name:      foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
		Alias:     foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "alias", codec.String[string]()),
		DeletedAt: foundryquery.NewNullableOrderedField[FoundryScope, time.Time](scope.Table(), "deleted_at", codec.Time()),
	}
}

// MemberQuery preserves model-specific keys through fluent query derivation.
type MemberQuery struct{ foundryquery.Query[Member] }

// QueryLinkMembers starts a complete-model query for link_members with generated hydration.
func QueryLinkMembers() MemberQuery {
	return MemberQuery{foundryquery.ForModel(foundryquery.Define[Member]("link_members", "id", []foundryquery.Column{foundryquery.Column{Name: "id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "name", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "alias", Nullable: true, DatabaseDefault: false}, foundryquery.Column{Name: "deleted_at", Nullable: true, DatabaseDefault: false}}, func(row database.Row) (Member, error) {
		var item Member
		if err := row.Scan(
			codec.ID[Member]().Scan(&item.ID),
			codec.String[string]().Scan(&item.Name),
			codec.Nullable(codec.String[string]()).Scan(&item.Alias),
			codec.Nullable(codec.Time()).Scan(&item.DeletedAt),
		); err != nil {
			return Member{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("id", codec.ID[Member](), func(item Member) model.ID[Member] { return item.ID }),
		foundryquery.NewModelField("name", codec.String[string](), func(item Member) string { return item.Name }),
		foundryquery.NewModelField("alias", codec.Nullable(codec.String[string]()), func(item Member) foundryvalue.Nullable[string] { return item.Alias }),
		foundryquery.NewModelField("deleted_at", codec.Nullable(codec.Time()), func(item Member) foundryvalue.Nullable[time.Time] { return item.DeletedAt }),
	).WithSoftDeletes("deleted_at").WithObserverHooks((MemberHooks{}).foundryWriteHooks, false).WithRetrievalHooks((MemberRetrievalHooks{}).foundryRetrievalHooks, true))}
}

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (Member) FoundryQuery() foundryquery.Query[Member] { return QueryLinkMembers().Query }

// FoundryReference retains Member and its concrete stored primary key for framework integrations.
// It reads ID directly, never calls an accessor, and performs no database lookup.
func (m Member) FoundryReference() model.Reference[Member, model.ID[Member]] {
	return model.NewReference[Member]("link_members", m.ID, codec.ID[Member]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m Member) FoundryIdentity() (model.Identity, error) { return m.FoundryReference().Identity() }

// WithTrashed derives a new Member query without changing its source.
func (q MemberQuery) WithTrashed() MemberQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new Member query without changing its source.
func (q MemberQuery) OnlyTrashed() MemberQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new Member query without changing its source.
func (q MemberQuery) WithoutTrashed() MemberQuery { q.Query = q.Query.WithoutTrashed(); return q }

// Where derives a new Member query without changing its source.
func (q MemberQuery) Where(predicates ...foundryquery.Predicate[Member]) MemberQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new Member query without changing its source.
func (q MemberQuery) WhereHas(relation foundryquery.ExistenceRelation[Member]) MemberQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new Member query without changing its source.
func (q MemberQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Member]) MemberQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new Member query without changing its source.
func (q MemberQuery) OrderBy(orders ...foundryquery.Order[Member]) MemberQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new Member query without changing its source.
func (q MemberQuery) Limit(count int) MemberQuery { q.Query = q.Query.Limit(count); return q }

// Offset derives a new Member query without changing its source.
func (q MemberQuery) Offset(count int) MemberQuery { q.Query = q.Query.Offset(count); return q }

// With derives a new Member query without changing its source.
func (q MemberQuery) With(relations ...foundryquery.Relation[Member]) MemberQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new Member query without changing its source.
func (q MemberQuery) WithRelationLimits(limits foundryquery.RelationLimits) MemberQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q MemberQuery) Find(ctx context.Context, executor database.Executor, key model.ID[Member]) (foundryvalue.Optional[Member], error) {
	return q.Where(MemberFields().ID.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q MemberQuery) RequireFind(ctx context.Context, executor database.Executor, key model.ID[Member]) (Member, error) {
	return q.Where(MemberFields().ID.Eq(key)).RequireFirst(ctx, executor)
}

// MemberLockedQuery preserves typed keys while requiring transaction-scoped reads.
type MemberLockedQuery struct {
	foundryquery.LockedQuery[Member]
}

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q MemberQuery) ForUpdate() MemberLockedQuery { return MemberLockedQuery{q.Query.ForUpdate()} }

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q MemberQuery) ForNoKeyUpdate() MemberLockedQuery {
	return MemberLockedQuery{q.Query.ForNoKeyUpdate()}
}

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q MemberQuery) ForShare() MemberLockedQuery { return MemberLockedQuery{q.Query.ForShare()} }

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q MemberQuery) ForKeyShare() MemberLockedQuery { return MemberLockedQuery{q.Query.ForKeyShare()} }

// WithTrashed derives a locked Member query without changing its source.
func (q MemberLockedQuery) WithTrashed() MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked Member query without changing its source.
func (q MemberLockedQuery) OnlyTrashed() MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked Member query without changing its source.
func (q MemberLockedQuery) WithoutTrashed() MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// Where derives a locked Member query without changing its source.
func (q MemberLockedQuery) Where(predicates ...foundryquery.Predicate[Member]) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked Member query without changing its source.
func (q MemberLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[Member]) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked Member query without changing its source.
func (q MemberLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Member]) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked Member query without changing its source.
func (q MemberLockedQuery) OrderBy(orders ...foundryquery.Order[Member]) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked Member query without changing its source.
func (q MemberLockedQuery) Limit(count int) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked Member query without changing its source.
func (q MemberLockedQuery) Offset(count int) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked Member query without changing its source.
func (q MemberLockedQuery) With(relations ...foundryquery.Relation[Member]) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked Member query without changing its source.
func (q MemberLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked Member query without changing its source.
func (q MemberLockedQuery) NoWait() MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.NoWait()
	return q
}

// SkipLocked derives a locked Member query without changing its source.
func (q MemberLockedQuery) SkipLocked() MemberLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked Member query without changing its source.
func (q MemberLockedQuery) Wait() MemberLockedQuery { q.LockedQuery = q.LockedQuery.Wait(); return q }

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q MemberLockedQuery) Find(ctx context.Context, tx *database.Tx, key model.ID[Member]) (foundryvalue.Optional[Member], error) {
	return q.Where(MemberFields().ID.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q MemberLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key model.ID[Member]) (Member, error) {
	return q.Where(MemberFields().ID.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q MemberQuery) Create(ctx context.Context, writer database.Transactor, draft MemberDraft) (Member, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return Member{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q MemberQuery) Upsert(ctx context.Context, writer database.Transactor, draft MemberDraft, conflict foundryquery.Conflict[Member]) (foundryvalue.Optional[Member], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[Member]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q MemberQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []MemberDraft) ([]Member, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q MemberQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []MemberDraft, conflict foundryquery.Conflict[Member]) ([]Member, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q MemberQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []MemberDraft, conflict *foundryquery.Conflict[Member]) ([]Member, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q MemberQuery) foundryCreateMutations(drafts []MemberDraft) ([]foundryquery.Mutation[Member], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[Member], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q MemberQuery) Update(ctx context.Context, writer database.Transactor, key model.ID[Member], draft MemberDraft) (Member, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return Member{}, err
	}
	return q.Where(MemberFields().ID.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete soft-deletes one active typed primary key within this query's filters and returns its stored result.
func (q MemberQuery) Delete(ctx context.Context, writer database.Transactor, key model.ID[Member]) (Member, error) {
	return q.Where(MemberFields().ID.Eq(key)).Query.Remove(ctx, writer)
}

// Restore restores one deleted typed primary key, retaining explicit filters and returning the stored result.
func (q MemberQuery) Restore(ctx context.Context, writer database.Transactor, key model.ID[Member]) (Member, error) {
	return q.Where(MemberFields().ID.Eq(key)).Query.Restore(ctx, writer)
}

// ForceDelete physically removes one typed primary key within the current visibility and filters. WithTrashed includes deleted models.
func (q MemberQuery) ForceDelete(ctx context.Context, writer database.Transactor, key model.ID[Member]) (Member, error) {
	return q.Where(MemberFields().ID.Eq(key)).Query.ForceRemove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q MemberQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []MemberDraft) ([]Member, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q MemberQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, Member) (MemberDraft, error)) ([]Member, error) {
	var callback func(context.Context, *database.Tx, Member) (foundryquery.Mutation[Member], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Member) (foundryquery.Mutation[Member], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q MemberQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// RestoreEach restores each deleted model matching the explicit predicates through its normal lifecycle. The positive limit bounds the complete atomic candidate set.
func (q MemberQuery) RestoreEach(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	return q.Query.RestoreEach(ctx, writer, limit)
}

// ForceDeleteEach physically removes each matching soft-delete model through its normal force-delete lifecycle. Visibility is retained; the positive limit bounds the complete atomic candidate set.
func (q MemberQuery) ForceDeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	return q.Query.ForceRemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q MemberQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create MemberDraft) (Member, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q MemberQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create MemberDraft, draft func(context.Context, *database.Tx, Member) (MemberDraft, error)) (Member, error) {
	var callback func(context.Context, *database.Tx, Member) (foundryquery.Mutation[Member], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Member) (foundryquery.Mutation[Member], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// MemberInsertFromBuilder selects stored SQL values into Member through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type MemberInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, Member]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p MemberInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertMemberFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertMemberFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) MemberInsertFromBuilder[FoundryScope] {
	return MemberInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (Member{}).FoundryQuery())}
}

// SelectID supplies the stored SQL value for id. It cannot also be supplied by Values.
func (p MemberInsertFromBuilder[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, model.ID[Member]]) MemberInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(MemberFields().ID, v))
	return p
}

// SelectName supplies the stored SQL value for name. It cannot also be supplied by Values.
func (p MemberInsertFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) MemberInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(MemberFields().Name, v))
	return p
}

// SelectAlias supplies the stored SQL value for alias. It cannot also be supplied by Values.
func (p MemberInsertFromBuilder[FoundryScope]) SelectAlias(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) MemberInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(MemberFields().Alias, v))
	return p
}

// SelectDeletedAt supplies the stored SQL value for deleted_at. It cannot also be supplied by Values.
// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
func (p MemberInsertFromBuilder[FoundryScope]) SelectDeletedAt(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[time.Time]]) MemberInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(MemberFields().DeletedAt, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p MemberInsertFromBuilder[FoundryScope]) Values(draft MemberDraft) MemberInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p MemberInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p MemberInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// MemberUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type MemberUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, Member]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p MemberUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdateMemberFrom preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func UpdateMemberFrom[FoundryScope any](destination MemberQuery, source foundryquery.ProjectionSource[FoundryScope]) MemberUpdateFromBuilder[FoundryScope] {
	return MemberUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p MemberUpdateFromBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Member]]) MemberUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(MemberFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p MemberUpdateFromBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Member]]]) MemberUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(MemberFields().ID, v))
	return p
}

// SelectName assigns a stored source value to name; Values cannot also supply it.
func (p MemberUpdateFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) MemberUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(MemberFields().Name, v))
	return p
}

// SelectAlias assigns a stored source value to alias; Values cannot also supply it.
func (p MemberUpdateFromBuilder[FoundryScope]) SelectAlias(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) MemberUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(MemberFields().Alias, v))
	return p
}

// SelectDeletedAt assigns a stored source value to deleted_at; Values cannot also supply it.
// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
func (p MemberUpdateFromBuilder[FoundryScope]) SelectDeletedAt(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[time.Time]]) MemberUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(MemberFields().DeletedAt, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p MemberUpdateFromBuilder[FoundryScope]) Values(draft MemberDraft) MemberUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p MemberUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p MemberUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// MemberDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type MemberDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, Member]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p MemberDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeleteMemberUsing preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func DeleteMemberUsing[FoundryScope any](destination MemberQuery, source foundryquery.ProjectionSource[FoundryScope]) MemberDeleteUsingBuilder[FoundryScope] {
	return MemberDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// ForceDeleteMemberUsing physically removes matching models with the destination's explicit visibility.
// Use WithTrashed on the destination to include already deleted models.
func ForceDeleteMemberUsing[FoundryScope any](destination MemberQuery, source foundryquery.ProjectionSource[FoundryScope]) MemberDeleteUsingBuilder[FoundryScope] {
	return MemberDeleteUsingBuilder[FoundryScope]{plan: foundryquery.ForceDeleteUsing(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p MemberDeleteUsingBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Member]]) MemberDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(MemberFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p MemberDeleteUsingBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Member]]]) MemberDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(MemberFields().ID, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p MemberDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p MemberDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Member, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d MemberDraft) FoundryCreateMutation(defaults foundryquery.Mutation[Member]) (foundryquery.Mutation[Member], error) {
	values, err := foundryquery.ReadCreateDefaults((Member{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[Member]{}, err
	}
	if !d.fieldID.IsSet() {
		v, err := foundryquery.MutationValue[Member, model.ID[Member]](values, "link_members", "id")
		if err != nil {
			return foundryquery.Mutation[Member]{}, err
		}
		d.fieldID = v
	}
	if !d.fieldName.IsSet() {
		v, err := foundryquery.MutationValue[Member, string](values, "link_members", "name")
		if err != nil {
			return foundryquery.Mutation[Member]{}, err
		}
		d.fieldName = v
	}
	if !d.fieldAlias.IsSet() {
		v, err := foundryquery.MutationValue[Member, foundryvalue.Nullable[string]](values, "link_members", "alias")
		if err != nil {
			return foundryquery.Mutation[Member]{}, err
		}
		d.fieldAlias = v
	}
	if !d.fieldDeletedAt.IsSet() {
		v, err := foundryquery.MutationValue[Member, foundryvalue.Nullable[time.Time]](values, "link_members", "deleted_at")
		if err != nil {
			return foundryquery.Mutation[Member]{}, err
		}
		d.fieldDeletedAt = v
	}
	return d.foundryMutation(true)
}
func (d MemberDraft) foundryMutation(create bool) (foundryquery.Mutation[Member], error) {
	if create && !d.fieldID.IsSet() {
		id, err := model.NewID[Member]()
		if err != nil {
			return foundryquery.Mutation[Member]{}, err
		}
		d = d.SetID(id)
	}
	var assignments []foundryquery.Assignment[Member]
	if v, set := d.fieldID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Member]("link_members", "id", codec.ID[Member](), v))
	}
	if v, set := d.fieldName.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Member]("link_members", "name", codec.String[string](), v))
	}
	if v, set := d.fieldAlias.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Member]("link_members", "alias", codec.Nullable(codec.String[string]()), v))
	}
	if v, set := d.fieldDeletedAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Member]("link_members", "deleted_at", codec.Nullable(codec.Time()), v))
	}
	return foundryquery.Change(assignments...), nil
}

// MemberRelationSet requires typed descriptors matching every declared relation slot.
type MemberRelationSet struct {
	Groups      foundryquery.ThroughRelation[Member, Group, Membership]
	NamedGroups foundryquery.ThroughRelation[Member, Group, NaturalLink]
	AliasGroups foundryquery.ThroughRelation[Member, Group, NullableLink]
	Friends     foundryquery.ThroughRelation[Member, Member, Friendship]
}

// MemberRelations binds handwritten key declarations to generated model metadata and typed slots.
func MemberRelations() MemberRelationSet {
	relations := (Member{}).DefineRelations()
	relations.Groups = relations.Groups.Bind("Groups", QueryLinkMembers().Query, (Group{}).FoundryQuery(), (Membership{}).FoundryQuery(), func(m Member) relation.Through[Group, Membership] { return m.Groups }, func(m Member, loaded relation.Through[Group, Membership]) Member { m.Groups = loaded; return m })
	relations.NamedGroups = relations.NamedGroups.Bind("NamedGroups", QueryLinkMembers().Query, (Group{}).FoundryQuery(), (NaturalLink{}).FoundryQuery(), func(m Member) relation.Through[Group, NaturalLink] { return m.NamedGroups }, func(m Member, loaded relation.Through[Group, NaturalLink]) Member { m.NamedGroups = loaded; return m })
	relations.AliasGroups = relations.AliasGroups.Bind("AliasGroups", QueryLinkMembers().Query, (Group{}).FoundryQuery(), (NullableLink{}).FoundryQuery(), func(m Member) relation.Through[Group, NullableLink] { return m.AliasGroups }, func(m Member, loaded relation.Through[Group, NullableLink]) Member { m.AliasGroups = loaded; return m })
	relations.Friends = relations.Friends.Bind("Friends", QueryLinkMembers().Query, (Member{}).FoundryQuery(), (Friendship{}).FoundryQuery(), func(m Member) relation.Through[Member, Friendship] { return m.Friends }, func(m Member, loaded relation.Through[Member, Friendship]) Member { m.Friends = loaded; return m })
	return relations
}

// MemberDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type MemberDraft struct {
	fieldID        foundryvalue.Optional[model.ID[Member]]
	fieldName      foundryvalue.Optional[string]
	fieldAlias     foundryvalue.Optional[foundryvalue.Nullable[string]]
	fieldDeletedAt foundryvalue.Optional[foundryvalue.Nullable[time.Time]]
}

// ID returns the typed mutation state for id.
func (d MemberDraft) ID() foundryvalue.Optional[model.ID[Member]] { return d.fieldID }

// SetID returns a new draft with id explicitly set.
func (d MemberDraft) SetID(v model.ID[Member]) MemberDraft { d.fieldID = foundryvalue.Set(v); return d }

// UnsetID omits id without requesting a zero or null write.
func (d MemberDraft) UnsetID() MemberDraft {
	d.fieldID = foundryvalue.Optional[model.ID[Member]]{}
	return d
}

// Name returns the typed mutation state for name.
func (d MemberDraft) Name() foundryvalue.Optional[string] { return d.fieldName }

// SetName returns a new draft with name explicitly set.
func (d MemberDraft) SetName(v string) MemberDraft { d.fieldName = foundryvalue.Set(v); return d }

// UnsetName omits name without requesting a zero or null write.
func (d MemberDraft) UnsetName() MemberDraft { d.fieldName = foundryvalue.Optional[string]{}; return d }

// Alias returns the typed mutation state for alias.
func (d MemberDraft) Alias() foundryvalue.Optional[foundryvalue.Nullable[string]] {
	return d.fieldAlias
}

// SetAlias returns a new draft with alias explicitly set.
func (d MemberDraft) SetAlias(v string) MemberDraft {
	d.fieldAlias = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetAlias omits alias without requesting a zero or null write.
func (d MemberDraft) UnsetAlias() MemberDraft {
	d.fieldAlias = foundryvalue.Optional[foundryvalue.Nullable[string]]{}
	return d
}

// ClearAlias explicitly sets alias to null.
func (d MemberDraft) ClearAlias() MemberDraft {
	d.fieldAlias = foundryvalue.Set(foundryvalue.Null[string]())
	return d
}

// DeletedAt returns the typed mutation state for deleted_at.
// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
func (d MemberDraft) DeletedAt() foundryvalue.Optional[foundryvalue.Nullable[time.Time]] {
	return d.fieldDeletedAt
}

// SetDeletedAt returns a new draft with deleted_at explicitly set.
// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
func (d MemberDraft) SetDeletedAt(v time.Time) MemberDraft {
	d.fieldDeletedAt = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetDeletedAt omits deleted_at without requesting a zero or null write.
func (d MemberDraft) UnsetDeletedAt() MemberDraft {
	d.fieldDeletedAt = foundryvalue.Optional[foundryvalue.Nullable[time.Time]]{}
	return d
}

// ClearDeletedAt explicitly sets deleted_at to null.
func (d MemberDraft) ClearDeletedAt() MemberDraft {
	d.fieldDeletedAt = foundryvalue.Set(foundryvalue.Null[time.Time]())
	return d
}

// IsEmpty reports whether no fields have been selected for mutation.
func (d MemberDraft) IsEmpty() bool {
	return !d.fieldID.IsSet() && !d.fieldName.IsSet() && !d.fieldAlias.IsSet() && !d.fieldDeletedAt.IsSet()
}

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (MemberDraft) Format(state fmt.State, _ rune) { _, _ = state.Write([]byte("Member draft")) }

// MemberFieldChanges contains typed changes for persisted fields only.
type MemberFieldChanges struct {
	// ID retains the typed change for id.
	ID lifecycle.FieldChange[model.ID[Member]]
	// Name retains the typed change for name.
	Name lifecycle.FieldChange[string]
	// Alias retains the typed change for alias.
	Alias lifecycle.FieldChange[foundryvalue.Nullable[string]]
	// DeletedAt retains the typed change for deleted_at.
	DeletedAt lifecycle.FieldChange[foundryvalue.Nullable[time.Time]]
}

// MemberChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type MemberChanges struct {
	before, after foundryvalue.Optional[Member]
	fields        MemberFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c MemberChanges) Operation() foundryvalue.Optional[lifecycle.Operation] { return c.operation }

// Before returns the persisted model before the operation, or absence for creation.
func (c MemberChanges) Before() foundryvalue.Optional[Member] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c MemberChanges) After() foundryvalue.Optional[Member] { return c.after }

// Fields returns model-specific field changes by value.
func (c MemberChanges) Fields() MemberFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c MemberChanges) Assigned() bool {
	return c.fields.ID.Assigned() || c.fields.Name.Assigned() || c.fields.Alias.Assigned() || c.fields.DeletedAt.Assigned()
}

// Changed reports whether any persisted field is changed.
func (c MemberChanges) Changed() bool {
	return c.fields.ID.Changed() || c.fields.Name.Changed() || c.fields.Alias.Changed() || c.fields.DeletedAt.Changed()
}

// String and GoString keep model snapshots out of routine diagnostics.
func (MemberChanges) String() string     { return "Member changes" }
func (c MemberChanges) GoString() string { return c.String() }

// CompareMember is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func CompareMember(before, after foundryvalue.Optional[Member], assigned MemberDraft) (MemberChanges, error) {
	before = foundryMemberSnapshot(before)
	after = foundryMemberSnapshot(after)
	var changes MemberChanges
	var err error
	changes.fields.ID, err = lifecycle.CompareModelField(codec.ID[Member](), before, after, assigned.fieldID.IsSet(), func(item Member) model.ID[Member] { return item.ID })
	if err != nil {
		return MemberChanges{}, fmt.Errorf("compare Member.ID: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.ID.Changed() || changes.fields.ID.Assigned()) {
		return MemberChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.Name, err = lifecycle.CompareModelField(codec.String[string](), before, after, assigned.fieldName.IsSet(), func(item Member) string { return item.Name })
	if err != nil {
		return MemberChanges{}, fmt.Errorf("compare Member.Name: %w", err)
	}
	changes.fields.Alias, err = lifecycle.CompareModelField(codec.Nullable(codec.String[string]()), before, after, assigned.fieldAlias.IsSet(), func(item Member) foundryvalue.Nullable[string] { return item.Alias })
	if err != nil {
		return MemberChanges{}, fmt.Errorf("compare Member.Alias: %w", err)
	}
	changes.fields.DeletedAt, err = lifecycle.CompareModelField(codec.Nullable(codec.Time()), before, after, assigned.fieldDeletedAt.IsSet(), func(item Member) foundryvalue.Nullable[time.Time] { return item.DeletedAt })
	if err != nil {
		return MemberChanges{}, fmt.Errorf("compare Member.DeletedAt: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryMemberSnapshot(snapshot foundryvalue.Optional[Member]) foundryvalue.Optional[Member] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[Member]{}
	}
	return foundryvalue.Set(Member{
		ID:        item.ID,
		Name:      item.Name,
		Alias:     item.Alias,
		DeletedAt: item.DeletedAt,
	})
}

// MemberHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type MemberHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[Member], *MemberDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *MemberDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, Member, *MemberDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, Member) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, Member) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, Member) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, MemberChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, MemberChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, MemberChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, MemberChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, MemberChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, MemberChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, MemberChanges) error
}

// MemberObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type MemberObserver = lifecycle.Observer[Member, MemberHooks]

// NewMemberObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewMemberObserver(observer string) MemberObserver {
	return lifecycle.NewObserver[Member, MemberHooks](observer)
}

// RegisterMemberObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterMemberObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer MemberObserver, construct func(foundation.Resolver) (func() MemberHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (MemberHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[Member], error) {
	factories, err := lifecycle.ObserverFactories[Member, MemberHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[Member]{}, err
	}
	var allHooks []MemberHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Member]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[Member]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Member]{}, err
	}
	return foundryquery.WriteHooks[Member]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[Member], mutation foundryquery.Mutation[Member]) (foundryquery.Mutation[Member], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			var draft MemberDraft
			draft.fieldID, err = foundryquery.MutationValue[Member, model.ID[Member]](values, "link_members", "id")
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			draft.fieldName, err = foundryquery.MutationValue[Member, string](values, "link_members", "name")
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			draft.fieldAlias, err = foundryquery.MutationValue[Member, foundryvalue.Nullable[string]](values, "link_members", "alias")
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			draft.fieldDeletedAt, err = foundryquery.MutationValue[Member, foundryvalue.Nullable[time.Time]](values, "link_members", "deleted_at")
			if err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[Member]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Member]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Member]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[Member]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[Member]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Member]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Member]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Member]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Member]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Member]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[Member]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[Member], mutation foundryquery.Mutation[Member]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft MemberDraft
			if values.Has("link_members", "id") {
				var zero model.ID[Member]
				draft.fieldID = foundryvalue.Set(zero)
			}
			if values.Has("link_members", "name") {
				var zero string
				draft.fieldName = foundryvalue.Set(zero)
			}
			if values.Has("link_members", "alias") {
				var zero foundryvalue.Nullable[string]
				draft.fieldAlias = foundryvalue.Set(zero)
			}
			if values.Has("link_members", "deleted_at") {
				var zero foundryvalue.Nullable[time.Time]
				draft.fieldDeletedAt = foundryvalue.Set(zero)
			}
			changes, err := CompareMember(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// MemberRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type MemberRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, Member) error
}

// MemberRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type MemberRetrievalObserver = lifecycle.Observer[Member, MemberRetrievalHooks]

// NewMemberRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewMemberRetrievalObserver(observer string) MemberRetrievalObserver {
	return lifecycle.NewRetrievalObserver[Member, MemberRetrievalHooks](observer)
}

// RegisterMemberRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterMemberRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer MemberRetrievalObserver, construct func(foundation.Resolver) (func() MemberRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (MemberRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[Member], error) {
	factories, err := lifecycle.RetrievalObserverFactories[Member, MemberRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[Member]{}, err
	}
	var allHooks []MemberRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Member]{}, err
	}
	allHooks = append(allHooks, memberReads())
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[Member]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Member]{}, err
	}
	return foundryquery.RetrievalHooks[Member]{Retrieved: func(ctx context.Context, executor database.Executor, item Member) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// MemberAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type MemberAuditPolicy struct {
	_ [0]*Member
	// ID controls the audit representation of stored link_members.id.
	ID record.Disclosure
	// Name controls the audit representation of stored link_members.name.
	Name record.Disclosure
	// Alias controls the audit representation of stored link_members.alias.
	Alias record.Disclosure
	// DeletedAt controls the audit representation of stored link_members.deleted_at.
	DeletedAt record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes MemberChanges) Audit(policy MemberAuditPolicy) (record.Model[Member, model.ID[Member]], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[Member, model.ID[Member]]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[Member, model.ID[Member]]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "id", policy.ID)
	if err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	var captured record.Field[Member]
	captured, err = record.CaptureField[Member]("id", codec.ID[Member](), changes.fields.ID, policy.ID)
	if err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	captured, err = record.CaptureField[Member]("name", codec.String[string](), changes.fields.Name, policy.Name)
	if err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	captured, err = record.CaptureField[Member]("alias", codec.Nullable(codec.String[string]()), changes.fields.Alias, policy.Alias)
	if err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	captured, err = record.CaptureField[Member]("deleted_at", codec.Nullable(codec.Time()), changes.fields.DeletedAt, policy.DeletedAt)
	if err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Member, model.ID[Member]]{}, err
	}
	return builder.Build()
}

// MemberAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type MemberAuditFieldSet struct {
	_ [0]*Member
	// ID retains stored link_members.id after write mutators; read accessors do not replace audit values.
	ID foundryvalue.Optional[record.FieldChange[model.ID[Member]]]
	// Name retains stored link_members.name after write mutators; read accessors do not replace audit values.
	Name foundryvalue.Optional[record.FieldChange[string]]
	// Alias retains stored link_members.alias after write mutators; read accessors do not replace audit values.
	Alias foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[string]]]
	// DeletedAt retains stored link_members.deleted_at after write mutators; read accessors do not replace audit values.
	// Managed soft-delete timestamp: Delete sets this stored field and Restore clears it. Ordinary queries exclude deleted models; WithTrashed and OnlyTrashed select visibility explicitly. Assigning this field directly through a draft uses ordinary create/update hooks rather than deletion/restoration events.
	DeletedAt foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[time.Time]]]
}

// MemberAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func MemberAuditFields(history record.Model[Member, model.ID[Member]]) (MemberAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return MemberAuditFieldSet{}, err
	}
	var fields MemberAuditFieldSet
	fields.ID, err = record.ReadField(view, "id", codec.ID[Member]())
	if err != nil {
		return MemberAuditFieldSet{}, err
	}
	fields.Name, err = record.ReadField(view, "name", codec.String[string]())
	if err != nil {
		return MemberAuditFieldSet{}, err
	}
	fields.Alias, err = record.ReadField(view, "alias", codec.Nullable(codec.String[string]()))
	if err != nil {
		return MemberAuditFieldSet{}, err
	}
	fields.DeletedAt, err = record.ReadField(view, "deleted_at", codec.Nullable(codec.Time()))
	if err != nil {
		return MemberAuditFieldSet{}, err
	}
	return fields, nil
}

// MemberAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func MemberAuditing(policy MemberAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[Member]()
		if err != nil {
			return err
		}
		return RegisterMemberObserver(registrar, pool, NewMemberObserver(name), func(resolver foundation.Resolver) (func() MemberHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() MemberHooks {
				write := func(ctx context.Context, tx *database.Tx, changes MemberChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return MemberHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
