// Code generated by foundry generate; DO NOT EDIT.
// Source: models.go:67.

package linkqueries

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
)

// NullableLinkFieldSet exposes fields owned by the unaliased model.
type NullableLinkFieldSet = NullableLinkScopedFieldSet[NullableLink]

// NullableLinkFields returns independent immutable field descriptors.
func NullableLinkFields() NullableLinkFieldSet {
	return NullableLinkFieldsAt(foundryquery.DeclareModelScope[NullableLink]("link_nullable"))
}

// NullableLinkScopedFieldSet preserves typed field operators in a declared query scope.
type NullableLinkScopedFieldSet[FoundryScope any] struct {
	// ID describes link_nullable.id.
	ID foundryquery.ScalarField[FoundryScope, model.ID[NullableLink]]
	// MemberAlias describes link_nullable.member_alias.
	MemberAlias foundryquery.NullableTextField[FoundryScope, string]
	// GroupName describes link_nullable.group_name.
	GroupName foundryquery.NullableTextField[FoundryScope, string]
}

// NullableLinkFieldsAt binds these record fields to an alias or joined scope.
func NullableLinkFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, NullableLink]) NullableLinkScopedFieldSet[FoundryScope] {
	return NullableLinkScopedFieldSet[FoundryScope]{
		ID:          foundryquery.NewScalarField[FoundryScope, model.ID[NullableLink]](scope.Table(), "id", codec.ID[NullableLink]()),
		MemberAlias: foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "member_alias", codec.String[string]()),
		GroupName:   foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "group_name", codec.String[string]()),
	}
}

// NullableLinkNullableFieldSet preserves typed field operators in a declared query scope.
type NullableLinkNullableFieldSet[FoundryScope any] struct {
	// ID describes link_nullable.id.
	ID foundryquery.NullableField[FoundryScope, model.ID[NullableLink]]
	// MemberAlias describes link_nullable.member_alias.
	MemberAlias foundryquery.NullableTextField[FoundryScope, string]
	// GroupName describes link_nullable.group_name.
	GroupName foundryquery.NullableTextField[FoundryScope, string]
}

// NullableLinkNullableFieldsAt binds these record fields to an alias or joined scope.
func NullableLinkNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, NullableLink]) NullableLinkNullableFieldSet[FoundryScope] {
	return NullableLinkNullableFieldSet[FoundryScope]{
		ID:          foundryquery.NewNullableField[FoundryScope, model.ID[NullableLink]](scope.Table(), "id", codec.ID[NullableLink]()),
		MemberAlias: foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "member_alias", codec.String[string]()),
		GroupName:   foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "group_name", codec.String[string]()),
	}
}

// NullableLinkQuery preserves model-specific keys through fluent query derivation.
type NullableLinkQuery struct {
	foundryquery.Query[NullableLink]
}

// QueryLinkNullable starts a complete-model query for link_nullable with generated hydration.
func QueryLinkNullable() NullableLinkQuery {
	return NullableLinkQuery{foundryquery.ForModel(foundryquery.Define[NullableLink]("link_nullable", "id", []foundryquery.Column{foundryquery.Column{Name: "id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "member_alias", Nullable: true, DatabaseDefault: false}, foundryquery.Column{Name: "group_name", Nullable: true, DatabaseDefault: false}}, func(row database.Row) (NullableLink, error) {
		var item NullableLink
		if err := row.Scan(
			codec.ID[NullableLink]().Scan(&item.ID),
			codec.Nullable(codec.String[string]()).Scan(&item.MemberAlias),
			codec.Nullable(codec.String[string]()).Scan(&item.GroupName),
		); err != nil {
			return NullableLink{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("id", codec.ID[NullableLink](), func(item NullableLink) model.ID[NullableLink] { return item.ID }),
		foundryquery.NewModelField("member_alias", codec.Nullable(codec.String[string]()), func(item NullableLink) foundryvalue.Nullable[string] { return item.MemberAlias }),
		foundryquery.NewModelField("group_name", codec.Nullable(codec.String[string]()), func(item NullableLink) foundryvalue.Nullable[string] { return item.GroupName }),
	).WithObserverHooks((NullableLinkHooks{}).foundryWriteHooks, false).WithRetrievalHooks((NullableLinkRetrievalHooks{}).foundryRetrievalHooks, false))}
}

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (NullableLink) FoundryQuery() foundryquery.Query[NullableLink] { return QueryLinkNullable().Query }

// FoundryReference retains NullableLink and its concrete stored primary key for framework integrations.
// It reads ID directly, never calls an accessor, and performs no database lookup.
func (m NullableLink) FoundryReference() model.Reference[NullableLink, model.ID[NullableLink]] {
	return model.NewReference[NullableLink]("link_nullable", m.ID, codec.ID[NullableLink]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m NullableLink) FoundryIdentity() (model.Identity, error) {
	return m.FoundryReference().Identity()
}

// WithTrashed derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) WithTrashed() NullableLinkQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) OnlyTrashed() NullableLinkQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) WithoutTrashed() NullableLinkQuery {
	q.Query = q.Query.WithoutTrashed()
	return q
}

// Where derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) Where(predicates ...foundryquery.Predicate[NullableLink]) NullableLinkQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) WhereHas(relation foundryquery.ExistenceRelation[NullableLink]) NullableLinkQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[NullableLink]) NullableLinkQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) OrderBy(orders ...foundryquery.Order[NullableLink]) NullableLinkQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) Limit(count int) NullableLinkQuery {
	q.Query = q.Query.Limit(count)
	return q
}

// Offset derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) Offset(count int) NullableLinkQuery {
	q.Query = q.Query.Offset(count)
	return q
}

// With derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) With(relations ...foundryquery.Relation[NullableLink]) NullableLinkQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new NullableLink query without changing its source.
func (q NullableLinkQuery) WithRelationLimits(limits foundryquery.RelationLimits) NullableLinkQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q NullableLinkQuery) Find(ctx context.Context, executor database.Executor, key model.ID[NullableLink]) (foundryvalue.Optional[NullableLink], error) {
	return q.Where(NullableLinkFields().ID.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q NullableLinkQuery) RequireFind(ctx context.Context, executor database.Executor, key model.ID[NullableLink]) (NullableLink, error) {
	return q.Where(NullableLinkFields().ID.Eq(key)).RequireFirst(ctx, executor)
}

// NullableLinkLockedQuery preserves typed keys while requiring transaction-scoped reads.
type NullableLinkLockedQuery struct {
	foundryquery.LockedQuery[NullableLink]
}

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NullableLinkQuery) ForUpdate() NullableLinkLockedQuery {
	return NullableLinkLockedQuery{q.Query.ForUpdate()}
}

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NullableLinkQuery) ForNoKeyUpdate() NullableLinkLockedQuery {
	return NullableLinkLockedQuery{q.Query.ForNoKeyUpdate()}
}

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NullableLinkQuery) ForShare() NullableLinkLockedQuery {
	return NullableLinkLockedQuery{q.Query.ForShare()}
}

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NullableLinkQuery) ForKeyShare() NullableLinkLockedQuery {
	return NullableLinkLockedQuery{q.Query.ForKeyShare()}
}

// WithTrashed derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) WithTrashed() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) OnlyTrashed() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) WithoutTrashed() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// Where derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) Where(predicates ...foundryquery.Predicate[NullableLink]) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[NullableLink]) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[NullableLink]) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) OrderBy(orders ...foundryquery.Order[NullableLink]) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) Limit(count int) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) Offset(count int) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) With(relations ...foundryquery.Relation[NullableLink]) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) NoWait() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.NoWait()
	return q
}

// SkipLocked derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) SkipLocked() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked NullableLink query without changing its source.
func (q NullableLinkLockedQuery) Wait() NullableLinkLockedQuery {
	q.LockedQuery = q.LockedQuery.Wait()
	return q
}

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q NullableLinkLockedQuery) Find(ctx context.Context, tx *database.Tx, key model.ID[NullableLink]) (foundryvalue.Optional[NullableLink], error) {
	return q.Where(NullableLinkFields().ID.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q NullableLinkLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key model.ID[NullableLink]) (NullableLink, error) {
	return q.Where(NullableLinkFields().ID.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q NullableLinkQuery) Create(ctx context.Context, writer database.Transactor, draft NullableLinkDraft) (NullableLink, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return NullableLink{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q NullableLinkQuery) Upsert(ctx context.Context, writer database.Transactor, draft NullableLinkDraft, conflict foundryquery.Conflict[NullableLink]) (foundryvalue.Optional[NullableLink], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[NullableLink]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q NullableLinkQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []NullableLinkDraft) ([]NullableLink, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q NullableLinkQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []NullableLinkDraft, conflict foundryquery.Conflict[NullableLink]) ([]NullableLink, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q NullableLinkQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []NullableLinkDraft, conflict *foundryquery.Conflict[NullableLink]) ([]NullableLink, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q NullableLinkQuery) foundryCreateMutations(drafts []NullableLinkDraft) ([]foundryquery.Mutation[NullableLink], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[NullableLink], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q NullableLinkQuery) Update(ctx context.Context, writer database.Transactor, key model.ID[NullableLink], draft NullableLinkDraft) (NullableLink, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return NullableLink{}, err
	}
	return q.Where(NullableLinkFields().ID.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete removes one typed primary key within this query's filters and returns its complete pre-deletion model.
func (q NullableLinkQuery) Delete(ctx context.Context, writer database.Transactor, key model.ID[NullableLink]) (NullableLink, error) {
	return q.Where(NullableLinkFields().ID.Eq(key)).Query.Remove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q NullableLinkQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []NullableLinkDraft) ([]NullableLink, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q NullableLinkQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, NullableLink) (NullableLinkDraft, error)) ([]NullableLink, error) {
	var callback func(context.Context, *database.Tx, NullableLink) (foundryquery.Mutation[NullableLink], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current NullableLink) (foundryquery.Mutation[NullableLink], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q NullableLinkQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]NullableLink, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q NullableLinkQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create NullableLinkDraft) (NullableLink, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q NullableLinkQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create NullableLinkDraft, draft func(context.Context, *database.Tx, NullableLink) (NullableLinkDraft, error)) (NullableLink, error) {
	var callback func(context.Context, *database.Tx, NullableLink) (foundryquery.Mutation[NullableLink], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current NullableLink) (foundryquery.Mutation[NullableLink], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// NullableLinkInsertFromBuilder selects stored SQL values into NullableLink through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type NullableLinkInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, NullableLink]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p NullableLinkInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertNullableLinkFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertNullableLinkFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) NullableLinkInsertFromBuilder[FoundryScope] {
	return NullableLinkInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (NullableLink{}).FoundryQuery())}
}

// SelectID supplies the stored SQL value for id. It cannot also be supplied by Values.
func (p NullableLinkInsertFromBuilder[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, model.ID[NullableLink]]) NullableLinkInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NullableLinkFields().ID, v))
	return p
}

// SelectMemberAlias supplies the stored SQL value for member_alias. It cannot also be supplied by Values.
func (p NullableLinkInsertFromBuilder[FoundryScope]) SelectMemberAlias(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) NullableLinkInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NullableLinkFields().MemberAlias, v))
	return p
}

// SelectGroupName supplies the stored SQL value for group_name. It cannot also be supplied by Values.
func (p NullableLinkInsertFromBuilder[FoundryScope]) SelectGroupName(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) NullableLinkInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NullableLinkFields().GroupName, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p NullableLinkInsertFromBuilder[FoundryScope]) Values(draft NullableLinkDraft) NullableLinkInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p NullableLinkInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p NullableLinkInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]NullableLink, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// NullableLinkUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type NullableLinkUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, NullableLink]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdateNullableLinkFrom preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func UpdateNullableLinkFrom[FoundryScope any](destination NullableLinkQuery, source foundryquery.ProjectionSource[FoundryScope]) NullableLinkUpdateFromBuilder[FoundryScope] {
	return NullableLinkUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[NullableLink]]) NullableLinkUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(NullableLinkFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[NullableLink]]]) NullableLinkUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(NullableLinkFields().ID, v))
	return p
}

// SelectMemberAlias assigns a stored source value to member_alias; Values cannot also supply it.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) SelectMemberAlias(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) NullableLinkUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(NullableLinkFields().MemberAlias, v))
	return p
}

// SelectGroupName assigns a stored source value to group_name; Values cannot also supply it.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) SelectGroupName(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) NullableLinkUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(NullableLinkFields().GroupName, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) Values(draft NullableLinkDraft) NullableLinkUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p NullableLinkUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]NullableLink, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// NullableLinkDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type NullableLinkDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, NullableLink]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p NullableLinkDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeleteNullableLinkUsing preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func DeleteNullableLinkUsing[FoundryScope any](destination NullableLinkQuery, source foundryquery.ProjectionSource[FoundryScope]) NullableLinkDeleteUsingBuilder[FoundryScope] {
	return NullableLinkDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p NullableLinkDeleteUsingBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[NullableLink]]) NullableLinkDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(NullableLinkFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p NullableLinkDeleteUsingBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[NullableLink]]]) NullableLinkDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(NullableLinkFields().ID, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p NullableLinkDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p NullableLinkDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]NullableLink, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d NullableLinkDraft) FoundryCreateMutation(defaults foundryquery.Mutation[NullableLink]) (foundryquery.Mutation[NullableLink], error) {
	values, err := foundryquery.ReadCreateDefaults((NullableLink{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[NullableLink]{}, err
	}
	if !d.fieldID.IsSet() {
		v, err := foundryquery.MutationValue[NullableLink, model.ID[NullableLink]](values, "link_nullable", "id")
		if err != nil {
			return foundryquery.Mutation[NullableLink]{}, err
		}
		d.fieldID = v
	}
	if !d.fieldMemberAlias.IsSet() {
		v, err := foundryquery.MutationValue[NullableLink, foundryvalue.Nullable[string]](values, "link_nullable", "member_alias")
		if err != nil {
			return foundryquery.Mutation[NullableLink]{}, err
		}
		d.fieldMemberAlias = v
	}
	if !d.fieldGroupName.IsSet() {
		v, err := foundryquery.MutationValue[NullableLink, foundryvalue.Nullable[string]](values, "link_nullable", "group_name")
		if err != nil {
			return foundryquery.Mutation[NullableLink]{}, err
		}
		d.fieldGroupName = v
	}
	return d.foundryMutation(true)
}
func (d NullableLinkDraft) foundryMutation(create bool) (foundryquery.Mutation[NullableLink], error) {
	if create && !d.fieldID.IsSet() {
		id, err := model.NewID[NullableLink]()
		if err != nil {
			return foundryquery.Mutation[NullableLink]{}, err
		}
		d = d.SetID(id)
	}
	var assignments []foundryquery.Assignment[NullableLink]
	if v, set := d.fieldID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[NullableLink]("link_nullable", "id", codec.ID[NullableLink](), v))
	}
	if v, set := d.fieldMemberAlias.Get(); set {
		assignments = append(assignments, foundryquery.Assign[NullableLink]("link_nullable", "member_alias", codec.Nullable(codec.String[string]()), v))
	}
	if v, set := d.fieldGroupName.Get(); set {
		assignments = append(assignments, foundryquery.Assign[NullableLink]("link_nullable", "group_name", codec.Nullable(codec.String[string]()), v))
	}
	return foundryquery.Change(assignments...), nil
}

// NullableLinkDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type NullableLinkDraft struct {
	fieldID          foundryvalue.Optional[model.ID[NullableLink]]
	fieldMemberAlias foundryvalue.Optional[foundryvalue.Nullable[string]]
	fieldGroupName   foundryvalue.Optional[foundryvalue.Nullable[string]]
}

// ID returns the typed mutation state for id.
func (d NullableLinkDraft) ID() foundryvalue.Optional[model.ID[NullableLink]] { return d.fieldID }

// SetID returns a new draft with id explicitly set.
func (d NullableLinkDraft) SetID(v model.ID[NullableLink]) NullableLinkDraft {
	d.fieldID = foundryvalue.Set(v)
	return d
}

// UnsetID omits id without requesting a zero or null write.
func (d NullableLinkDraft) UnsetID() NullableLinkDraft {
	d.fieldID = foundryvalue.Optional[model.ID[NullableLink]]{}
	return d
}

// MemberAlias returns the typed mutation state for member_alias.
func (d NullableLinkDraft) MemberAlias() foundryvalue.Optional[foundryvalue.Nullable[string]] {
	return d.fieldMemberAlias
}

// SetMemberAlias returns a new draft with member_alias explicitly set.
func (d NullableLinkDraft) SetMemberAlias(v string) NullableLinkDraft {
	d.fieldMemberAlias = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetMemberAlias omits member_alias without requesting a zero or null write.
func (d NullableLinkDraft) UnsetMemberAlias() NullableLinkDraft {
	d.fieldMemberAlias = foundryvalue.Optional[foundryvalue.Nullable[string]]{}
	return d
}

// ClearMemberAlias explicitly sets member_alias to null.
func (d NullableLinkDraft) ClearMemberAlias() NullableLinkDraft {
	d.fieldMemberAlias = foundryvalue.Set(foundryvalue.Null[string]())
	return d
}

// GroupName returns the typed mutation state for group_name.
func (d NullableLinkDraft) GroupName() foundryvalue.Optional[foundryvalue.Nullable[string]] {
	return d.fieldGroupName
}

// SetGroupName returns a new draft with group_name explicitly set.
func (d NullableLinkDraft) SetGroupName(v string) NullableLinkDraft {
	d.fieldGroupName = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetGroupName omits group_name without requesting a zero or null write.
func (d NullableLinkDraft) UnsetGroupName() NullableLinkDraft {
	d.fieldGroupName = foundryvalue.Optional[foundryvalue.Nullable[string]]{}
	return d
}

// ClearGroupName explicitly sets group_name to null.
func (d NullableLinkDraft) ClearGroupName() NullableLinkDraft {
	d.fieldGroupName = foundryvalue.Set(foundryvalue.Null[string]())
	return d
}

// IsEmpty reports whether no fields have been selected for mutation.
func (d NullableLinkDraft) IsEmpty() bool {
	return !d.fieldID.IsSet() && !d.fieldMemberAlias.IsSet() && !d.fieldGroupName.IsSet()
}

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (NullableLinkDraft) Format(state fmt.State, _ rune) {
	_, _ = state.Write([]byte("NullableLink draft"))
}

// NullableLinkFieldChanges contains typed changes for persisted fields only.
type NullableLinkFieldChanges struct {
	// ID retains the typed change for id.
	ID lifecycle.FieldChange[model.ID[NullableLink]]
	// MemberAlias retains the typed change for member_alias.
	MemberAlias lifecycle.FieldChange[foundryvalue.Nullable[string]]
	// GroupName retains the typed change for group_name.
	GroupName lifecycle.FieldChange[foundryvalue.Nullable[string]]
}

// NullableLinkChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type NullableLinkChanges struct {
	before, after foundryvalue.Optional[NullableLink]
	fields        NullableLinkFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c NullableLinkChanges) Operation() foundryvalue.Optional[lifecycle.Operation] {
	return c.operation
}

// Before returns the persisted model before the operation, or absence for creation.
func (c NullableLinkChanges) Before() foundryvalue.Optional[NullableLink] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c NullableLinkChanges) After() foundryvalue.Optional[NullableLink] { return c.after }

// Fields returns model-specific field changes by value.
func (c NullableLinkChanges) Fields() NullableLinkFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c NullableLinkChanges) Assigned() bool {
	return c.fields.ID.Assigned() || c.fields.MemberAlias.Assigned() || c.fields.GroupName.Assigned()
}

// Changed reports whether any persisted field is changed.
func (c NullableLinkChanges) Changed() bool {
	return c.fields.ID.Changed() || c.fields.MemberAlias.Changed() || c.fields.GroupName.Changed()
}

// String and GoString keep model snapshots out of routine diagnostics.
func (NullableLinkChanges) String() string     { return "NullableLink changes" }
func (c NullableLinkChanges) GoString() string { return c.String() }

// CompareNullableLink is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func CompareNullableLink(before, after foundryvalue.Optional[NullableLink], assigned NullableLinkDraft) (NullableLinkChanges, error) {
	before = foundryNullableLinkSnapshot(before)
	after = foundryNullableLinkSnapshot(after)
	var changes NullableLinkChanges
	var err error
	changes.fields.ID, err = lifecycle.CompareModelField(codec.ID[NullableLink](), before, after, assigned.fieldID.IsSet(), func(item NullableLink) model.ID[NullableLink] { return item.ID })
	if err != nil {
		return NullableLinkChanges{}, fmt.Errorf("compare NullableLink.ID: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.ID.Changed() || changes.fields.ID.Assigned()) {
		return NullableLinkChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.MemberAlias, err = lifecycle.CompareModelField(codec.Nullable(codec.String[string]()), before, after, assigned.fieldMemberAlias.IsSet(), func(item NullableLink) foundryvalue.Nullable[string] { return item.MemberAlias })
	if err != nil {
		return NullableLinkChanges{}, fmt.Errorf("compare NullableLink.MemberAlias: %w", err)
	}
	changes.fields.GroupName, err = lifecycle.CompareModelField(codec.Nullable(codec.String[string]()), before, after, assigned.fieldGroupName.IsSet(), func(item NullableLink) foundryvalue.Nullable[string] { return item.GroupName })
	if err != nil {
		return NullableLinkChanges{}, fmt.Errorf("compare NullableLink.GroupName: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryNullableLinkSnapshot(snapshot foundryvalue.Optional[NullableLink]) foundryvalue.Optional[NullableLink] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[NullableLink]{}
	}
	return foundryvalue.Set(NullableLink{
		ID:          item.ID,
		MemberAlias: item.MemberAlias,
		GroupName:   item.GroupName,
	})
}

// NullableLinkHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type NullableLinkHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[NullableLink], *NullableLinkDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *NullableLinkDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, NullableLink, *NullableLinkDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, NullableLink) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, NullableLink) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, NullableLink) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, NullableLinkChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, NullableLinkChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, NullableLinkChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, NullableLinkChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, NullableLinkChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, NullableLinkChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, NullableLinkChanges) error
}

// NullableLinkObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type NullableLinkObserver = lifecycle.Observer[NullableLink, NullableLinkHooks]

// NewNullableLinkObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewNullableLinkObserver(observer string) NullableLinkObserver {
	return lifecycle.NewObserver[NullableLink, NullableLinkHooks](observer)
}

// RegisterNullableLinkObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterNullableLinkObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer NullableLinkObserver, construct func(foundation.Resolver) (func() NullableLinkHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (NullableLinkHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[NullableLink], error) {
	factories, err := lifecycle.ObserverFactories[NullableLink, NullableLinkHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[NullableLink]{}, err
	}
	var allHooks []NullableLinkHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[NullableLink]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[NullableLink]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[NullableLink]{}, err
	}
	return foundryquery.WriteHooks[NullableLink]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[NullableLink], mutation foundryquery.Mutation[NullableLink]) (foundryquery.Mutation[NullableLink], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			var draft NullableLinkDraft
			draft.fieldID, err = foundryquery.MutationValue[NullableLink, model.ID[NullableLink]](values, "link_nullable", "id")
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			draft.fieldMemberAlias, err = foundryquery.MutationValue[NullableLink, foundryvalue.Nullable[string]](values, "link_nullable", "member_alias")
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			draft.fieldGroupName, err = foundryquery.MutationValue[NullableLink, foundryvalue.Nullable[string]](values, "link_nullable", "group_name")
			if err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[NullableLink]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[NullableLink]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[NullableLink]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[NullableLink]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[NullableLink]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[NullableLink]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[NullableLink]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[NullableLink]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[NullableLink]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[NullableLink]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[NullableLink]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[NullableLink], mutation foundryquery.Mutation[NullableLink]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft NullableLinkDraft
			if values.Has("link_nullable", "id") {
				var zero model.ID[NullableLink]
				draft.fieldID = foundryvalue.Set(zero)
			}
			if values.Has("link_nullable", "member_alias") {
				var zero foundryvalue.Nullable[string]
				draft.fieldMemberAlias = foundryvalue.Set(zero)
			}
			if values.Has("link_nullable", "group_name") {
				var zero foundryvalue.Nullable[string]
				draft.fieldGroupName = foundryvalue.Set(zero)
			}
			changes, err := CompareNullableLink(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// NullableLinkRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type NullableLinkRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, NullableLink) error
}

// NullableLinkRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type NullableLinkRetrievalObserver = lifecycle.Observer[NullableLink, NullableLinkRetrievalHooks]

// NewNullableLinkRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewNullableLinkRetrievalObserver(observer string) NullableLinkRetrievalObserver {
	return lifecycle.NewRetrievalObserver[NullableLink, NullableLinkRetrievalHooks](observer)
}

// RegisterNullableLinkRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterNullableLinkRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer NullableLinkRetrievalObserver, construct func(foundation.Resolver) (func() NullableLinkRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (NullableLinkRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[NullableLink], error) {
	factories, err := lifecycle.RetrievalObserverFactories[NullableLink, NullableLinkRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[NullableLink]{}, err
	}
	var allHooks []NullableLinkRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[NullableLink]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[NullableLink]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[NullableLink]{}, err
	}
	return foundryquery.RetrievalHooks[NullableLink]{Retrieved: func(ctx context.Context, executor database.Executor, item NullableLink) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// NullableLinkAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type NullableLinkAuditPolicy struct {
	_ [0]*NullableLink
	// ID controls the audit representation of stored link_nullable.id.
	ID record.Disclosure
	// MemberAlias controls the audit representation of stored link_nullable.member_alias.
	MemberAlias record.Disclosure
	// GroupName controls the audit representation of stored link_nullable.group_name.
	GroupName record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes NullableLinkChanges) Audit(policy NullableLinkAuditPolicy) (record.Model[NullableLink, model.ID[NullableLink]], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "id", policy.ID)
	if err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	var captured record.Field[NullableLink]
	captured, err = record.CaptureField[NullableLink]("id", codec.ID[NullableLink](), changes.fields.ID, policy.ID)
	if err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	captured, err = record.CaptureField[NullableLink]("member_alias", codec.Nullable(codec.String[string]()), changes.fields.MemberAlias, policy.MemberAlias)
	if err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	captured, err = record.CaptureField[NullableLink]("group_name", codec.Nullable(codec.String[string]()), changes.fields.GroupName, policy.GroupName)
	if err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[NullableLink, model.ID[NullableLink]]{}, err
	}
	return builder.Build()
}

// NullableLinkAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type NullableLinkAuditFieldSet struct {
	_ [0]*NullableLink
	// ID retains stored link_nullable.id after write mutators; read accessors do not replace audit values.
	ID foundryvalue.Optional[record.FieldChange[model.ID[NullableLink]]]
	// MemberAlias retains stored link_nullable.member_alias after write mutators; read accessors do not replace audit values.
	MemberAlias foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[string]]]
	// GroupName retains stored link_nullable.group_name after write mutators; read accessors do not replace audit values.
	GroupName foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[string]]]
}

// NullableLinkAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func NullableLinkAuditFields(history record.Model[NullableLink, model.ID[NullableLink]]) (NullableLinkAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return NullableLinkAuditFieldSet{}, err
	}
	var fields NullableLinkAuditFieldSet
	fields.ID, err = record.ReadField(view, "id", codec.ID[NullableLink]())
	if err != nil {
		return NullableLinkAuditFieldSet{}, err
	}
	fields.MemberAlias, err = record.ReadField(view, "member_alias", codec.Nullable(codec.String[string]()))
	if err != nil {
		return NullableLinkAuditFieldSet{}, err
	}
	fields.GroupName, err = record.ReadField(view, "group_name", codec.Nullable(codec.String[string]()))
	if err != nil {
		return NullableLinkAuditFieldSet{}, err
	}
	return fields, nil
}

// NullableLinkAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func NullableLinkAuditing(policy NullableLinkAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[NullableLink]()
		if err != nil {
			return err
		}
		return RegisterNullableLinkObserver(registrar, pool, NewNullableLinkObserver(name), func(resolver foundation.Resolver) (func() NullableLinkHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() NullableLinkHooks {
				write := func(ctx context.Context, tx *database.Tx, changes NullableLinkChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return NullableLinkHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
