// Code generated by foundry generate; DO NOT EDIT.
// Source: node.go.

package recursivequeries

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
)

// NodeFieldSet exposes fields owned by the unaliased model.
type NodeFieldSet = NodeScopedFieldSet[Node]

var foundryNodeFields foundryquery.Memo[NodeFieldSet]

// NodeFields returns immutable field descriptors, built once per process.
func NodeFields() NodeFieldSet {
	return foundryNodeFields.Get(func() NodeFieldSet { return NodeFieldsAt(foundryquery.DeclareModelScope[Node]("nodes")) })
}

// NodeScopedFieldSet preserves typed field operators in a declared query scope.
type NodeScopedFieldSet[FoundryScope any] struct {
	// Code describes nodes.code.
	Code foundryquery.TextField[FoundryScope, NodeCode]
	// Parent describes nodes.parent_code.
	Parent foundryquery.NullableTextField[FoundryScope, NodeCode]
	// Name describes nodes.name.
	Name foundryquery.TextField[FoundryScope, string]
}

// NodeFieldsAt binds these record fields to an alias or joined scope.
func NodeFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, Node]) NodeScopedFieldSet[FoundryScope] {
	return NodeScopedFieldSet[FoundryScope]{
		Code:   foundryquery.NewTextField[FoundryScope, NodeCode](scope.Table(), "code", codec.String[NodeCode]()),
		Parent: foundryquery.NewNullableTextField[FoundryScope, NodeCode](scope.Table(), "parent_code", codec.String[NodeCode]()),
		Name:   foundryquery.NewTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
	}
}

// NodeNullableFieldSet preserves typed field operators in a declared query scope.
type NodeNullableFieldSet[FoundryScope any] struct {
	// Code describes nodes.code.
	Code foundryquery.NullableTextField[FoundryScope, NodeCode]
	// Parent describes nodes.parent_code.
	Parent foundryquery.NullableTextField[FoundryScope, NodeCode]
	// Name describes nodes.name.
	Name foundryquery.NullableTextField[FoundryScope, string]
}

// NodeNullableFieldsAt binds these record fields to an alias or joined scope.
func NodeNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, Node]) NodeNullableFieldSet[FoundryScope] {
	return NodeNullableFieldSet[FoundryScope]{
		Code:   foundryquery.NewNullableTextField[FoundryScope, NodeCode](scope.Table(), "code", codec.String[NodeCode]()),
		Parent: foundryquery.NewNullableTextField[FoundryScope, NodeCode](scope.Table(), "parent_code", codec.String[NodeCode]()),
		Name:   foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "name", codec.String[string]()),
	}
}

// NodeQuery preserves model-specific keys through fluent query derivation.
type NodeQuery struct{ foundryquery.Query[Node] }

// foundryNodeModelQuery holds the immutable declaration, hydration codecs and field metadata, built once on first use.
var foundryNodeModelQuery foundryquery.Memo[foundryquery.Query[Node]]

func foundryNodeBuildQuery() foundryquery.Query[Node] {
	foundryCodec0 := codec.String[NodeCode]()
	foundryCodec1 := codec.Nullable(codec.String[NodeCode]())
	foundryCodec2 := codec.String[string]()
	return foundryquery.ForModel(foundryquery.Define[Node]("nodes", "code", []foundryquery.Column{foundryquery.Column{Name: "code", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "parent_code", Nullable: true, DatabaseDefault: false}, foundryquery.Column{Name: "name", Nullable: false, DatabaseDefault: false}}, func(row database.Row) (Node, error) {
		var item Node
		if err := row.Scan(
			foundryCodec0.Scan(&item.Code),
			foundryCodec1.Scan(&item.Parent),
			foundryCodec2.Scan(&item.Name),
		); err != nil {
			return Node{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("code", foundryCodec0, func(item Node) NodeCode { return item.Code }),
		foundryquery.NewModelField("parent_code", foundryCodec1, func(item Node) foundryvalue.Nullable[NodeCode] { return item.Parent }),
		foundryquery.NewModelField("name", foundryCodec2, func(item Node) string { return item.Name }),
	).WithObserverHooks((NodeHooks{}).foundryWriteHooks, false).WithRetrievalHooks((NodeRetrievalHooks{}).foundryRetrievalHooks, false))
}

// QueryNodes starts a complete-model query for nodes with generated hydration.
func QueryNodes() NodeQuery { return NodeQuery{foundryNodeModelQuery.Get(foundryNodeBuildQuery)} }

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (Node) FoundryQuery() foundryquery.Query[Node] { return QueryNodes().Query }

// FoundryReference retains Node and its concrete stored primary key for framework integrations.
// It reads Code directly, never calls an accessor, and performs no database lookup.
func (m Node) FoundryReference() model.Reference[Node, NodeCode] {
	return model.NewReference[Node]("nodes", m.Code, codec.String[NodeCode]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m Node) FoundryIdentity() (model.Identity, error) { return m.FoundryReference().Identity() }

// WithTrashed derives a new Node query without changing its source.
func (q NodeQuery) WithTrashed() NodeQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new Node query without changing its source.
func (q NodeQuery) OnlyTrashed() NodeQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new Node query without changing its source.
func (q NodeQuery) WithoutTrashed() NodeQuery { q.Query = q.Query.WithoutTrashed(); return q }

// WithoutGlobalScope derives a new Node query without changing its source.
func (q NodeQuery) WithoutGlobalScope(scopes ...foundryquery.GlobalScope[Node]) NodeQuery {
	q.Query = q.Query.WithoutGlobalScope(scopes...)
	return q
}

// WithoutGlobalScopes derives a new Node query without changing its source.
func (q NodeQuery) WithoutGlobalScopes() NodeQuery { q.Query = q.Query.WithoutGlobalScopes(); return q }

// WithScopeContext derives a new Node query without changing its source.
func (q NodeQuery) WithScopeContext(ctx context.Context) NodeQuery {
	q.Query = q.Query.WithScopeContext(ctx)
	return q
}

// Where derives a new Node query without changing its source.
func (q NodeQuery) Where(predicates ...foundryquery.Predicate[Node]) NodeQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new Node query without changing its source.
func (q NodeQuery) WhereHas(relation foundryquery.ExistenceRelation[Node]) NodeQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new Node query without changing its source.
func (q NodeQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Node]) NodeQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new Node query without changing its source.
func (q NodeQuery) OrderBy(orders ...foundryquery.Order[Node]) NodeQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new Node query without changing its source.
func (q NodeQuery) Limit(count int) NodeQuery { q.Query = q.Query.Limit(count); return q }

// Offset derives a new Node query without changing its source.
func (q NodeQuery) Offset(count int) NodeQuery { q.Query = q.Query.Offset(count); return q }

// With derives a new Node query without changing its source.
func (q NodeQuery) With(relations ...foundryquery.Relation[Node]) NodeQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new Node query without changing its source.
func (q NodeQuery) WithRelationLimits(limits foundryquery.RelationLimits) NodeQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q NodeQuery) Find(ctx context.Context, executor database.Executor, key NodeCode) (foundryvalue.Optional[Node], error) {
	return q.Where(NodeFields().Code.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q NodeQuery) RequireFind(ctx context.Context, executor database.Executor, key NodeCode) (Node, error) {
	return q.Where(NodeFields().Code.Eq(key)).RequireFirst(ctx, executor)
}

// NodeLockedQuery preserves typed keys while requiring transaction-scoped reads.
type NodeLockedQuery struct{ foundryquery.LockedQuery[Node] }

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NodeQuery) ForUpdate() NodeLockedQuery { return NodeLockedQuery{q.Query.ForUpdate()} }

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NodeQuery) ForNoKeyUpdate() NodeLockedQuery { return NodeLockedQuery{q.Query.ForNoKeyUpdate()} }

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NodeQuery) ForShare() NodeLockedQuery { return NodeLockedQuery{q.Query.ForShare()} }

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q NodeQuery) ForKeyShare() NodeLockedQuery { return NodeLockedQuery{q.Query.ForKeyShare()} }

// WithTrashed derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithTrashed() NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked Node query without changing its source.
func (q NodeLockedQuery) OnlyTrashed() NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithoutTrashed() NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// WithoutGlobalScope derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithoutGlobalScope(scopes ...foundryquery.GlobalScope[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutGlobalScope(scopes...)
	return q
}

// WithoutGlobalScopes derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithoutGlobalScopes() NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutGlobalScopes()
	return q
}

// WithScopeContext derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithScopeContext(ctx context.Context) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithScopeContext(ctx)
	return q
}

// Where derives a locked Node query without changing its source.
func (q NodeLockedQuery) Where(predicates ...foundryquery.Predicate[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked Node query without changing its source.
func (q NodeLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked Node query without changing its source.
func (q NodeLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked Node query without changing its source.
func (q NodeLockedQuery) OrderBy(orders ...foundryquery.Order[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked Node query without changing its source.
func (q NodeLockedQuery) Limit(count int) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked Node query without changing its source.
func (q NodeLockedQuery) Offset(count int) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked Node query without changing its source.
func (q NodeLockedQuery) With(relations ...foundryquery.Relation[Node]) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked Node query without changing its source.
func (q NodeLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked Node query without changing its source.
func (q NodeLockedQuery) NoWait() NodeLockedQuery { q.LockedQuery = q.LockedQuery.NoWait(); return q }

// SkipLocked derives a locked Node query without changing its source.
func (q NodeLockedQuery) SkipLocked() NodeLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked Node query without changing its source.
func (q NodeLockedQuery) Wait() NodeLockedQuery { q.LockedQuery = q.LockedQuery.Wait(); return q }

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q NodeLockedQuery) Find(ctx context.Context, tx *database.Tx, key NodeCode) (foundryvalue.Optional[Node], error) {
	return q.Where(NodeFields().Code.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q NodeLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key NodeCode) (Node, error) {
	return q.Where(NodeFields().Code.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q NodeQuery) Create(ctx context.Context, writer database.Transactor, draft NodeDraft) (Node, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return Node{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q NodeQuery) Upsert(ctx context.Context, writer database.Transactor, draft NodeDraft, conflict foundryquery.Conflict[Node]) (foundryvalue.Optional[Node], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[Node]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q NodeQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []NodeDraft) ([]Node, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q NodeQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []NodeDraft, conflict foundryquery.Conflict[Node]) ([]Node, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q NodeQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []NodeDraft, conflict *foundryquery.Conflict[Node]) ([]Node, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q NodeQuery) foundryCreateMutations(drafts []NodeDraft) ([]foundryquery.Mutation[Node], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[Node], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q NodeQuery) Update(ctx context.Context, writer database.Transactor, key NodeCode, draft NodeDraft) (Node, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return Node{}, err
	}
	return q.Where(NodeFields().Code.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete removes one typed primary key within this query's filters and returns its complete pre-deletion model.
func (q NodeQuery) Delete(ctx context.Context, writer database.Transactor, key NodeCode) (Node, error) {
	return q.Where(NodeFields().Code.Eq(key)).Query.Remove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q NodeQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []NodeDraft) ([]Node, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q NodeQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, Node) (NodeDraft, error)) ([]Node, error) {
	var callback func(context.Context, *database.Tx, Node) (foundryquery.Mutation[Node], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Node) (foundryquery.Mutation[Node], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q NodeQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Node, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; omitted fields default from the query's top-level equality filters and global scopes, and the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q NodeQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create NodeDraft) (Node, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// CreateOrFirst creates a model through its normal lifecycle and, when a unique constraint rejects it, returns the first primary-ordered model matching the query instead. The insert runs in its own savepoint, so a concurrent creation of the same unique key is resolved under READ COMMITTED rather than reported. The query must select the row holding the conflicting key; a created model must satisfy it.
func (q NodeQuery) CreateOrFirst(ctx context.Context, writer database.Transactor, create NodeDraft) (Node, error) {
	return q.Query.InsertOrFirst(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q NodeQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create NodeDraft, draft func(context.Context, *database.Tx, Node) (NodeDraft, error)) (Node, error) {
	var callback func(context.Context, *database.Tx, Node) (foundryquery.Mutation[Node], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Node) (foundryquery.Mutation[Node], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// NodeInsertFromBuilder selects stored SQL values into Node through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type NodeInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, Node]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p NodeInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertNodeFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertNodeFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) NodeInsertFromBuilder[FoundryScope] {
	return NodeInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (Node{}).FoundryQuery())}
}

// SelectCode supplies the stored SQL value for code. It cannot also be supplied by Values.
func (p NodeInsertFromBuilder[FoundryScope]) SelectCode(v foundryquery.Expression[FoundryScope, NodeCode]) NodeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NodeFields().Code, v))
	return p
}

// SelectParent supplies the stored SQL value for parent_code. It cannot also be supplied by Values.
func (p NodeInsertFromBuilder[FoundryScope]) SelectParent(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[NodeCode]]) NodeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NodeFields().Parent, v))
	return p
}

// SelectName supplies the stored SQL value for name. It cannot also be supplied by Values.
func (p NodeInsertFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) NodeInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(NodeFields().Name, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p NodeInsertFromBuilder[FoundryScope]) Values(draft NodeDraft) NodeInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p NodeInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p NodeInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Node, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// NodeUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type NodeUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, Node]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p NodeUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdateNodeFrom preserves destination filters and the source's explicitly selected window.
// Call MatchCode to connect the source identity to this model's primary key.
func UpdateNodeFrom[FoundryScope any](destination NodeQuery, source foundryquery.ProjectionSource[FoundryScope]) NodeUpdateFromBuilder[FoundryScope] {
	return NodeUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchCode replaces the stored source value matched to code; it never assigns the key.
func (p NodeUpdateFromBuilder[FoundryScope]) MatchCode(v foundryquery.Expression[FoundryScope, NodeCode]) NodeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(NodeFields().Code, v))
	return p
}

// MatchNullableCode accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p NodeUpdateFromBuilder[FoundryScope]) MatchNullableCode(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[NodeCode]]) NodeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(NodeFields().Code, v))
	return p
}

// SelectParent assigns a stored source value to parent_code; Values cannot also supply it.
func (p NodeUpdateFromBuilder[FoundryScope]) SelectParent(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[NodeCode]]) NodeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(NodeFields().Parent, v))
	return p
}

// SelectName assigns a stored source value to name; Values cannot also supply it.
func (p NodeUpdateFromBuilder[FoundryScope]) SelectName(v foundryquery.Expression[FoundryScope, string]) NodeUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(NodeFields().Name, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p NodeUpdateFromBuilder[FoundryScope]) Values(draft NodeDraft) NodeUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p NodeUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p NodeUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Node, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// NodeDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type NodeDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, Node]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p NodeDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeleteNodeUsing preserves destination filters and the source's explicitly selected window.
// Call MatchCode to connect the source identity to this model's primary key.
func DeleteNodeUsing[FoundryScope any](destination NodeQuery, source foundryquery.ProjectionSource[FoundryScope]) NodeDeleteUsingBuilder[FoundryScope] {
	return NodeDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// MatchCode replaces the stored source value matched to code; it never assigns the key.
func (p NodeDeleteUsingBuilder[FoundryScope]) MatchCode(v foundryquery.Expression[FoundryScope, NodeCode]) NodeDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(NodeFields().Code, v))
	return p
}

// MatchNullableCode accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p NodeDeleteUsingBuilder[FoundryScope]) MatchNullableCode(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[NodeCode]]) NodeDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(NodeFields().Code, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p NodeDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p NodeDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Node, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// WithoutModelHooks acknowledges that set-based writes on this query skip per-model hooks and observers; per-model writes on it are rejected.
func (q NodeQuery) WithoutModelHooks() NodeQuery { q.Query = q.Query.WithoutModelHooks(); return q }

// UpdateAll assigns the draft to every model matching this query (filters, global scopes and soft-delete visibility) in one UPDATE and returns the affected count. Managed update timestamps and field mutators apply once; per-model hooks, observers and change capture do not run.
func (q NodeQuery) UpdateAll(ctx context.Context, writer database.Transactor, draft NodeDraft) (int64, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return 0, err
	}
	return q.Query.PatchAll(ctx, writer, mutation)
}

// DeleteAll physically deletes every model matching this query in one statement and returns the affected count. Per-model hooks do not run.
func (q NodeQuery) DeleteAll(ctx context.Context, writer database.Transactor) (int64, error) {
	return q.Query.RemoveAll(ctx, writer)
}

// Increment adjusts one numeric field of every matching model by a typed delta, such as NodeFields().Field.By(1), with an optional extra draft, in one UPDATE. SQL NULL stays NULL. Per-model hooks do not run.
func (q NodeQuery) Increment(ctx context.Context, writer database.Transactor, adjustment foundryquery.Adjustment[Node], extra ...NodeDraft) (int64, error) {
	if len(extra) > 1 {
		return 0, foundryfault.New(foundryfault.Invalid, "numeric adjustment accepts at most one extra draft")
	}
	var mutation foundryquery.Mutation[Node]
	if len(extra) == 1 {
		var err error
		if mutation, err = extra[0].foundryMutation(false); err != nil {
			return 0, err
		}
	}
	return q.Query.AdjustAll(ctx, writer, adjustment, false, mutation)
}

// Decrement adjusts one numeric field of every matching model by a typed delta, such as NodeFields().Field.By(1), with an optional extra draft, in one UPDATE. SQL NULL stays NULL. Per-model hooks do not run.
func (q NodeQuery) Decrement(ctx context.Context, writer database.Transactor, adjustment foundryquery.Adjustment[Node], extra ...NodeDraft) (int64, error) {
	if len(extra) > 1 {
		return 0, foundryfault.New(foundryfault.Invalid, "numeric adjustment accepts at most one extra draft")
	}
	var mutation foundryquery.Mutation[Node]
	if len(extra) == 1 {
		var err error
		if mutation, err = extra[0].foundryMutation(false); err != nil {
			return 0, err
		}
	}
	return q.Query.AdjustAll(ctx, writer, adjustment, true, mutation)
}

// FoundryUpdateMutation supplies the typed update-draft adapter for framework integrations such as pivot updates. Omitted fields stay unchanged; no mutators or database calls run here.
func (d NodeDraft) FoundryUpdateMutation() (foundryquery.Mutation[Node], error) {
	return d.foundryMutation(false)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d NodeDraft) FoundryCreateMutation(defaults foundryquery.Mutation[Node]) (foundryquery.Mutation[Node], error) {
	values, err := foundryquery.ReadCreateDefaults((Node{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[Node]{}, err
	}
	if !d.fieldCode.IsSet() {
		v, err := foundryquery.MutationValue[Node, NodeCode](values, "nodes", "code")
		if err != nil {
			return foundryquery.Mutation[Node]{}, err
		}
		d.fieldCode = v
	}
	if !d.fieldParent.IsSet() {
		v, err := foundryquery.MutationValue[Node, foundryvalue.Nullable[NodeCode]](values, "nodes", "parent_code")
		if err != nil {
			return foundryquery.Mutation[Node]{}, err
		}
		d.fieldParent = v
	}
	if !d.fieldName.IsSet() {
		v, err := foundryquery.MutationValue[Node, string](values, "nodes", "name")
		if err != nil {
			return foundryquery.Mutation[Node]{}, err
		}
		d.fieldName = v
	}
	return d.foundryMutation(true)
}
func (d NodeDraft) foundryMutation(create bool) (foundryquery.Mutation[Node], error) {
	var assignments []foundryquery.Assignment[Node]
	if v, set := d.fieldCode.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Node]("nodes", "code", codec.String[NodeCode](), v))
	}
	if v, set := d.fieldParent.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Node]("nodes", "parent_code", codec.Nullable(codec.String[NodeCode]()), v))
	}
	if v, set := d.fieldName.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Node]("nodes", "name", codec.String[string](), v))
	}
	return foundryquery.Change(assignments...), nil
}

// NodeDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type NodeDraft struct {
	fieldCode   foundryvalue.Optional[NodeCode]
	fieldParent foundryvalue.Optional[foundryvalue.Nullable[NodeCode]]
	fieldName   foundryvalue.Optional[string]
}

// Code returns the typed mutation state for code.
func (d NodeDraft) Code() foundryvalue.Optional[NodeCode] { return d.fieldCode }

// SetCode returns a new draft with code explicitly set.
func (d NodeDraft) SetCode(v NodeCode) NodeDraft { d.fieldCode = foundryvalue.Set(v); return d }

// UnsetCode omits code without requesting a zero or null write.
func (d NodeDraft) UnsetCode() NodeDraft { d.fieldCode = foundryvalue.Optional[NodeCode]{}; return d }

// Parent returns the typed mutation state for parent_code.
func (d NodeDraft) Parent() foundryvalue.Optional[foundryvalue.Nullable[NodeCode]] {
	return d.fieldParent
}

// SetParent returns a new draft with parent_code explicitly set.
func (d NodeDraft) SetParent(v NodeCode) NodeDraft {
	d.fieldParent = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetParent omits parent_code without requesting a zero or null write.
func (d NodeDraft) UnsetParent() NodeDraft {
	d.fieldParent = foundryvalue.Optional[foundryvalue.Nullable[NodeCode]]{}
	return d
}

// ClearParent explicitly sets parent_code to null.
func (d NodeDraft) ClearParent() NodeDraft {
	d.fieldParent = foundryvalue.Set(foundryvalue.Null[NodeCode]())
	return d
}

// Name returns the typed mutation state for name.
func (d NodeDraft) Name() foundryvalue.Optional[string] { return d.fieldName }

// SetName returns a new draft with name explicitly set.
func (d NodeDraft) SetName(v string) NodeDraft { d.fieldName = foundryvalue.Set(v); return d }

// UnsetName omits name without requesting a zero or null write.
func (d NodeDraft) UnsetName() NodeDraft { d.fieldName = foundryvalue.Optional[string]{}; return d }

// IsEmpty reports whether no fields have been selected for mutation.
func (d NodeDraft) IsEmpty() bool {
	return !d.fieldCode.IsSet() && !d.fieldParent.IsSet() && !d.fieldName.IsSet()
}

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (NodeDraft) Format(state fmt.State, _ rune) { _, _ = state.Write([]byte("Node draft")) }

// NodeFieldChanges contains typed changes for persisted fields only.
type NodeFieldChanges struct {
	// Code retains the typed change for code.
	Code lifecycle.FieldChange[NodeCode]
	// Parent retains the typed change for parent_code.
	Parent lifecycle.FieldChange[foundryvalue.Nullable[NodeCode]]
	// Name retains the typed change for name.
	Name lifecycle.FieldChange[string]
}

// NodeChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type NodeChanges struct {
	before, after foundryvalue.Optional[Node]
	fields        NodeFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c NodeChanges) Operation() foundryvalue.Optional[lifecycle.Operation] { return c.operation }

// Before returns the persisted model before the operation, or absence for creation.
func (c NodeChanges) Before() foundryvalue.Optional[Node] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c NodeChanges) After() foundryvalue.Optional[Node] { return c.after }

// Fields returns model-specific field changes by value.
func (c NodeChanges) Fields() NodeFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c NodeChanges) Assigned() bool {
	return c.fields.Code.Assigned() || c.fields.Parent.Assigned() || c.fields.Name.Assigned()
}

// Changed reports whether any persisted field is changed.
func (c NodeChanges) Changed() bool {
	return c.fields.Code.Changed() || c.fields.Parent.Changed() || c.fields.Name.Changed()
}

// String and GoString keep model snapshots out of routine diagnostics.
func (NodeChanges) String() string     { return "Node changes" }
func (c NodeChanges) GoString() string { return c.String() }

// CompareNode is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func CompareNode(before, after foundryvalue.Optional[Node], assigned NodeDraft) (NodeChanges, error) {
	before = foundryNodeSnapshot(before)
	after = foundryNodeSnapshot(after)
	var changes NodeChanges
	var err error
	changes.fields.Code, err = lifecycle.CompareModelField(codec.String[NodeCode](), before, after, assigned.fieldCode.IsSet(), func(item Node) NodeCode { return item.Code })
	if err != nil {
		return NodeChanges{}, fmt.Errorf("compare Node.Code: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.Code.Changed() || changes.fields.Code.Assigned()) {
		return NodeChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.Parent, err = lifecycle.CompareModelField(codec.Nullable(codec.String[NodeCode]()), before, after, assigned.fieldParent.IsSet(), func(item Node) foundryvalue.Nullable[NodeCode] { return item.Parent })
	if err != nil {
		return NodeChanges{}, fmt.Errorf("compare Node.Parent: %w", err)
	}
	changes.fields.Name, err = lifecycle.CompareModelField(codec.String[string](), before, after, assigned.fieldName.IsSet(), func(item Node) string { return item.Name })
	if err != nil {
		return NodeChanges{}, fmt.Errorf("compare Node.Name: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryNodeSnapshot(snapshot foundryvalue.Optional[Node]) foundryvalue.Optional[Node] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[Node]{}
	}
	return foundryvalue.Set(Node{
		Code:   item.Code,
		Parent: item.Parent,
		Name:   item.Name,
	})
}

// NodeHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type NodeHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[Node], *NodeDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *NodeDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, Node, *NodeDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, Node) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, Node) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, Node) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, NodeChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, NodeChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, NodeChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, NodeChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, NodeChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, NodeChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, NodeChanges) error
}

// NodeObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type NodeObserver = lifecycle.Observer[Node, NodeHooks]

// NewNodeObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewNodeObserver(observer string) NodeObserver {
	return lifecycle.NewObserver[Node, NodeHooks](observer)
}

// RegisterNodeObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterNodeObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer NodeObserver, construct func(foundation.Resolver) (func() NodeHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (NodeHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[Node], error) {
	factories, err := lifecycle.ObserverFactories[Node, NodeHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[Node]{}, err
	}
	var allHooks []NodeHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Node]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[Node]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Node]{}, err
	}
	return foundryquery.WriteHooks[Node]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[Node], mutation foundryquery.Mutation[Node]) (foundryquery.Mutation[Node], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			var draft NodeDraft
			draft.fieldCode, err = foundryquery.MutationValue[Node, NodeCode](values, "nodes", "code")
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			draft.fieldParent, err = foundryquery.MutationValue[Node, foundryvalue.Nullable[NodeCode]](values, "nodes", "parent_code")
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			draft.fieldName, err = foundryquery.MutationValue[Node, string](values, "nodes", "name")
			if err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[Node]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Node]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Node]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[Node]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[Node]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Node]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Node]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Node]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Node]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Node]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[Node]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[Node], mutation foundryquery.Mutation[Node]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft NodeDraft
			if values.Has("nodes", "code") {
				var zero NodeCode
				draft.fieldCode = foundryvalue.Set(zero)
			}
			if values.Has("nodes", "parent_code") {
				var zero foundryvalue.Nullable[NodeCode]
				draft.fieldParent = foundryvalue.Set(zero)
			}
			if values.Has("nodes", "name") {
				var zero string
				draft.fieldName = foundryvalue.Set(zero)
			}
			changes, err := CompareNode(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// NodeRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type NodeRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, Node) error
}

// NodeRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type NodeRetrievalObserver = lifecycle.Observer[Node, NodeRetrievalHooks]

// NewNodeRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewNodeRetrievalObserver(observer string) NodeRetrievalObserver {
	return lifecycle.NewRetrievalObserver[Node, NodeRetrievalHooks](observer)
}

// RegisterNodeRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterNodeRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer NodeRetrievalObserver, construct func(foundation.Resolver) (func() NodeRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (NodeRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[Node], error) {
	factories, err := lifecycle.RetrievalObserverFactories[Node, NodeRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[Node]{}, err
	}
	var allHooks []NodeRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Node]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[Node]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Node]{}, err
	}
	return foundryquery.RetrievalHooks[Node]{Retrieved: func(ctx context.Context, executor database.Executor, item Node) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// NodeAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type NodeAuditPolicy struct {
	_ [0]*Node
	// Code controls the audit representation of stored nodes.code.
	Code record.Disclosure
	// Parent controls the audit representation of stored nodes.parent_code.
	Parent record.Disclosure
	// Name controls the audit representation of stored nodes.name.
	Name record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Updates, soft deletes and restorations record assigned or changed fields plus the key; create and delete record every field.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes NodeChanges) Audit(policy NodeAuditPolicy) (record.Model[Node, NodeCode], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[Node, NodeCode]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[Node, NodeCode]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "code", policy.Code)
	if err != nil {
		return record.Model[Node, NodeCode]{}, err
	}
	if err = record.Capture(builder, "code", codec.String[NodeCode](), changes.fields.Code, policy.Code); err != nil {
		return record.Model[Node, NodeCode]{}, err
	}
	if err = record.Capture(builder, "parent_code", codec.Nullable(codec.String[NodeCode]()), changes.fields.Parent, policy.Parent); err != nil {
		return record.Model[Node, NodeCode]{}, err
	}
	if err = record.Capture(builder, "name", codec.String[string](), changes.fields.Name, policy.Name); err != nil {
		return record.Model[Node, NodeCode]{}, err
	}
	return builder.Build()
}

// NodeAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type NodeAuditFieldSet struct {
	_ [0]*Node
	// Code retains stored nodes.code after write mutators; read accessors do not replace audit values.
	Code foundryvalue.Optional[record.FieldChange[NodeCode]]
	// Parent retains stored nodes.parent_code after write mutators; read accessors do not replace audit values.
	Parent foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[NodeCode]]]
	// Name retains stored nodes.name after write mutators; read accessors do not replace audit values.
	Name foundryvalue.Optional[record.FieldChange[string]]
}

// NodeAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func NodeAuditFields(history record.Model[Node, NodeCode]) (NodeAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return NodeAuditFieldSet{}, err
	}
	var fields NodeAuditFieldSet
	fields.Code, err = record.ReadField(view, "code", codec.String[NodeCode]())
	if err != nil {
		return NodeAuditFieldSet{}, err
	}
	fields.Parent, err = record.ReadField(view, "parent_code", codec.Nullable(codec.String[NodeCode]()))
	if err != nil {
		return NodeAuditFieldSet{}, err
	}
	fields.Name, err = record.ReadField(view, "name", codec.String[string]())
	if err != nil {
		return NodeAuditFieldSet{}, err
	}
	return fields, nil
}

// NodeAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func NodeAuditing(policy NodeAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[Node]()
		if err != nil {
			return err
		}
		return RegisterNodeObserver(registrar, pool, NewNodeObserver(name), func(resolver foundation.Resolver) (func() NodeHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() NodeHooks {
				write := func(ctx context.Context, tx *database.Tx, changes NodeChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return NodeHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
