package upsertqueries_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"foundry.test/consumer/internal/queryfixture"
	"foundry.test/consumer/models"
	"foundry.test/consumer/upsertqueries"
	"github.com/weiloon1234/Foundry-Go/database"
	"github.com/weiloon1234/Foundry-Go/database/query"
	"github.com/weiloon1234/Foundry-Go/decimal"
	"github.com/weiloon1234/Foundry-Go/fault"
	"github.com/weiloon1234/Foundry-Go/model"
	pgtest "github.com/weiloon1234/Foundry-Go/testkit/postgres"
)

func TestPostgresTypedUpsertAndBatchDefaults(t *testing.T) {
	queryfixture.Run(t, func(tx *database.Tx, _ []models.User) error {
		if _, err := tx.Exec(t.Context(), `CREATE TABLE write_records (code bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL CONSTRAINT write_records_name_key UNIQUE,enabled boolean NOT NULL DEFAULT true,note text DEFAULT 'db-note',amount numeric NOT NULL DEFAULT 1.25)`); err != nil {
			return err
		}
		q := models.QueryWriteRecords()
		f := models.WriteRecordFields()
		initial, err := q.CreateMany(t.Context(), tx, []models.WriteRecordDraft{
			models.WriteRecordDraft{}.SetName("one").SetNote("kept"),
			models.WriteRecordDraft{}.SetName("two").SetEnabled(false).ClearNote(),
		})
		if err != nil {
			return err
		}
		byName := map[string]models.WriteRecord{}
		for _, record := range initial {
			byName[record.Name] = record
		}
		if len(byName) != 2 || !byName["one"].Enabled || byName["two"].Enabled || !byName["two"].Note.IsNull() {
			t.Fatal("batch defaults/zero/null states changed")
		}
		amount, err := decimal.Parse("42.50")
		if err != nil {
			return err
		}
		policy := query.OnConflict(f.Name).Update(f.Amount).Where(f.Enabled.Eq(true))
		result, err := q.Upsert(t.Context(), tx, models.WriteRecordDraft{}.SetName("one").SetAmount(amount), policy)
		if err != nil {
			return err
		}
		updated, present := result.Get()
		note, hasNote := updated.Note.Get()
		if !present || updated.Code != byName["one"].Code || updated.Amount.String() != "42.5" || !hasNote || note != "kept" {
			t.Fatal("upsert changed unrelated fields or identity", updated.Amount.String())
		}
		_, err = q.Upsert(t.Context(), tx, models.WriteRecordDraft{}.SetName("one"), query.OnConflictConstraint[models.WriteRecord]("write_records_name_key").DoUpdate(f.Note.SetNull(), f.Enabled.Set(false)))
		if err != nil {
			return err
		}
		skipped, err := q.Upsert(t.Context(), tx, models.WriteRecordDraft{}.SetName("one").SetAmount(amount), policy)
		if err != nil || skipped.IsSet() {
			t.Fatal("false update condition returned a model", err)
		}
		mixed, err := q.UpsertMany(t.Context(), tx, []models.WriteRecordDraft{
			models.WriteRecordDraft{}.SetName("one"), models.WriteRecordDraft{}.SetName("three"),
		}, query.OnConflict[models.WriteRecord]().DoNothing())
		if err != nil || len(mixed) != 1 || mixed[0].Name != "three" {
			t.Fatal("skipped batch rows lost identity", err)
		}
		_, err = q.UpsertMany(t.Context(), tx, []models.WriteRecordDraft{models.WriteRecordDraft{}.SetName("one"), models.WriteRecordDraft{}.SetName("two")}, query.OnConflict(f.Name).Update(f.Note))
		if err != nil {
			return err
		}
		all, err := q.All(t.Context(), tx)
		if err != nil {
			return err
		}
		for _, record := range all {
			if n, ok := record.Note.Get(); !ok || n != "db-note" {
				t.Fatal("selected omitted incoming field did not use database default")
			}
		}
		// Repeated update targets must fail the whole statement, not become
		// multiple hidden writes whose last input silently wins.
		_, err = q.UpsertMany(t.Context(), tx, []models.WriteRecordDraft{models.WriteRecordDraft{}.SetName("duplicate"), models.WriteRecordDraft{}.SetName("duplicate")}, query.OnConflict(f.Name).Update(f.Amount))
		var dbErr *database.Error
		if !errors.As(err, &dbErr) || dbErr.SQLState() != "21000" {
			t.Fatal("duplicate upsert target did not report PostgreSQL cardinality", err)
		}
		if n, err := q.Where(f.Name.Eq("duplicate")).Count(t.Context(), tx); err != nil || n != 0 {
			t.Fatal("failed upsert batch partially persisted", err)
		}
		// A codec failure after an earlier RETURNING row rolls back the batch.
		if _, err := tx.Exec(t.Context(), `ALTER TABLE write_records ALTER COLUMN amount SET DEFAULT 'NaN'`); err != nil {
			return err
		}
		items, err := q.CreateMany(t.Context(), tx, []models.WriteRecordDraft{models.WriteRecordDraft{}.SetName("valid-before-failure").SetAmount(amount), models.WriteRecordDraft{}.SetName("invalid-decimal")})
		if err == nil || items != nil {
			t.Fatal("failed returning decode published partial models")
		}
		if n, err := q.Where(f.Name.In("valid-before-failure", "invalid-decimal")).Count(t.Context(), tx); err != nil || n != 0 {
			t.Fatal("failed returning decode committed rows", err)
		}
		return nil
	})
}

func TestPostgresUpsertCompositeKeysAndReservedTarget(t *testing.T) {
	queryfixture.Run(t, func(tx *database.Tx, users []models.User) error {
		if _, err := tx.Exec(t.Context(), `CREATE UNIQUE INDEX users_email_level_key ON users(email_address,level)`); err != nil {
			return err
		}
		f := models.UserFields()
		draft := userDraft(users[0].Email, 99)
		result, err := models.QueryUsers().Upsert(t.Context(), tx, draft, query.OnConflict(f.Email, f.Level).Update(f.Age))
		if err != nil {
			return err
		}
		user, present := result.Get()
		if !present || user.ID != users[0].ID || user.Age != 99 || draft.ID().IsSet() {
			t.Fatal("composite conflict lost original UUID or mutated draft")
		}
		if _, err := tx.Exec(t.Context(), `CREATE TABLE excluded (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL DEFAULT 'before')`); err != nil {
			return err
		}
		r := upsertqueries.ExcludedRecordFields()
		q := upsertqueries.QueryExcluded()
		first, err := q.Create(t.Context(), tx, upsertqueries.ExcludedRecordDraft{}.SetName("before"))
		if err != nil {
			return err
		}
		after, err := q.Upsert(t.Context(), tx, upsertqueries.ExcludedRecordDraft{}.SetID(first.ID).SetName("after"), query.OnConflict(r.ID).Update(r.Name).Where(r.Name.Eq("before")))
		if err != nil {
			return err
		}
		actual, ok := after.Get()
		if !ok || actual.Name != "after" || actual.ID != first.ID {
			t.Fatal("physical excluded table confused target and incoming rows")
		}
		defaults, err := q.CreateMany(t.Context(), tx, []upsertqueries.ExcludedRecordDraft{{}, {}})
		if err != nil || len(defaults) != 2 || defaults[0].ID == defaults[1].ID || defaults[0].Name != "before" || defaults[1].Name != "before" {
			t.Fatal("all-default batch lost database-owned values", err)
		}
		return nil
	})
}

func userDraft(email string, age int) models.UserDraft {
	return models.UserDraft{}.SetEmail(email).SetAge(age).SetStatus(models.StatusActive).SetLevel(models.LevelBasic)
}

func TestPostgresConcurrentUpsertsShareOneIdentity(t *testing.T) {
	db := pgtest.Open(t)
	namespace := pgtest.Namespace(t, db)
	path := `SET LOCAL search_path TO "` + namespace + `"`
	if err := db.Transaction(t.Context(), func(tx *database.Tx) error {
		if _, err := tx.Exec(t.Context(), path); err != nil {
			return err
		}
		_, err := tx.Exec(t.Context(), `CREATE TABLE users (id uuid PRIMARY KEY,email_address text NOT NULL UNIQUE,age bigint NOT NULL,nickname text,status text NOT NULL,level smallint NOT NULL,birthday date,introducer_id uuid)`)
		return err
	}); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()
	start := make(chan struct{})
	ready := make(chan struct{}, 2)
	type outcome struct {
		id  model.ID[models.User]
		err error
	}
	outcomes := make(chan outcome, 2)
	for age := 1; age <= 2; age++ {
		go func() {
			var id model.ID[models.User]
			err := db.Transaction(ctx, func(tx *database.Tx) error {
				if _, err := tx.Exec(ctx, path); err != nil {
					return err
				}
				ready <- struct{}{}
				select {
				case <-start:
				case <-ctx.Done():
					return ctx.Err()
				}
				f := models.UserFields()
				result, err := models.QueryUsers().Upsert(ctx, tx, userDraft("same@example.test", age), query.OnConflict(f.Email).Update(f.Age))
				if err != nil {
					return err
				}
				u, present := result.Get()
				if !present {
					return errors.New("concurrent upsert unexpectedly skipped")
				}
				id = u.ID
				return nil
			})
			outcomes <- outcome{id, err}
		}()
	}
	for range 2 {
		select {
		case <-ready:
		case <-ctx.Done():
			t.Fatal("concurrent writers did not reach barrier")
		}
	}
	close(start)
	a, b := <-outcomes, <-outcomes
	if a.err != nil || b.err != nil || a.id != b.id {
		t.Fatal("atomic conflict handling lost shared identity", a.err, b.err)
	}
	if err := db.Transaction(t.Context(), func(tx *database.Tx) error {
		if _, err := tx.Exec(t.Context(), path); err != nil {
			return err
		}
		n, err := models.QueryUsers().Count(t.Context(), tx)
		if err != nil {
			return err
		}
		if n != 1 {
			return errors.New("concurrent upserts created duplicate rows")
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
}

type noWrites struct{ t *testing.T }

func (w noWrites) Transaction(context.Context, func(*database.Tx) error, ...database.TxOptions) error {
	w.t.Error("invalid or empty write opened a transaction")
	return errors.New("unexpected write")
}

func TestUpsertInvalidAndEmptyBatchesUseNoDatabase(t *testing.T) {
	q := models.QueryWriteRecords()
	f := models.WriteRecordFields()
	writer := noWrites{t}
	if items, err := q.CreateMany(t.Context(), writer, nil); err != nil || items == nil || len(items) != 0 {
		t.Fatal("empty insert failed", err)
	}
	if items, err := q.UpsertMany(t.Context(), writer, nil, query.OnConflict(f.Name).Update(f.Note)); err != nil || items == nil || len(items) != 0 {
		t.Fatal("empty upsert failed", err)
	}
	for _, run := range []func() error{
		func() error {
			_, err := q.CreateMany(t.Context(), writer, make([]models.WriteRecordDraft, query.MaxInsertRows+1))
			return err
		},
		func() error {
			_, err := q.UpsertMany(t.Context(), writer, nil, query.Conflict[models.WriteRecord]{})
			return err
		},
		func() error { _, err := q.Where(f.Name.Eq("ignored")).CreateMany(t.Context(), writer, nil); return err },
		func() error {
			_, err := q.Upsert(t.Context(), writer, models.WriteRecordDraft{}.SetName("one"), query.OnConflict(f.Name).Update(f.Code))
			return err
		},
	} {
		if err := run(); !errors.Is(err, fault.Invalid) {
			t.Fatal("invalid insert option accepted", err)
		}
	}
}
