// Code generated by foundry generate; DO NOT EDIT.
// Source: models.go:46.

package tokenstore

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	temporal "github.com/weiloon1234/Foundry-Go/temporal"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
)

// EntryFieldSet exposes fields owned by the unaliased model.
type EntryFieldSet = EntryScopedFieldSet[Entry]

// EntryFields returns independent immutable field descriptors.
func EntryFields() EntryFieldSet {
	return EntryFieldsAt(foundryquery.DeclareModelScope[Entry]("foundry_token_generations"))
}

// EntryScopedFieldSet preserves typed field operators in a declared query scope.
type EntryScopedFieldSet[FoundryScope any] struct {
	// ID describes foundry_token_generations.id.
	ID foundryquery.ScalarField[FoundryScope, model.ID[Entry]]
	// Scope describes foundry_token_generations.scope.
	Scope foundryquery.TextField[FoundryScope, string]
	// FamilyID describes foundry_token_generations.family_id.
	FamilyID foundryquery.ScalarField[FoundryScope, model.ID[Family]]
	// Generation describes foundry_token_generations.generation.
	Generation foundryquery.ExactField[FoundryScope, uint32]
	// AccessHash describes foundry_token_generations.access_hash.
	AccessHash foundryquery.TextField[FoundryScope, string]
	// RefreshHash describes foundry_token_generations.refresh_hash.
	RefreshHash foundryquery.NullableTextField[FoundryScope, string]
	// IssuedAt describes foundry_token_generations.issued_at.
	IssuedAt foundryquery.OrderedField[FoundryScope, temporal.DateTime]
	// LastSeenAt describes foundry_token_generations.last_seen_at.
	LastSeenAt foundryquery.OrderedField[FoundryScope, temporal.DateTime]
	// AccessExpiresAt describes foundry_token_generations.access_expires_at.
	AccessExpiresAt foundryquery.OrderedField[FoundryScope, temporal.DateTime]
	// RefreshExpiresAt describes foundry_token_generations.refresh_expires_at.
	RefreshExpiresAt foundryquery.NullableOrderedField[FoundryScope, temporal.DateTime]
}

// EntryFieldsAt binds these record fields to an alias or joined scope.
func EntryFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, Entry]) EntryScopedFieldSet[FoundryScope] {
	return EntryScopedFieldSet[FoundryScope]{
		ID:               foundryquery.NewScalarField[FoundryScope, model.ID[Entry]](scope.Table(), "id", codec.ID[Entry]()),
		Scope:            foundryquery.NewTextField[FoundryScope, string](scope.Table(), "scope", codec.String[string]()),
		FamilyID:         foundryquery.NewScalarField[FoundryScope, model.ID[Family]](scope.Table(), "family_id", codec.ID[Family]()),
		Generation:       foundryquery.NewExactField[FoundryScope, uint32](scope.Table(), "generation", codec.Unsigned[uint32]()),
		AccessHash:       foundryquery.NewTextField[FoundryScope, string](scope.Table(), "access_hash", codec.String[string]()),
		RefreshHash:      foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "refresh_hash", codec.String[string]()),
		IssuedAt:         foundryquery.NewOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "issued_at", codec.DateTime()),
		LastSeenAt:       foundryquery.NewOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "last_seen_at", codec.DateTime()),
		AccessExpiresAt:  foundryquery.NewOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "access_expires_at", codec.DateTime()),
		RefreshExpiresAt: foundryquery.NewNullableOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "refresh_expires_at", codec.DateTime()),
	}
}

// EntryNullableFieldSet preserves typed field operators in a declared query scope.
type EntryNullableFieldSet[FoundryScope any] struct {
	// ID describes foundry_token_generations.id.
	ID foundryquery.NullableField[FoundryScope, model.ID[Entry]]
	// Scope describes foundry_token_generations.scope.
	Scope foundryquery.NullableTextField[FoundryScope, string]
	// FamilyID describes foundry_token_generations.family_id.
	FamilyID foundryquery.NullableField[FoundryScope, model.ID[Family]]
	// Generation describes foundry_token_generations.generation.
	Generation foundryquery.NullableExactField[FoundryScope, uint32]
	// AccessHash describes foundry_token_generations.access_hash.
	AccessHash foundryquery.NullableTextField[FoundryScope, string]
	// RefreshHash describes foundry_token_generations.refresh_hash.
	RefreshHash foundryquery.NullableTextField[FoundryScope, string]
	// IssuedAt describes foundry_token_generations.issued_at.
	IssuedAt foundryquery.NullableOrderedField[FoundryScope, temporal.DateTime]
	// LastSeenAt describes foundry_token_generations.last_seen_at.
	LastSeenAt foundryquery.NullableOrderedField[FoundryScope, temporal.DateTime]
	// AccessExpiresAt describes foundry_token_generations.access_expires_at.
	AccessExpiresAt foundryquery.NullableOrderedField[FoundryScope, temporal.DateTime]
	// RefreshExpiresAt describes foundry_token_generations.refresh_expires_at.
	RefreshExpiresAt foundryquery.NullableOrderedField[FoundryScope, temporal.DateTime]
}

// EntryNullableFieldsAt binds these record fields to an alias or joined scope.
func EntryNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, Entry]) EntryNullableFieldSet[FoundryScope] {
	return EntryNullableFieldSet[FoundryScope]{
		ID:               foundryquery.NewNullableField[FoundryScope, model.ID[Entry]](scope.Table(), "id", codec.ID[Entry]()),
		Scope:            foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "scope", codec.String[string]()),
		FamilyID:         foundryquery.NewNullableField[FoundryScope, model.ID[Family]](scope.Table(), "family_id", codec.ID[Family]()),
		Generation:       foundryquery.NewNullableExactField[FoundryScope, uint32](scope.Table(), "generation", codec.Unsigned[uint32]()),
		AccessHash:       foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "access_hash", codec.String[string]()),
		RefreshHash:      foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "refresh_hash", codec.String[string]()),
		IssuedAt:         foundryquery.NewNullableOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "issued_at", codec.DateTime()),
		LastSeenAt:       foundryquery.NewNullableOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "last_seen_at", codec.DateTime()),
		AccessExpiresAt:  foundryquery.NewNullableOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "access_expires_at", codec.DateTime()),
		RefreshExpiresAt: foundryquery.NewNullableOrderedField[FoundryScope, temporal.DateTime](scope.Table(), "refresh_expires_at", codec.DateTime()),
	}
}

// EntryQuery preserves model-specific keys through fluent query derivation.
type EntryQuery struct{ foundryquery.Query[Entry] }

// QueryFoundryTokenGenerations starts a complete-model query for foundry_token_generations with generated hydration.
func QueryFoundryTokenGenerations() EntryQuery {
	return EntryQuery{foundryquery.ForModel(foundryquery.Define[Entry]("foundry_token_generations", "id", []foundryquery.Column{foundryquery.Column{Name: "id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "scope", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "family_id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "generation", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "access_hash", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "refresh_hash", Nullable: true, DatabaseDefault: false}, foundryquery.Column{Name: "issued_at", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "last_seen_at", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "access_expires_at", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "refresh_expires_at", Nullable: true, DatabaseDefault: false}}, func(row database.Row) (Entry, error) {
		var item Entry
		if err := row.Scan(
			codec.ID[Entry]().Scan(&item.ID),
			codec.String[string]().Scan(&item.Scope),
			codec.ID[Family]().Scan(&item.FamilyID),
			codec.Unsigned[uint32]().Scan(&item.Generation),
			codec.String[string]().Scan(&item.AccessHash),
			codec.Nullable(codec.String[string]()).Scan(&item.RefreshHash),
			codec.DateTime().Scan(&item.IssuedAt),
			codec.DateTime().Scan(&item.LastSeenAt),
			codec.DateTime().Scan(&item.AccessExpiresAt),
			codec.Nullable(codec.DateTime()).Scan(&item.RefreshExpiresAt),
		); err != nil {
			return Entry{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("id", codec.ID[Entry](), func(item Entry) model.ID[Entry] { return item.ID }),
		foundryquery.NewModelField("scope", codec.String[string](), func(item Entry) string { return item.Scope }),
		foundryquery.NewModelField("family_id", codec.ID[Family](), func(item Entry) model.ID[Family] { return item.FamilyID }),
		foundryquery.NewModelField("generation", codec.Unsigned[uint32](), func(item Entry) uint32 { return item.Generation }),
		foundryquery.NewModelField("access_hash", codec.String[string](), func(item Entry) string { return item.AccessHash }),
		foundryquery.NewModelField("refresh_hash", codec.Nullable(codec.String[string]()), func(item Entry) foundryvalue.Nullable[string] { return item.RefreshHash }),
		foundryquery.NewModelField("issued_at", codec.DateTime(), func(item Entry) temporal.DateTime { return item.IssuedAt }),
		foundryquery.NewModelField("last_seen_at", codec.DateTime(), func(item Entry) temporal.DateTime { return item.LastSeenAt }),
		foundryquery.NewModelField("access_expires_at", codec.DateTime(), func(item Entry) temporal.DateTime { return item.AccessExpiresAt }),
		foundryquery.NewModelField("refresh_expires_at", codec.Nullable(codec.DateTime()), func(item Entry) foundryvalue.Nullable[temporal.DateTime] { return item.RefreshExpiresAt }),
	).WithObserverHooks((EntryHooks{}).foundryWriteHooks, false).WithRetrievalHooks((EntryRetrievalHooks{}).foundryRetrievalHooks, false))}
}

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (Entry) FoundryQuery() foundryquery.Query[Entry] { return QueryFoundryTokenGenerations().Query }

// FoundryReference retains Entry and its concrete stored primary key for framework integrations.
// It reads ID directly, never calls an accessor, and performs no database lookup.
func (m Entry) FoundryReference() model.Reference[Entry, model.ID[Entry]] {
	return model.NewReference[Entry]("foundry_token_generations", m.ID, codec.ID[Entry]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m Entry) FoundryIdentity() (model.Identity, error) { return m.FoundryReference().Identity() }

// WithTrashed derives a new Entry query without changing its source.
func (q EntryQuery) WithTrashed() EntryQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new Entry query without changing its source.
func (q EntryQuery) OnlyTrashed() EntryQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new Entry query without changing its source.
func (q EntryQuery) WithoutTrashed() EntryQuery { q.Query = q.Query.WithoutTrashed(); return q }

// Where derives a new Entry query without changing its source.
func (q EntryQuery) Where(predicates ...foundryquery.Predicate[Entry]) EntryQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new Entry query without changing its source.
func (q EntryQuery) WhereHas(relation foundryquery.ExistenceRelation[Entry]) EntryQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new Entry query without changing its source.
func (q EntryQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Entry]) EntryQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new Entry query without changing its source.
func (q EntryQuery) OrderBy(orders ...foundryquery.Order[Entry]) EntryQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new Entry query without changing its source.
func (q EntryQuery) Limit(count int) EntryQuery { q.Query = q.Query.Limit(count); return q }

// Offset derives a new Entry query without changing its source.
func (q EntryQuery) Offset(count int) EntryQuery { q.Query = q.Query.Offset(count); return q }

// With derives a new Entry query without changing its source.
func (q EntryQuery) With(relations ...foundryquery.Relation[Entry]) EntryQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new Entry query without changing its source.
func (q EntryQuery) WithRelationLimits(limits foundryquery.RelationLimits) EntryQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q EntryQuery) Find(ctx context.Context, executor database.Executor, key model.ID[Entry]) (foundryvalue.Optional[Entry], error) {
	return q.Where(EntryFields().ID.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q EntryQuery) RequireFind(ctx context.Context, executor database.Executor, key model.ID[Entry]) (Entry, error) {
	return q.Where(EntryFields().ID.Eq(key)).RequireFirst(ctx, executor)
}

// EntryLockedQuery preserves typed keys while requiring transaction-scoped reads.
type EntryLockedQuery struct {
	foundryquery.LockedQuery[Entry]
}

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EntryQuery) ForUpdate() EntryLockedQuery { return EntryLockedQuery{q.Query.ForUpdate()} }

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EntryQuery) ForNoKeyUpdate() EntryLockedQuery {
	return EntryLockedQuery{q.Query.ForNoKeyUpdate()}
}

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EntryQuery) ForShare() EntryLockedQuery { return EntryLockedQuery{q.Query.ForShare()} }

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q EntryQuery) ForKeyShare() EntryLockedQuery { return EntryLockedQuery{q.Query.ForKeyShare()} }

// WithTrashed derives a locked Entry query without changing its source.
func (q EntryLockedQuery) WithTrashed() EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked Entry query without changing its source.
func (q EntryLockedQuery) OnlyTrashed() EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked Entry query without changing its source.
func (q EntryLockedQuery) WithoutTrashed() EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// Where derives a locked Entry query without changing its source.
func (q EntryLockedQuery) Where(predicates ...foundryquery.Predicate[Entry]) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked Entry query without changing its source.
func (q EntryLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[Entry]) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked Entry query without changing its source.
func (q EntryLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Entry]) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked Entry query without changing its source.
func (q EntryLockedQuery) OrderBy(orders ...foundryquery.Order[Entry]) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked Entry query without changing its source.
func (q EntryLockedQuery) Limit(count int) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked Entry query without changing its source.
func (q EntryLockedQuery) Offset(count int) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked Entry query without changing its source.
func (q EntryLockedQuery) With(relations ...foundryquery.Relation[Entry]) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked Entry query without changing its source.
func (q EntryLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked Entry query without changing its source.
func (q EntryLockedQuery) NoWait() EntryLockedQuery { q.LockedQuery = q.LockedQuery.NoWait(); return q }

// SkipLocked derives a locked Entry query without changing its source.
func (q EntryLockedQuery) SkipLocked() EntryLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked Entry query without changing its source.
func (q EntryLockedQuery) Wait() EntryLockedQuery { q.LockedQuery = q.LockedQuery.Wait(); return q }

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q EntryLockedQuery) Find(ctx context.Context, tx *database.Tx, key model.ID[Entry]) (foundryvalue.Optional[Entry], error) {
	return q.Where(EntryFields().ID.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q EntryLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key model.ID[Entry]) (Entry, error) {
	return q.Where(EntryFields().ID.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q EntryQuery) Create(ctx context.Context, writer database.Transactor, draft EntryDraft) (Entry, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return Entry{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q EntryQuery) Upsert(ctx context.Context, writer database.Transactor, draft EntryDraft, conflict foundryquery.Conflict[Entry]) (foundryvalue.Optional[Entry], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[Entry]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q EntryQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []EntryDraft) ([]Entry, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q EntryQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []EntryDraft, conflict foundryquery.Conflict[Entry]) ([]Entry, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q EntryQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []EntryDraft, conflict *foundryquery.Conflict[Entry]) ([]Entry, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q EntryQuery) foundryCreateMutations(drafts []EntryDraft) ([]foundryquery.Mutation[Entry], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[Entry], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q EntryQuery) Update(ctx context.Context, writer database.Transactor, key model.ID[Entry], draft EntryDraft) (Entry, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return Entry{}, err
	}
	return q.Where(EntryFields().ID.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete removes one typed primary key within this query's filters and returns its complete pre-deletion model.
func (q EntryQuery) Delete(ctx context.Context, writer database.Transactor, key model.ID[Entry]) (Entry, error) {
	return q.Where(EntryFields().ID.Eq(key)).Query.Remove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q EntryQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []EntryDraft) ([]Entry, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q EntryQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, Entry) (EntryDraft, error)) ([]Entry, error) {
	var callback func(context.Context, *database.Tx, Entry) (foundryquery.Mutation[Entry], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Entry) (foundryquery.Mutation[Entry], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q EntryQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Entry, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q EntryQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create EntryDraft) (Entry, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q EntryQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create EntryDraft, draft func(context.Context, *database.Tx, Entry) (EntryDraft, error)) (Entry, error) {
	var callback func(context.Context, *database.Tx, Entry) (foundryquery.Mutation[Entry], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Entry) (foundryquery.Mutation[Entry], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// EntryInsertFromBuilder selects stored SQL values into Entry through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type EntryInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, Entry]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p EntryInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertEntryFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertEntryFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) EntryInsertFromBuilder[FoundryScope] {
	return EntryInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (Entry{}).FoundryQuery())}
}

// SelectID supplies the stored SQL value for id. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, model.ID[Entry]]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().ID, v))
	return p
}

// SelectScope supplies the stored SQL value for scope. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectScope(v foundryquery.Expression[FoundryScope, string]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().Scope, v))
	return p
}

// SelectFamilyID supplies the stored SQL value for family_id. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectFamilyID(v foundryquery.Expression[FoundryScope, model.ID[Family]]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().FamilyID, v))
	return p
}

// SelectGeneration supplies the stored SQL value for generation. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectGeneration(v foundryquery.Expression[FoundryScope, uint32]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().Generation, v))
	return p
}

// SelectAccessHash supplies the stored SQL value for access_hash. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectAccessHash(v foundryquery.Expression[FoundryScope, string]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().AccessHash, v))
	return p
}

// SelectRefreshHash supplies the stored SQL value for refresh_hash. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectRefreshHash(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().RefreshHash, v))
	return p
}

// SelectIssuedAt supplies the stored SQL value for issued_at. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectIssuedAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().IssuedAt, v))
	return p
}

// SelectLastSeenAt supplies the stored SQL value for last_seen_at. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectLastSeenAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().LastSeenAt, v))
	return p
}

// SelectAccessExpiresAt supplies the stored SQL value for access_expires_at. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectAccessExpiresAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().AccessExpiresAt, v))
	return p
}

// SelectRefreshExpiresAt supplies the stored SQL value for refresh_expires_at. It cannot also be supplied by Values.
func (p EntryInsertFromBuilder[FoundryScope]) SelectRefreshExpiresAt(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[temporal.DateTime]]) EntryInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(EntryFields().RefreshExpiresAt, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p EntryInsertFromBuilder[FoundryScope]) Values(draft EntryDraft) EntryInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p EntryInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p EntryInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Entry, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// EntryUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type EntryUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, Entry]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p EntryUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdateEntryFrom preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func UpdateEntryFrom[FoundryScope any](destination EntryQuery, source foundryquery.ProjectionSource[FoundryScope]) EntryUpdateFromBuilder[FoundryScope] {
	return EntryUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p EntryUpdateFromBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Entry]]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(EntryFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p EntryUpdateFromBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Entry]]]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(EntryFields().ID, v))
	return p
}

// SelectScope assigns a stored source value to scope; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectScope(v foundryquery.Expression[FoundryScope, string]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().Scope, v))
	return p
}

// SelectFamilyID assigns a stored source value to family_id; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectFamilyID(v foundryquery.Expression[FoundryScope, model.ID[Family]]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().FamilyID, v))
	return p
}

// SelectGeneration assigns a stored source value to generation; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectGeneration(v foundryquery.Expression[FoundryScope, uint32]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().Generation, v))
	return p
}

// SelectAccessHash assigns a stored source value to access_hash; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectAccessHash(v foundryquery.Expression[FoundryScope, string]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().AccessHash, v))
	return p
}

// SelectRefreshHash assigns a stored source value to refresh_hash; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectRefreshHash(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[string]]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().RefreshHash, v))
	return p
}

// SelectIssuedAt assigns a stored source value to issued_at; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectIssuedAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().IssuedAt, v))
	return p
}

// SelectLastSeenAt assigns a stored source value to last_seen_at; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectLastSeenAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().LastSeenAt, v))
	return p
}

// SelectAccessExpiresAt assigns a stored source value to access_expires_at; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectAccessExpiresAt(v foundryquery.Expression[FoundryScope, temporal.DateTime]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().AccessExpiresAt, v))
	return p
}

// SelectRefreshExpiresAt assigns a stored source value to refresh_expires_at; Values cannot also supply it.
func (p EntryUpdateFromBuilder[FoundryScope]) SelectRefreshExpiresAt(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[temporal.DateTime]]) EntryUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(EntryFields().RefreshExpiresAt, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p EntryUpdateFromBuilder[FoundryScope]) Values(draft EntryDraft) EntryUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p EntryUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p EntryUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Entry, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// EntryDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type EntryDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, Entry]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p EntryDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeleteEntryUsing preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func DeleteEntryUsing[FoundryScope any](destination EntryQuery, source foundryquery.ProjectionSource[FoundryScope]) EntryDeleteUsingBuilder[FoundryScope] {
	return EntryDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p EntryDeleteUsingBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, model.ID[Entry]]) EntryDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(EntryFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p EntryDeleteUsingBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[model.ID[Entry]]]) EntryDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(EntryFields().ID, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p EntryDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p EntryDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Entry, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d EntryDraft) FoundryCreateMutation(defaults foundryquery.Mutation[Entry]) (foundryquery.Mutation[Entry], error) {
	values, err := foundryquery.ReadCreateDefaults((Entry{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[Entry]{}, err
	}
	if !d.fieldID.IsSet() {
		v, err := foundryquery.MutationValue[Entry, model.ID[Entry]](values, "foundry_token_generations", "id")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldID = v
	}
	if !d.fieldScope.IsSet() {
		v, err := foundryquery.MutationValue[Entry, string](values, "foundry_token_generations", "scope")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldScope = v
	}
	if !d.fieldFamilyID.IsSet() {
		v, err := foundryquery.MutationValue[Entry, model.ID[Family]](values, "foundry_token_generations", "family_id")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldFamilyID = v
	}
	if !d.fieldGeneration.IsSet() {
		v, err := foundryquery.MutationValue[Entry, uint32](values, "foundry_token_generations", "generation")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldGeneration = v
	}
	if !d.fieldAccessHash.IsSet() {
		v, err := foundryquery.MutationValue[Entry, string](values, "foundry_token_generations", "access_hash")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldAccessHash = v
	}
	if !d.fieldRefreshHash.IsSet() {
		v, err := foundryquery.MutationValue[Entry, foundryvalue.Nullable[string]](values, "foundry_token_generations", "refresh_hash")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldRefreshHash = v
	}
	if !d.fieldIssuedAt.IsSet() {
		v, err := foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "issued_at")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldIssuedAt = v
	}
	if !d.fieldLastSeenAt.IsSet() {
		v, err := foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "last_seen_at")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldLastSeenAt = v
	}
	if !d.fieldAccessExpiresAt.IsSet() {
		v, err := foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "access_expires_at")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldAccessExpiresAt = v
	}
	if !d.fieldRefreshExpiresAt.IsSet() {
		v, err := foundryquery.MutationValue[Entry, foundryvalue.Nullable[temporal.DateTime]](values, "foundry_token_generations", "refresh_expires_at")
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d.fieldRefreshExpiresAt = v
	}
	return d.foundryMutation(true)
}
func (d EntryDraft) foundryMutation(create bool) (foundryquery.Mutation[Entry], error) {
	if create && !d.fieldID.IsSet() {
		id, err := model.NewID[Entry]()
		if err != nil {
			return foundryquery.Mutation[Entry]{}, err
		}
		d = d.SetID(id)
	}
	var assignments []foundryquery.Assignment[Entry]
	if v, set := d.fieldID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "id", codec.ID[Entry](), v))
	}
	if v, set := d.fieldScope.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "scope", codec.String[string](), v))
	}
	if v, set := d.fieldFamilyID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "family_id", codec.ID[Family](), v))
	}
	if v, set := d.fieldGeneration.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "generation", codec.Unsigned[uint32](), v))
	}
	if v, set := d.fieldAccessHash.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "access_hash", codec.String[string](), v))
	}
	if v, set := d.fieldRefreshHash.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "refresh_hash", codec.Nullable(codec.String[string]()), v))
	}
	if v, set := d.fieldIssuedAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "issued_at", codec.DateTime(), v))
	}
	if v, set := d.fieldLastSeenAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "last_seen_at", codec.DateTime(), v))
	}
	if v, set := d.fieldAccessExpiresAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "access_expires_at", codec.DateTime(), v))
	}
	if v, set := d.fieldRefreshExpiresAt.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Entry]("foundry_token_generations", "refresh_expires_at", codec.Nullable(codec.DateTime()), v))
	}
	return foundryquery.Change(assignments...), nil
}

// EntryDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type EntryDraft struct {
	fieldID               foundryvalue.Optional[model.ID[Entry]]
	fieldScope            foundryvalue.Optional[string]
	fieldFamilyID         foundryvalue.Optional[model.ID[Family]]
	fieldGeneration       foundryvalue.Optional[uint32]
	fieldAccessHash       foundryvalue.Optional[string]
	fieldRefreshHash      foundryvalue.Optional[foundryvalue.Nullable[string]]
	fieldIssuedAt         foundryvalue.Optional[temporal.DateTime]
	fieldLastSeenAt       foundryvalue.Optional[temporal.DateTime]
	fieldAccessExpiresAt  foundryvalue.Optional[temporal.DateTime]
	fieldRefreshExpiresAt foundryvalue.Optional[foundryvalue.Nullable[temporal.DateTime]]
}

// ID returns the typed mutation state for id.
func (d EntryDraft) ID() foundryvalue.Optional[model.ID[Entry]] { return d.fieldID }

// SetID returns a new draft with id explicitly set.
func (d EntryDraft) SetID(v model.ID[Entry]) EntryDraft { d.fieldID = foundryvalue.Set(v); return d }

// UnsetID omits id without requesting a zero or null write.
func (d EntryDraft) UnsetID() EntryDraft {
	d.fieldID = foundryvalue.Optional[model.ID[Entry]]{}
	return d
}

// Scope returns the typed mutation state for scope.
func (d EntryDraft) Scope() foundryvalue.Optional[string] { return d.fieldScope }

// SetScope returns a new draft with scope explicitly set.
func (d EntryDraft) SetScope(v string) EntryDraft { d.fieldScope = foundryvalue.Set(v); return d }

// UnsetScope omits scope without requesting a zero or null write.
func (d EntryDraft) UnsetScope() EntryDraft { d.fieldScope = foundryvalue.Optional[string]{}; return d }

// FamilyID returns the typed mutation state for family_id.
func (d EntryDraft) FamilyID() foundryvalue.Optional[model.ID[Family]] { return d.fieldFamilyID }

// SetFamilyID returns a new draft with family_id explicitly set.
func (d EntryDraft) SetFamilyID(v model.ID[Family]) EntryDraft {
	d.fieldFamilyID = foundryvalue.Set(v)
	return d
}

// UnsetFamilyID omits family_id without requesting a zero or null write.
func (d EntryDraft) UnsetFamilyID() EntryDraft {
	d.fieldFamilyID = foundryvalue.Optional[model.ID[Family]]{}
	return d
}

// Generation returns the typed mutation state for generation.
func (d EntryDraft) Generation() foundryvalue.Optional[uint32] { return d.fieldGeneration }

// SetGeneration returns a new draft with generation explicitly set.
func (d EntryDraft) SetGeneration(v uint32) EntryDraft {
	d.fieldGeneration = foundryvalue.Set(v)
	return d
}

// UnsetGeneration omits generation without requesting a zero or null write.
func (d EntryDraft) UnsetGeneration() EntryDraft {
	d.fieldGeneration = foundryvalue.Optional[uint32]{}
	return d
}

// AccessHash returns the typed mutation state for access_hash.
func (d EntryDraft) AccessHash() foundryvalue.Optional[string] { return d.fieldAccessHash }

// SetAccessHash returns a new draft with access_hash explicitly set.
func (d EntryDraft) SetAccessHash(v string) EntryDraft {
	d.fieldAccessHash = foundryvalue.Set(v)
	return d
}

// UnsetAccessHash omits access_hash without requesting a zero or null write.
func (d EntryDraft) UnsetAccessHash() EntryDraft {
	d.fieldAccessHash = foundryvalue.Optional[string]{}
	return d
}

// RefreshHash returns the typed mutation state for refresh_hash.
func (d EntryDraft) RefreshHash() foundryvalue.Optional[foundryvalue.Nullable[string]] {
	return d.fieldRefreshHash
}

// SetRefreshHash returns a new draft with refresh_hash explicitly set.
func (d EntryDraft) SetRefreshHash(v string) EntryDraft {
	d.fieldRefreshHash = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetRefreshHash omits refresh_hash without requesting a zero or null write.
func (d EntryDraft) UnsetRefreshHash() EntryDraft {
	d.fieldRefreshHash = foundryvalue.Optional[foundryvalue.Nullable[string]]{}
	return d
}

// ClearRefreshHash explicitly sets refresh_hash to null.
func (d EntryDraft) ClearRefreshHash() EntryDraft {
	d.fieldRefreshHash = foundryvalue.Set(foundryvalue.Null[string]())
	return d
}

// IssuedAt returns the typed mutation state for issued_at.
func (d EntryDraft) IssuedAt() foundryvalue.Optional[temporal.DateTime] { return d.fieldIssuedAt }

// SetIssuedAt returns a new draft with issued_at explicitly set.
func (d EntryDraft) SetIssuedAt(v temporal.DateTime) EntryDraft {
	d.fieldIssuedAt = foundryvalue.Set(v)
	return d
}

// UnsetIssuedAt omits issued_at without requesting a zero or null write.
func (d EntryDraft) UnsetIssuedAt() EntryDraft {
	d.fieldIssuedAt = foundryvalue.Optional[temporal.DateTime]{}
	return d
}

// LastSeenAt returns the typed mutation state for last_seen_at.
func (d EntryDraft) LastSeenAt() foundryvalue.Optional[temporal.DateTime] { return d.fieldLastSeenAt }

// SetLastSeenAt returns a new draft with last_seen_at explicitly set.
func (d EntryDraft) SetLastSeenAt(v temporal.DateTime) EntryDraft {
	d.fieldLastSeenAt = foundryvalue.Set(v)
	return d
}

// UnsetLastSeenAt omits last_seen_at without requesting a zero or null write.
func (d EntryDraft) UnsetLastSeenAt() EntryDraft {
	d.fieldLastSeenAt = foundryvalue.Optional[temporal.DateTime]{}
	return d
}

// AccessExpiresAt returns the typed mutation state for access_expires_at.
func (d EntryDraft) AccessExpiresAt() foundryvalue.Optional[temporal.DateTime] {
	return d.fieldAccessExpiresAt
}

// SetAccessExpiresAt returns a new draft with access_expires_at explicitly set.
func (d EntryDraft) SetAccessExpiresAt(v temporal.DateTime) EntryDraft {
	d.fieldAccessExpiresAt = foundryvalue.Set(v)
	return d
}

// UnsetAccessExpiresAt omits access_expires_at without requesting a zero or null write.
func (d EntryDraft) UnsetAccessExpiresAt() EntryDraft {
	d.fieldAccessExpiresAt = foundryvalue.Optional[temporal.DateTime]{}
	return d
}

// RefreshExpiresAt returns the typed mutation state for refresh_expires_at.
func (d EntryDraft) RefreshExpiresAt() foundryvalue.Optional[foundryvalue.Nullable[temporal.DateTime]] {
	return d.fieldRefreshExpiresAt
}

// SetRefreshExpiresAt returns a new draft with refresh_expires_at explicitly set.
func (d EntryDraft) SetRefreshExpiresAt(v temporal.DateTime) EntryDraft {
	d.fieldRefreshExpiresAt = foundryvalue.Set(foundryvalue.Of(v))
	return d
}

// UnsetRefreshExpiresAt omits refresh_expires_at without requesting a zero or null write.
func (d EntryDraft) UnsetRefreshExpiresAt() EntryDraft {
	d.fieldRefreshExpiresAt = foundryvalue.Optional[foundryvalue.Nullable[temporal.DateTime]]{}
	return d
}

// ClearRefreshExpiresAt explicitly sets refresh_expires_at to null.
func (d EntryDraft) ClearRefreshExpiresAt() EntryDraft {
	d.fieldRefreshExpiresAt = foundryvalue.Set(foundryvalue.Null[temporal.DateTime]())
	return d
}

// IsEmpty reports whether no fields have been selected for mutation.
func (d EntryDraft) IsEmpty() bool {
	return !d.fieldID.IsSet() && !d.fieldScope.IsSet() && !d.fieldFamilyID.IsSet() && !d.fieldGeneration.IsSet() && !d.fieldAccessHash.IsSet() && !d.fieldRefreshHash.IsSet() && !d.fieldIssuedAt.IsSet() && !d.fieldLastSeenAt.IsSet() && !d.fieldAccessExpiresAt.IsSet() && !d.fieldRefreshExpiresAt.IsSet()
}

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (EntryDraft) Format(state fmt.State, _ rune) { _, _ = state.Write([]byte("Entry draft")) }

// EntryFieldChanges contains typed changes for persisted fields only.
type EntryFieldChanges struct {
	// ID retains the typed change for id.
	ID lifecycle.FieldChange[model.ID[Entry]]
	// Scope retains the typed change for scope.
	Scope lifecycle.FieldChange[string]
	// FamilyID retains the typed change for family_id.
	FamilyID lifecycle.FieldChange[model.ID[Family]]
	// Generation retains the typed change for generation.
	Generation lifecycle.FieldChange[uint32]
	// AccessHash retains the typed change for access_hash.
	AccessHash lifecycle.FieldChange[string]
	// RefreshHash retains the typed change for refresh_hash.
	RefreshHash lifecycle.FieldChange[foundryvalue.Nullable[string]]
	// IssuedAt retains the typed change for issued_at.
	IssuedAt lifecycle.FieldChange[temporal.DateTime]
	// LastSeenAt retains the typed change for last_seen_at.
	LastSeenAt lifecycle.FieldChange[temporal.DateTime]
	// AccessExpiresAt retains the typed change for access_expires_at.
	AccessExpiresAt lifecycle.FieldChange[temporal.DateTime]
	// RefreshExpiresAt retains the typed change for refresh_expires_at.
	RefreshExpiresAt lifecycle.FieldChange[foundryvalue.Nullable[temporal.DateTime]]
}

// EntryChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type EntryChanges struct {
	before, after foundryvalue.Optional[Entry]
	fields        EntryFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c EntryChanges) Operation() foundryvalue.Optional[lifecycle.Operation] { return c.operation }

// Before returns the persisted model before the operation, or absence for creation.
func (c EntryChanges) Before() foundryvalue.Optional[Entry] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c EntryChanges) After() foundryvalue.Optional[Entry] { return c.after }

// Fields returns model-specific field changes by value.
func (c EntryChanges) Fields() EntryFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c EntryChanges) Assigned() bool {
	return c.fields.ID.Assigned() || c.fields.Scope.Assigned() || c.fields.FamilyID.Assigned() || c.fields.Generation.Assigned() || c.fields.AccessHash.Assigned() || c.fields.RefreshHash.Assigned() || c.fields.IssuedAt.Assigned() || c.fields.LastSeenAt.Assigned() || c.fields.AccessExpiresAt.Assigned() || c.fields.RefreshExpiresAt.Assigned()
}

// Changed reports whether any persisted field is changed.
func (c EntryChanges) Changed() bool {
	return c.fields.ID.Changed() || c.fields.Scope.Changed() || c.fields.FamilyID.Changed() || c.fields.Generation.Changed() || c.fields.AccessHash.Changed() || c.fields.RefreshHash.Changed() || c.fields.IssuedAt.Changed() || c.fields.LastSeenAt.Changed() || c.fields.AccessExpiresAt.Changed() || c.fields.RefreshExpiresAt.Changed()
}

// String and GoString keep model snapshots out of routine diagnostics.
func (EntryChanges) String() string     { return "Entry changes" }
func (c EntryChanges) GoString() string { return c.String() }

// CompareEntry is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func CompareEntry(before, after foundryvalue.Optional[Entry], assigned EntryDraft) (EntryChanges, error) {
	before = foundryEntrySnapshot(before)
	after = foundryEntrySnapshot(after)
	var changes EntryChanges
	var err error
	changes.fields.ID, err = lifecycle.CompareModelField(codec.ID[Entry](), before, after, assigned.fieldID.IsSet(), func(item Entry) model.ID[Entry] { return item.ID })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.ID: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.ID.Changed() || changes.fields.ID.Assigned()) {
		return EntryChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.Scope, err = lifecycle.CompareModelField(codec.String[string](), before, after, assigned.fieldScope.IsSet(), func(item Entry) string { return item.Scope })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.Scope: %w", err)
	}
	changes.fields.FamilyID, err = lifecycle.CompareModelField(codec.ID[Family](), before, after, assigned.fieldFamilyID.IsSet(), func(item Entry) model.ID[Family] { return item.FamilyID })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.FamilyID: %w", err)
	}
	changes.fields.Generation, err = lifecycle.CompareModelField(codec.Unsigned[uint32](), before, after, assigned.fieldGeneration.IsSet(), func(item Entry) uint32 { return item.Generation })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.Generation: %w", err)
	}
	changes.fields.AccessHash, err = lifecycle.CompareModelField(codec.String[string](), before, after, assigned.fieldAccessHash.IsSet(), func(item Entry) string { return item.AccessHash })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.AccessHash: %w", err)
	}
	changes.fields.RefreshHash, err = lifecycle.CompareModelField(codec.Nullable(codec.String[string]()), before, after, assigned.fieldRefreshHash.IsSet(), func(item Entry) foundryvalue.Nullable[string] { return item.RefreshHash })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.RefreshHash: %w", err)
	}
	changes.fields.IssuedAt, err = lifecycle.CompareModelField(codec.DateTime(), before, after, assigned.fieldIssuedAt.IsSet(), func(item Entry) temporal.DateTime { return item.IssuedAt })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.IssuedAt: %w", err)
	}
	changes.fields.LastSeenAt, err = lifecycle.CompareModelField(codec.DateTime(), before, after, assigned.fieldLastSeenAt.IsSet(), func(item Entry) temporal.DateTime { return item.LastSeenAt })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.LastSeenAt: %w", err)
	}
	changes.fields.AccessExpiresAt, err = lifecycle.CompareModelField(codec.DateTime(), before, after, assigned.fieldAccessExpiresAt.IsSet(), func(item Entry) temporal.DateTime { return item.AccessExpiresAt })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.AccessExpiresAt: %w", err)
	}
	changes.fields.RefreshExpiresAt, err = lifecycle.CompareModelField(codec.Nullable(codec.DateTime()), before, after, assigned.fieldRefreshExpiresAt.IsSet(), func(item Entry) foundryvalue.Nullable[temporal.DateTime] { return item.RefreshExpiresAt })
	if err != nil {
		return EntryChanges{}, fmt.Errorf("compare Entry.RefreshExpiresAt: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryEntrySnapshot(snapshot foundryvalue.Optional[Entry]) foundryvalue.Optional[Entry] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[Entry]{}
	}
	return foundryvalue.Set(Entry{
		ID:               item.ID,
		Scope:            item.Scope,
		FamilyID:         item.FamilyID,
		Generation:       item.Generation,
		AccessHash:       item.AccessHash,
		RefreshHash:      item.RefreshHash,
		IssuedAt:         item.IssuedAt,
		LastSeenAt:       item.LastSeenAt,
		AccessExpiresAt:  item.AccessExpiresAt,
		RefreshExpiresAt: item.RefreshExpiresAt,
	})
}

// EntryHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type EntryHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[Entry], *EntryDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *EntryDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, Entry, *EntryDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, Entry) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, Entry) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, Entry) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, EntryChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, EntryChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, EntryChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, EntryChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, EntryChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, EntryChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, EntryChanges) error
}

// EntryObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type EntryObserver = lifecycle.Observer[Entry, EntryHooks]

// NewEntryObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewEntryObserver(observer string) EntryObserver {
	return lifecycle.NewObserver[Entry, EntryHooks](observer)
}

// RegisterEntryObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterEntryObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer EntryObserver, construct func(foundation.Resolver) (func() EntryHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (EntryHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[Entry], error) {
	factories, err := lifecycle.ObserverFactories[Entry, EntryHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[Entry]{}, err
	}
	var allHooks []EntryHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Entry]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[Entry]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Entry]{}, err
	}
	return foundryquery.WriteHooks[Entry]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[Entry], mutation foundryquery.Mutation[Entry]) (foundryquery.Mutation[Entry], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			var draft EntryDraft
			draft.fieldID, err = foundryquery.MutationValue[Entry, model.ID[Entry]](values, "foundry_token_generations", "id")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldScope, err = foundryquery.MutationValue[Entry, string](values, "foundry_token_generations", "scope")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldFamilyID, err = foundryquery.MutationValue[Entry, model.ID[Family]](values, "foundry_token_generations", "family_id")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldGeneration, err = foundryquery.MutationValue[Entry, uint32](values, "foundry_token_generations", "generation")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldAccessHash, err = foundryquery.MutationValue[Entry, string](values, "foundry_token_generations", "access_hash")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldRefreshHash, err = foundryquery.MutationValue[Entry, foundryvalue.Nullable[string]](values, "foundry_token_generations", "refresh_hash")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldIssuedAt, err = foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "issued_at")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldLastSeenAt, err = foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "last_seen_at")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldAccessExpiresAt, err = foundryquery.MutationValue[Entry, temporal.DateTime](values, "foundry_token_generations", "access_expires_at")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			draft.fieldRefreshExpiresAt, err = foundryquery.MutationValue[Entry, foundryvalue.Nullable[temporal.DateTime]](values, "foundry_token_generations", "refresh_expires_at")
			if err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[Entry]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Entry]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Entry]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[Entry]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[Entry]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Entry]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Entry]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Entry]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Entry]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Entry]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[Entry]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[Entry], mutation foundryquery.Mutation[Entry]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft EntryDraft
			if values.Has("foundry_token_generations", "id") {
				var zero model.ID[Entry]
				draft.fieldID = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "scope") {
				var zero string
				draft.fieldScope = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "family_id") {
				var zero model.ID[Family]
				draft.fieldFamilyID = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "generation") {
				var zero uint32
				draft.fieldGeneration = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "access_hash") {
				var zero string
				draft.fieldAccessHash = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "refresh_hash") {
				var zero foundryvalue.Nullable[string]
				draft.fieldRefreshHash = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "issued_at") {
				var zero temporal.DateTime
				draft.fieldIssuedAt = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "last_seen_at") {
				var zero temporal.DateTime
				draft.fieldLastSeenAt = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "access_expires_at") {
				var zero temporal.DateTime
				draft.fieldAccessExpiresAt = foundryvalue.Set(zero)
			}
			if values.Has("foundry_token_generations", "refresh_expires_at") {
				var zero foundryvalue.Nullable[temporal.DateTime]
				draft.fieldRefreshExpiresAt = foundryvalue.Set(zero)
			}
			changes, err := CompareEntry(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// EntryRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type EntryRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, Entry) error
}

// EntryRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type EntryRetrievalObserver = lifecycle.Observer[Entry, EntryRetrievalHooks]

// NewEntryRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewEntryRetrievalObserver(observer string) EntryRetrievalObserver {
	return lifecycle.NewRetrievalObserver[Entry, EntryRetrievalHooks](observer)
}

// RegisterEntryRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterEntryRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer EntryRetrievalObserver, construct func(foundation.Resolver) (func() EntryRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (EntryRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[Entry], error) {
	factories, err := lifecycle.RetrievalObserverFactories[Entry, EntryRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[Entry]{}, err
	}
	var allHooks []EntryRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Entry]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[Entry]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Entry]{}, err
	}
	return foundryquery.RetrievalHooks[Entry]{Retrieved: func(ctx context.Context, executor database.Executor, item Entry) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// EntryAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type EntryAuditPolicy struct {
	_ [0]*Entry
	// ID controls the audit representation of stored foundry_token_generations.id.
	ID record.Disclosure
	// Scope controls the audit representation of stored foundry_token_generations.scope.
	Scope record.Disclosure
	// FamilyID controls the audit representation of stored foundry_token_generations.family_id.
	FamilyID record.Disclosure
	// Generation controls the audit representation of stored foundry_token_generations.generation.
	Generation record.Disclosure
	// AccessHash controls the audit representation of stored foundry_token_generations.access_hash.
	AccessHash record.Disclosure
	// RefreshHash controls the audit representation of stored foundry_token_generations.refresh_hash.
	RefreshHash record.Disclosure
	// IssuedAt controls the audit representation of stored foundry_token_generations.issued_at.
	IssuedAt record.Disclosure
	// LastSeenAt controls the audit representation of stored foundry_token_generations.last_seen_at.
	LastSeenAt record.Disclosure
	// AccessExpiresAt controls the audit representation of stored foundry_token_generations.access_expires_at.
	AccessExpiresAt record.Disclosure
	// RefreshExpiresAt controls the audit representation of stored foundry_token_generations.refresh_expires_at.
	RefreshExpiresAt record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes EntryChanges) Audit(policy EntryAuditPolicy) (record.Model[Entry, model.ID[Entry]], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[Entry, model.ID[Entry]]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[Entry, model.ID[Entry]]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "id", policy.ID)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	var captured record.Field[Entry]
	captured, err = record.CaptureField[Entry]("id", codec.ID[Entry](), changes.fields.ID, policy.ID)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("scope", codec.String[string](), changes.fields.Scope, policy.Scope)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("family_id", codec.ID[Family](), changes.fields.FamilyID, policy.FamilyID)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("generation", codec.Unsigned[uint32](), changes.fields.Generation, policy.Generation)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("access_hash", codec.String[string](), changes.fields.AccessHash, policy.AccessHash)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("refresh_hash", codec.Nullable(codec.String[string]()), changes.fields.RefreshHash, policy.RefreshHash)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("issued_at", codec.DateTime(), changes.fields.IssuedAt, policy.IssuedAt)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("last_seen_at", codec.DateTime(), changes.fields.LastSeenAt, policy.LastSeenAt)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("access_expires_at", codec.DateTime(), changes.fields.AccessExpiresAt, policy.AccessExpiresAt)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	captured, err = record.CaptureField[Entry]("refresh_expires_at", codec.Nullable(codec.DateTime()), changes.fields.RefreshExpiresAt, policy.RefreshExpiresAt)
	if err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Entry, model.ID[Entry]]{}, err
	}
	return builder.Build()
}

// EntryAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type EntryAuditFieldSet struct {
	_ [0]*Entry
	// ID retains stored foundry_token_generations.id after write mutators; read accessors do not replace audit values.
	ID foundryvalue.Optional[record.FieldChange[model.ID[Entry]]]
	// Scope retains stored foundry_token_generations.scope after write mutators; read accessors do not replace audit values.
	Scope foundryvalue.Optional[record.FieldChange[string]]
	// FamilyID retains stored foundry_token_generations.family_id after write mutators; read accessors do not replace audit values.
	FamilyID foundryvalue.Optional[record.FieldChange[model.ID[Family]]]
	// Generation retains stored foundry_token_generations.generation after write mutators; read accessors do not replace audit values.
	Generation foundryvalue.Optional[record.FieldChange[uint32]]
	// AccessHash retains stored foundry_token_generations.access_hash after write mutators; read accessors do not replace audit values.
	AccessHash foundryvalue.Optional[record.FieldChange[string]]
	// RefreshHash retains stored foundry_token_generations.refresh_hash after write mutators; read accessors do not replace audit values.
	RefreshHash foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[string]]]
	// IssuedAt retains stored foundry_token_generations.issued_at after write mutators; read accessors do not replace audit values.
	IssuedAt foundryvalue.Optional[record.FieldChange[temporal.DateTime]]
	// LastSeenAt retains stored foundry_token_generations.last_seen_at after write mutators; read accessors do not replace audit values.
	LastSeenAt foundryvalue.Optional[record.FieldChange[temporal.DateTime]]
	// AccessExpiresAt retains stored foundry_token_generations.access_expires_at after write mutators; read accessors do not replace audit values.
	AccessExpiresAt foundryvalue.Optional[record.FieldChange[temporal.DateTime]]
	// RefreshExpiresAt retains stored foundry_token_generations.refresh_expires_at after write mutators; read accessors do not replace audit values.
	RefreshExpiresAt foundryvalue.Optional[record.FieldChange[foundryvalue.Nullable[temporal.DateTime]]]
}

// EntryAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func EntryAuditFields(history record.Model[Entry, model.ID[Entry]]) (EntryAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	var fields EntryAuditFieldSet
	fields.ID, err = record.ReadField(view, "id", codec.ID[Entry]())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.Scope, err = record.ReadField(view, "scope", codec.String[string]())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.FamilyID, err = record.ReadField(view, "family_id", codec.ID[Family]())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.Generation, err = record.ReadField(view, "generation", codec.Unsigned[uint32]())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.AccessHash, err = record.ReadField(view, "access_hash", codec.String[string]())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.RefreshHash, err = record.ReadField(view, "refresh_hash", codec.Nullable(codec.String[string]()))
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.IssuedAt, err = record.ReadField(view, "issued_at", codec.DateTime())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.LastSeenAt, err = record.ReadField(view, "last_seen_at", codec.DateTime())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.AccessExpiresAt, err = record.ReadField(view, "access_expires_at", codec.DateTime())
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	fields.RefreshExpiresAt, err = record.ReadField(view, "refresh_expires_at", codec.Nullable(codec.DateTime()))
	if err != nil {
		return EntryAuditFieldSet{}, err
	}
	return fields, nil
}

// EntryAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func EntryAuditing(policy EntryAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[Entry]()
		if err != nil {
			return err
		}
		return RegisterEntryObserver(registrar, pool, NewEntryObserver(name), func(resolver foundation.Resolver) (func() EntryHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() EntryHooks {
				write := func(ctx context.Context, tx *database.Tx, changes EntryChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return EntryHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
