// Code generated by foundry generate; DO NOT EDIT.
// Source: manager.go.

package datatable

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	i18n "github.com/weiloon1234/Foundry-Go/i18n"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
	sync "sync"
)

// PresentationJSON describes the concrete Presentation JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func PresentationJSON() foundrycontract.JSON[Presentation] { return foundryPresentationJSON() }

var foundryPresentationJSON = sync.OnceValue(func() foundrycontract.JSON[Presentation] {
	return foundrycontract.DefineJSON[Presentation](foundrycontract.Schema{Root: "github.com/weiloon1234/Foundry-Go/datatable.Presentation", Types: []foundrycontract.Type{
		{ID: "github.com/weiloon1234/Foundry-Go/datatable.Presentation", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "locale", Type: "github.com/weiloon1234/Foundry-Go/i18n.LocaleID", Required: true},
				{Name: "time_zone", Type: "string", Required: true},
			},
		},
		{ID: "github.com/weiloon1234/Foundry-Go/i18n.LocaleID", Kind: foundrycontract.Kind("string"), Nullable: false},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
})

// PresentationValidationFieldSet retains concrete DTO and value types for validation.
type PresentationValidationFieldSet struct {
	// Locale validates the declared JSON property "locale".
	Locale foundryvalidation.Field[Presentation, i18n.LocaleID]
	// TimeZone validates the declared JSON property "time_zone".
	TimeZone foundryvalidation.Field[Presentation, string]
}

// PresentationValidationFields returns typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func PresentationValidationFields() PresentationValidationFieldSet {
	return foundryPresentationValidationFields()
}

var foundryPresentationValidationFields = sync.OnceValue(func() PresentationValidationFieldSet {
	return PresentationValidationFieldSet{
		Locale: foundryvalidation.DefineField("locale", func(input Presentation) i18n.LocaleID {
			return input.Locale
		}),
		TimeZone: foundryvalidation.DefineField("time_zone", func(input Presentation) string {
			return input.TimeZone
		}),
	}
})
