// Code generated by foundry generate; DO NOT EDIT.
// Source: request.go:48.

package datatable

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
)

// SortJSON describes the concrete Sort JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func SortJSON() foundrycontract.JSON[Sort] {
	return foundrycontract.DefineJSON[Sort](foundrycontract.Schema{Root: "github.com/weiloon1234/Foundry-Go/datatable.Sort", Types: []foundrycontract.Type{
		foundrycontract.EnumType("github.com/weiloon1234/Foundry-Go/datatable.Direction", Direction("").EnumDescriptor()),
		{ID: "github.com/weiloon1234/Foundry-Go/datatable.Sort", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "column", Type: "string", Required: true},
				{Name: "direction", Type: "github.com/weiloon1234/Foundry-Go/datatable.Direction", Required: true},
			},
		},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
}

// SortValidationFieldSet retains concrete DTO and value types for validation.
type SortValidationFieldSet struct {
	// Column validates the declared JSON property "column".
	Column foundryvalidation.Field[Sort, string]
	// Direction validates the declared JSON property "direction".
	Direction foundryvalidation.Field[Sort, Direction]
}

// SortValidationFields returns independent typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func SortValidationFields() SortValidationFieldSet {
	return SortValidationFieldSet{
		Column: foundryvalidation.DefineField("column", func(input Sort) string {
			return input.Column
		}),
		Direction: foundryvalidation.DefineField("direction", func(input Sort) Direction {
			return input.Direction
		}),
	}
}
