// Code generated by foundry generate; DO NOT EDIT.
// Source: rule_routes.go:14.

package teamworkflow

import (
	foundryhttp "github.com/weiloon1234/Foundry-Go/http"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
)

// MultipartInputDescriptor binds multipart parts to concrete MultipartInput fields.
// Files are request-owned; Optional preserves omission and slices retain part order.
// Structured JSON parts use explicit contracts; models are not transport DTOs.
func MultipartInputDescriptor() foundryhttp.Multipart[MultipartInput] {
	return foundryhttp.DefineMultipart[MultipartInput](
		foundryhttp.TextPart(foundryhttp.QueryParam[MultipartInput, string]("name", foundryhttp.URLType("string", foundryhttp.StringQuery[string]()), func(form *MultipartInput) *string { return &form.Name })),
	)
}

// MultipartInputValidationFieldSet retains concrete DTO and value types for validation.
type MultipartInputValidationFieldSet struct {
	// Name validates the declared multipart part "name".
	Name foundryvalidation.Field[MultipartInput, string]
}

// MultipartInputValidationFields returns independent typed field descriptors.
// Compose rules with these fields; multipart names and selectors are generated.
func MultipartInputValidationFields() MultipartInputValidationFieldSet {
	return MultipartInputValidationFieldSet{
		Name: foundryvalidation.DefineField("name", func(input MultipartInput) string {
			return input.Name
		}),
	}
}
