// Code generated by foundry generate; DO NOT EDIT.
// Source: contracts.go:36.

package teamworkflow

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
)

// SubmissionInputJSON describes the concrete SubmissionInput JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func SubmissionInputJSON() foundrycontract.JSON[SubmissionInput] {
	return foundrycontract.DefineJSON[SubmissionInput](foundrycontract.Schema{Root: "foundry.test/consumer/teamworkflow.SubmissionInput", Types: []foundrycontract.Type{
		{ID: "bool", Kind: foundrycontract.Kind("boolean"), Nullable: false},
		{ID: "foundry.test/consumer/teamworkflow.SubmissionInput", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "name", Type: "string", Required: true},
				{Name: "reject", Type: "bool", Required: false},
			},
		},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
}

// SubmissionInputValidationFieldSet retains concrete DTO and value types for validation.
type SubmissionInputValidationFieldSet struct {
	// Name validates the declared JSON property "name".
	Name foundryvalidation.Field[SubmissionInput, string]
	// Reject validates the declared JSON property "reject".
	Reject foundryvalidation.Field[SubmissionInput, bool]
}

// SubmissionInputValidationFields returns independent typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func SubmissionInputValidationFields() SubmissionInputValidationFieldSet {
	return SubmissionInputValidationFieldSet{
		Name: foundryvalidation.DefineField("name", func(input SubmissionInput) string {
			return input.Name
		}),
		Reject: foundryvalidation.DefineField("reject", func(input SubmissionInput) bool {
			return input.Reject
		}),
	}
}
