// Code generated by foundry generate; DO NOT EDIT.
// Source: pagination.go.

package httppagination

import (
	foundryhttp "github.com/weiloon1234/Foundry-Go/http"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
	sync "sync"
)

// MemberFiltersDescriptor binds query parameters to concrete MemberFilters fields.
// Reuse this descriptor for request decoding and query URL encoding.
// Optional fields preserve omission; repeated fields retain slice order.
func MemberFiltersDescriptor() foundryhttp.Query[MemberFilters] {
	return foundryMemberFiltersDescriptor()
}

var foundryMemberFiltersDescriptor = sync.OnceValue(func() foundryhttp.Query[MemberFilters] {
	return foundryhttp.DefineQuery[MemberFilters](
		foundryhttp.OptionalQueryParam[MemberFilters, string]("email", foundryhttp.URLType("string", foundryhttp.StringQuery[string]()), func(query *MemberFilters) *foundryvalue.Optional[string] { return &query.Email }),
	)
})
