// Code generated by foundry generate; DO NOT EDIT.
// Source: messages.go.

package localization

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	message "github.com/weiloon1234/Foundry-Go/i18n/message"
	sync "sync"
)

// NameLabelJSON describes the concrete NameLabel JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func NameLabelJSON() foundrycontract.JSON[NameLabel] { return foundryNameLabelJSON() }

var foundryNameLabelJSON = sync.OnceValue(func() foundrycontract.JSON[NameLabel] {
	return foundrycontract.DefineJSON[NameLabel](foundrycontract.Schema{Root: "foundry.test/consumer/localization.NameLabel", Types: []foundrycontract.Type{
		{ID: "foundry.test/consumer/localization.NameLabel", Kind: foundrycontract.Kind("object"), Nullable: false},
	}})
})

// NameLabelValidationFieldSet retains concrete DTO and value types for validation.
type NameLabelValidationFieldSet struct {
}

// NameLabelValidationFields returns typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func NameLabelValidationFields() NameLabelValidationFieldSet {
	return foundryNameLabelValidationFields()
}

var foundryNameLabelValidationFields = sync.OnceValue(func() NameLabelValidationFieldSet {
	return NameLabelValidationFieldSet{}
})

// NameLabelMessage retains this declaration's exact argument type and shared JSON contract.
func NameLabelMessage() message.Message[NameLabel] { return foundryNameLabelMessage() }

var foundryNameLabelMessage = sync.OnceValue(func() message.Message[NameLabel] {
	return message.Define("fields.name", NameLabelJSON(), message.Options{Plural: "", Kind: ""})
})
