// Code generated by foundry generate; DO NOT EDIT.
// Source: models.go:28.

package intervalqueries

import (
	context "context"
	fmt "fmt"
	record "github.com/weiloon1234/Foundry-Go/audit/record"
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	lifecycle "github.com/weiloon1234/Foundry-Go/database/lifecycle"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	relation "github.com/weiloon1234/Foundry-Go/database/relation"
	foundryfault "github.com/weiloon1234/Foundry-Go/fault"
	foundation "github.com/weiloon1234/Foundry-Go/foundation"
	model "github.com/weiloon1234/Foundry-Go/model"
	temporal "github.com/weiloon1234/Foundry-Go/temporal"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
)

// PlanFieldSet exposes fields owned by the unaliased model.
type PlanFieldSet = PlanScopedFieldSet[Plan]

// PlanFields returns independent immutable field descriptors.
func PlanFields() PlanFieldSet {
	return PlanFieldsAt(foundryquery.DeclareModelScope[Plan]("interval_plans"))
}

// PlanScopedFieldSet preserves typed field operators in a declared query scope.
type PlanScopedFieldSet[FoundryScope any] struct {
	// ID describes interval_plans.id.
	ID foundryquery.ExactField[FoundryScope, int]
	// Period describes interval_plans.period.
	Period foundryquery.IntervalField[FoundryScope, temporal.Interval]
}

// PlanFieldsAt binds these record fields to an alias or joined scope.
func PlanFieldsAt[FoundryScope any](scope foundryquery.ModelScope[FoundryScope, Plan]) PlanScopedFieldSet[FoundryScope] {
	return PlanScopedFieldSet[FoundryScope]{
		ID:     foundryquery.NewExactField[FoundryScope, int](scope.Table(), "id", codec.Signed[int]()),
		Period: foundryquery.NewIntervalField[FoundryScope, temporal.Interval](scope.Table(), "period", codec.Interval()),
	}
}

// PlanNullableFieldSet preserves typed field operators in a declared query scope.
type PlanNullableFieldSet[FoundryScope any] struct {
	// ID describes interval_plans.id.
	ID foundryquery.NullableExactField[FoundryScope, int]
	// Period describes interval_plans.period.
	Period foundryquery.NullableIntervalField[FoundryScope, temporal.Interval]
}

// PlanNullableFieldsAt binds these record fields to an alias or joined scope.
func PlanNullableFieldsAt[FoundryScope any](scope foundryquery.NullableModelScope[FoundryScope, Plan]) PlanNullableFieldSet[FoundryScope] {
	return PlanNullableFieldSet[FoundryScope]{
		ID:     foundryquery.NewNullableExactField[FoundryScope, int](scope.Table(), "id", codec.Signed[int]()),
		Period: foundryquery.NewNullableIntervalField[FoundryScope, temporal.Interval](scope.Table(), "period", codec.Interval()),
	}
}

// PlanQuery preserves model-specific keys through fluent query derivation.
type PlanQuery struct{ foundryquery.Query[Plan] }

// QueryIntervalPlans starts a complete-model query for interval_plans with generated hydration.
func QueryIntervalPlans() PlanQuery {
	return PlanQuery{foundryquery.ForModel(foundryquery.Define[Plan]("interval_plans", "id", []foundryquery.Column{foundryquery.Column{Name: "id", Nullable: false, DatabaseDefault: false}, foundryquery.Column{Name: "period", Nullable: false, DatabaseDefault: false}}, func(row database.Row) (Plan, error) {
		var item Plan
		if err := row.Scan(
			codec.Signed[int]().Scan(&item.ID),
			codec.Interval().Scan(&item.Period),
		); err != nil {
			return Plan{}, err
		}
		return item, nil
	},
		foundryquery.NewModelField("id", codec.Signed[int](), func(item Plan) int { return item.ID }),
		foundryquery.NewModelField("period", codec.Interval(), func(item Plan) temporal.Interval { return item.Period }),
	).WithObserverHooks((PlanHooks{}).foundryWriteHooks, false).WithRetrievalHooks((PlanRetrievalHooks{}).foundryRetrievalHooks, false))}
}

// FoundryQuery returns this model's generated metadata query for framework integrations.
func (Plan) FoundryQuery() foundryquery.Query[Plan] { return QueryIntervalPlans().Query }

// FoundryReference retains Plan and its concrete stored primary key for framework integrations.
// It reads ID directly, never calls an accessor, and performs no database lookup.
func (m Plan) FoundryReference() model.Reference[Plan, int] {
	return model.NewReference[Plan]("interval_plans", m.ID, codec.Signed[int]())
}

// FoundryIdentity snapshots only the stored model name and primary key for attribution and audit.
// This explicit serialization boundary does not establish authentication or authorization.
func (m Plan) FoundryIdentity() (model.Identity, error) { return m.FoundryReference().Identity() }

// WithTrashed derives a new Plan query without changing its source.
func (q PlanQuery) WithTrashed() PlanQuery { q.Query = q.Query.WithTrashed(); return q }

// OnlyTrashed derives a new Plan query without changing its source.
func (q PlanQuery) OnlyTrashed() PlanQuery { q.Query = q.Query.OnlyTrashed(); return q }

// WithoutTrashed derives a new Plan query without changing its source.
func (q PlanQuery) WithoutTrashed() PlanQuery { q.Query = q.Query.WithoutTrashed(); return q }

// Where derives a new Plan query without changing its source.
func (q PlanQuery) Where(predicates ...foundryquery.Predicate[Plan]) PlanQuery {
	q.Query = q.Query.Where(predicates...)
	return q
}

// WhereHas derives a new Plan query without changing its source.
func (q PlanQuery) WhereHas(relation foundryquery.ExistenceRelation[Plan]) PlanQuery {
	q.Query = q.Query.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a new Plan query without changing its source.
func (q PlanQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Plan]) PlanQuery {
	q.Query = q.Query.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a new Plan query without changing its source.
func (q PlanQuery) OrderBy(orders ...foundryquery.Order[Plan]) PlanQuery {
	q.Query = q.Query.OrderBy(orders...)
	return q
}

// Limit derives a new Plan query without changing its source.
func (q PlanQuery) Limit(count int) PlanQuery { q.Query = q.Query.Limit(count); return q }

// Offset derives a new Plan query without changing its source.
func (q PlanQuery) Offset(count int) PlanQuery { q.Query = q.Query.Offset(count); return q }

// With derives a new Plan query without changing its source.
func (q PlanQuery) With(relations ...foundryquery.Relation[Plan]) PlanQuery {
	q.Query = q.Query.With(relations...)
	return q
}

// WithRelationLimits derives a new Plan query without changing its source.
func (q PlanQuery) WithRelationLimits(limits foundryquery.RelationLimits) PlanQuery {
	q.Query = q.Query.WithRelationLimits(limits)
	return q
}

// Find applies a typed primary key to this query, preserving filters and pagination.
func (q PlanQuery) Find(ctx context.Context, executor database.Executor, key int) (foundryvalue.Optional[Plan], error) {
	return q.Where(PlanFields().ID.Eq(key)).First(ctx, executor)
}

// RequireFind reports database.NotFound when the typed key does not match this query.
func (q PlanQuery) RequireFind(ctx context.Context, executor database.Executor, key int) (Plan, error) {
	return q.Where(PlanFields().ID.Eq(key)).RequireFirst(ctx, executor)
}

// PlanLockedQuery preserves typed keys while requiring transaction-scoped reads.
type PlanLockedQuery struct{ foundryquery.LockedQuery[Plan] }

// ForUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q PlanQuery) ForUpdate() PlanLockedQuery { return PlanLockedQuery{q.Query.ForUpdate()} }

// ForNoKeyUpdate derives a transaction-scoped row-locking query; locks last until transaction end.
func (q PlanQuery) ForNoKeyUpdate() PlanLockedQuery { return PlanLockedQuery{q.Query.ForNoKeyUpdate()} }

// ForShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q PlanQuery) ForShare() PlanLockedQuery { return PlanLockedQuery{q.Query.ForShare()} }

// ForKeyShare derives a transaction-scoped row-locking query; locks last until transaction end.
func (q PlanQuery) ForKeyShare() PlanLockedQuery { return PlanLockedQuery{q.Query.ForKeyShare()} }

// WithTrashed derives a locked Plan query without changing its source.
func (q PlanLockedQuery) WithTrashed() PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.WithTrashed()
	return q
}

// OnlyTrashed derives a locked Plan query without changing its source.
func (q PlanLockedQuery) OnlyTrashed() PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.OnlyTrashed()
	return q
}

// WithoutTrashed derives a locked Plan query without changing its source.
func (q PlanLockedQuery) WithoutTrashed() PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.WithoutTrashed()
	return q
}

// Where derives a locked Plan query without changing its source.
func (q PlanLockedQuery) Where(predicates ...foundryquery.Predicate[Plan]) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.Where(predicates...)
	return q
}

// WhereHas derives a locked Plan query without changing its source.
func (q PlanLockedQuery) WhereHas(relation foundryquery.ExistenceRelation[Plan]) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereHas(relation)
	return q
}

// WhereDoesntHave derives a locked Plan query without changing its source.
func (q PlanLockedQuery) WhereDoesntHave(relation foundryquery.ExistenceRelation[Plan]) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.WhereDoesntHave(relation)
	return q
}

// OrderBy derives a locked Plan query without changing its source.
func (q PlanLockedQuery) OrderBy(orders ...foundryquery.Order[Plan]) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.OrderBy(orders...)
	return q
}

// Limit derives a locked Plan query without changing its source.
func (q PlanLockedQuery) Limit(count int) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.Limit(count)
	return q
}

// Offset derives a locked Plan query without changing its source.
func (q PlanLockedQuery) Offset(count int) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.Offset(count)
	return q
}

// With derives a locked Plan query without changing its source.
func (q PlanLockedQuery) With(relations ...foundryquery.Relation[Plan]) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.With(relations...)
	return q
}

// WithRelationLimits derives a locked Plan query without changing its source.
func (q PlanLockedQuery) WithRelationLimits(limits foundryquery.RelationLimits) PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.WithRelationLimits(limits)
	return q
}

// NoWait derives a locked Plan query without changing its source.
func (q PlanLockedQuery) NoWait() PlanLockedQuery { q.LockedQuery = q.LockedQuery.NoWait(); return q }

// SkipLocked derives a locked Plan query without changing its source.
func (q PlanLockedQuery) SkipLocked() PlanLockedQuery {
	q.LockedQuery = q.LockedQuery.SkipLocked()
	return q
}

// Wait derives a locked Plan query without changing its source.
func (q PlanLockedQuery) Wait() PlanLockedQuery { q.LockedQuery = q.LockedQuery.Wait(); return q }

// Find locks a model selected by its typed primary key, preserving filters and pagination.
func (q PlanLockedQuery) Find(ctx context.Context, tx *database.Tx, key int) (foundryvalue.Optional[Plan], error) {
	return q.Where(PlanFields().ID.Eq(key)).First(ctx, tx)
}

// RequireFind reports database.NotFound when no model can be selected and locked.
func (q PlanLockedQuery) RequireFind(ctx context.Context, tx *database.Tx, key int) (Plan, error) {
	return q.Where(PlanFields().ID.Eq(key)).RequireFirst(ctx, tx)
}

// Create inserts a complete model from explicit draft fields. Omitted UUID primary keys are generated unless the database owns their default or a distinct mutation input is required.
func (q PlanQuery) Create(ctx context.Context, writer database.Transactor, draft PlanDraft) (Plan, error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return Plan{}, err
	}
	return q.Query.Insert(ctx, writer, mutation)
}

// Upsert inserts or applies an explicit typed conflict policy. Skipped conflicts return an omitted result; database constraints still apply.
func (q PlanQuery) Upsert(ctx context.Context, writer database.Transactor, draft PlanDraft, conflict foundryquery.Conflict[Plan]) (foundryvalue.Optional[Plan], error) {
	mutation, err := draft.foundryMutation(true)
	if err != nil {
		return foundryvalue.Optional[Plan]{}, err
	}
	return q.Query.InsertOnConflict(ctx, writer, mutation, conflict)
}

// CreateMany inserts a bounded batch atomically. A valid empty batch performs no database work. This is a set-based write.
func (q PlanQuery) CreateMany(ctx context.Context, writer database.Transactor, drafts []PlanDraft) ([]Plan, error) {
	return q.foundryInsertMany(ctx, writer, drafts, nil)
}

// UpsertMany applies one typed conflict policy to a bounded atomic batch. Skipped conflicts have no returned model; result order is not an input-row mapping.
func (q PlanQuery) UpsertMany(ctx context.Context, writer database.Transactor, drafts []PlanDraft, conflict foundryquery.Conflict[Plan]) ([]Plan, error) {
	return q.foundryInsertMany(ctx, writer, drafts, &conflict)
}
func (q PlanQuery) foundryInsertMany(ctx context.Context, writer database.Transactor, drafts []PlanDraft, conflict *foundryquery.Conflict[Plan]) ([]Plan, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	if conflict == nil {
		return q.Query.InsertMany(ctx, writer, mutations)
	}
	return q.Query.InsertManyOnConflict(ctx, writer, mutations, *conflict)
}
func (q PlanQuery) foundryCreateMutations(drafts []PlanDraft) ([]foundryquery.Mutation[Plan], error) {
	if len(drafts) > foundryquery.MaxInsertRows {
		return nil, foundryfault.New(foundryfault.Invalid, "model insert exceeds its row bound")
	}
	mutations := make([]foundryquery.Mutation[Plan], len(drafts))
	for i, draft := range drafts {
		m, err := draft.foundryMutation(true)
		if err != nil {
			return nil, err
		}
		mutations[i] = m
	}
	return mutations, nil
}

// Update patches one typed primary key within this query's filters. Omitted fields stay unchanged; primary-key mutation is rejected.
func (q PlanQuery) Update(ctx context.Context, writer database.Transactor, key int, draft PlanDraft) (Plan, error) {
	mutation, err := draft.foundryMutation(false)
	if err != nil {
		return Plan{}, err
	}
	return q.Where(PlanFields().ID.Eq(key)).Query.Patch(ctx, writer, mutation)
}

// Delete removes one typed primary key within this query's filters and returns its complete pre-deletion model.
func (q PlanQuery) Delete(ctx context.Context, writer database.Transactor, key int) (Plan, error) {
	return q.Where(PlanFields().ID.Eq(key)).Query.Remove(ctx, writer)
}

// CreateEach creates each input through normal model hooks and mutators inside one bounded atomic operation. Results preserve input order; CreateMany has separate set-based semantics.
func (q PlanQuery) CreateEach(ctx context.Context, writer database.Transactor, drafts []PlanDraft) ([]Plan, error) {
	mutations, err := q.foundryCreateMutations(drafts)
	if err != nil {
		return nil, err
	}
	return q.Query.InsertEach(ctx, writer, mutations)
}

// UpdateEach derives a concrete draft for each locked model and runs its normal lifecycle. The complete matching set must fit limit before any callback. Results follow primary-key order and all selected writes are atomic; read ordering, pagination and eager-loading options are rejected.
func (q PlanQuery) UpdateEach(ctx context.Context, writer database.Transactor, limit int, draft func(context.Context, *database.Tx, Plan) (PlanDraft, error)) ([]Plan, error) {
	var callback func(context.Context, *database.Tx, Plan) (foundryquery.Mutation[Plan], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Plan) (foundryquery.Mutation[Plan], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchEach(ctx, writer, limit, callback)
}

// DeleteEach deletes each selected active model through normal lifecycle behavior. Soft-delete models remain stored; other models are physically removed. The positive limit bounds the complete atomic candidate set before hooks run.
func (q PlanQuery) DeleteEach(ctx context.Context, writer database.Transactor, limit int) ([]Plan, error) {
	return q.Query.RemoveEach(ctx, writer, limit)
}

// FirstOrCreate returns the first primary-ordered matching model or creates one through its normal lifecycle. The draft is prepared only when no model matches; the stored creation must satisfy the query. Internal lookup skips Retrieved. Concurrent absence relies on database unique constraints and reports ordinary conflicts without hidden retries.
func (q PlanQuery) FirstOrCreate(ctx context.Context, writer database.Transactor, create PlanDraft) (Plan, error) {
	return q.Query.FirstOrInsert(ctx, writer, create)
}

// UpdateOrCreate runs a concrete draft callback for the first primary-ordered matching model or creates from the separate creation draft. Only the chosen branch prepares its draft; ordinary lifecycle and transaction ownership remain in force. Read ordering, pagination and eager-loading options are rejected.
func (q PlanQuery) UpdateOrCreate(ctx context.Context, writer database.Transactor, create PlanDraft, draft func(context.Context, *database.Tx, Plan) (PlanDraft, error)) (Plan, error) {
	var callback func(context.Context, *database.Tx, Plan) (foundryquery.Mutation[Plan], error)
	if draft != nil {
		callback = func(ctx context.Context, tx *database.Tx, current Plan) (foundryquery.Mutation[Plan], error) {
			d, err := draft(ctx, tx, current)
			if err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			return d.foundryMutation(false)
		}
	}
	return q.Query.PatchOrInsert(ctx, writer, create, callback)
}

// PlanInsertFromBuilder selects stored SQL values into Plan through a typed source scope.
// This is a set-based write without per-model observers. Values uses ordinary draft setters.
// Columns with Go mutators have no Select method; use their literal draft inputs instead.
type PlanInsertFromBuilder[FoundryScope any] struct {
	plan foundryquery.InsertSelect[FoundryScope, Plan]
	err  error
}

// Format omits captured source parameters and literal draft inputs from diagnostics.
func (p PlanInsertFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// InsertPlanFrom starts a typed INSERT SELECT. Omitted columns retain database defaults or NULL.
// UUID primary keys require a typed source value or a declared database default; no per-row Go IDs are generated.
func InsertPlanFrom[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) PlanInsertFromBuilder[FoundryScope] {
	return PlanInsertFromBuilder[FoundryScope]{plan: foundryquery.InsertFrom(source, (Plan{}).FoundryQuery())}
}

// SelectID supplies the stored SQL value for id. It cannot also be supplied by Values.
func (p PlanInsertFromBuilder[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, int]) PlanInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(PlanFields().ID, v))
	return p
}

// SelectPeriod supplies the stored SQL value for period. It cannot also be supplied by Values.
func (p PlanInsertFromBuilder[FoundryScope]) SelectPeriod(v foundryquery.Expression[FoundryScope, temporal.Interval]) PlanInsertFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapInsert(PlanFields().Period, v))
	return p
}

// Values replaces literal draft inputs for every selected row, normalizing them once inside the transaction.
func (p PlanInsertFromBuilder[FoundryScope]) Values(draft PlanDraft) PlanInsertFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec inserts the selected window and returns an affected row count without collecting models.
func (p PlanInsertFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete models; excess returned rows roll back the entire write.
// The bound limits retained models, not SQL work or field sizes. It never truncates the source; result order is not source order.
func (p PlanInsertFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Plan, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// PlanUpdateFromBuilder performs a typed set-based source write without per-model observers.
// SQL value mappings require one source match per affected model; ambiguity rolls back.
// Literal draft inputs retain normal setters and timestamps; SQL selectors cannot bypass them.
type PlanUpdateFromBuilder[FoundryScope any] struct {
	plan foundryquery.UpdateSource[FoundryScope, Plan]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p PlanUpdateFromBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// UpdatePlanFrom preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func UpdatePlanFrom[FoundryScope any](destination PlanQuery, source foundryquery.ProjectionSource[FoundryScope]) PlanUpdateFromBuilder[FoundryScope] {
	return PlanUpdateFromBuilder[FoundryScope]{plan: foundryquery.UpdateFrom(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p PlanUpdateFromBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, int]) PlanUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(PlanFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p PlanUpdateFromBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[int]]) PlanUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(PlanFields().ID, v))
	return p
}

// SelectPeriod assigns a stored source value to period; Values cannot also supply it.
func (p PlanUpdateFromBuilder[FoundryScope]) SelectPeriod(v foundryquery.Expression[FoundryScope, temporal.Interval]) PlanUpdateFromBuilder[FoundryScope] {
	p.plan = p.plan.Select(foundryquery.MapUpdate(PlanFields().Period, v))
	return p
}

// Values replaces literal inputs for every affected model, normalized once inside the transaction.
// Primary keys cannot be changed. Fixed-value updates allow repeated source matches.
func (p PlanUpdateFromBuilder[FoundryScope]) Values(draft PlanDraft) PlanUpdateFromBuilder[FoundryScope] {
	mutation, err := draft.foundryMutation(false)
	p.err = err
	p.plan = p.plan.Values(mutation)
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p PlanUpdateFromBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p PlanUpdateFromBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Plan, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// PlanDeleteUsingBuilder performs a typed set-based source write without per-model observers.
// Ordinary deletion honors soft deletion; repeated source keys affect each destination once.
type PlanDeleteUsingBuilder[FoundryScope any] struct {
	plan foundryquery.DeleteSource[FoundryScope, Plan]
	err  error
}

// Format omits captured source parameters and draft inputs.
func (p PlanDeleteUsingBuilder[FoundryScope]) Format(state fmt.State, verb rune) {
	p.plan.Format(state, verb)
}

// DeletePlanUsing preserves destination filters and the source's explicitly selected window.
// Call MatchID to connect the source identity to this model's primary key.
func DeletePlanUsing[FoundryScope any](destination PlanQuery, source foundryquery.ProjectionSource[FoundryScope]) PlanDeleteUsingBuilder[FoundryScope] {
	return PlanDeleteUsingBuilder[FoundryScope]{plan: foundryquery.DeleteUsing(destination, source)}
}

// MatchID replaces the stored source value matched to id; it never assigns the key.
func (p PlanDeleteUsingBuilder[FoundryScope]) MatchID(v foundryquery.Expression[FoundryScope, int]) PlanDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchSource(PlanFields().ID, v))
	return p
}

// MatchNullableID accepts a nullable source key, such as an outer join. NULL matches nothing.
func (p PlanDeleteUsingBuilder[FoundryScope]) MatchNullableID(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[int]]) PlanDeleteUsingBuilder[FoundryScope] {
	p.plan = p.plan.Match(foundryquery.MatchNullableSource(PlanFields().ID, v))
	return p
}

// Exec returns the number of affected destination models without collecting them.
func (p PlanDeleteUsingBuilder[FoundryScope]) Exec(ctx context.Context, writer database.Transactor) (int64, error) {
	if p.err != nil {
		return 0, p.err
	}
	return p.plan.Exec(ctx, writer)
}

// Returning collects at most limit complete affected models; excess returned rows roll back the write.
// The bound limits retained models, not SQL work or field sizes; it never truncates the source or promises result order.
func (p PlanDeleteUsingBuilder[FoundryScope]) Returning(ctx context.Context, writer database.Transactor, limit int) ([]Plan, error) {
	if p.err != nil {
		return nil, p.err
	}
	return p.plan.Returning(ctx, writer, limit)
}

// FoundryCreateMutation supplies the typed draft adapter for framework integrations. Defaults fill omitted fields before UUID preparation; no mutators or database calls run here.
func (d PlanDraft) FoundryCreateMutation(defaults foundryquery.Mutation[Plan]) (foundryquery.Mutation[Plan], error) {
	values, err := foundryquery.ReadCreateDefaults((Plan{}).FoundryQuery(), defaults)
	if err != nil {
		return foundryquery.Mutation[Plan]{}, err
	}
	if !d.fieldID.IsSet() {
		v, err := foundryquery.MutationValue[Plan, int](values, "interval_plans", "id")
		if err != nil {
			return foundryquery.Mutation[Plan]{}, err
		}
		d.fieldID = v
	}
	if !d.fieldPeriod.IsSet() {
		v, err := foundryquery.MutationValue[Plan, temporal.Interval](values, "interval_plans", "period")
		if err != nil {
			return foundryquery.Mutation[Plan]{}, err
		}
		d.fieldPeriod = v
	}
	return d.foundryMutation(true)
}
func (d PlanDraft) foundryMutation(create bool) (foundryquery.Mutation[Plan], error) {
	var assignments []foundryquery.Assignment[Plan]
	if v, set := d.fieldID.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Plan]("interval_plans", "id", codec.Signed[int](), v))
	}
	if v, set := d.fieldPeriod.Get(); set {
		assignments = append(assignments, foundryquery.Assign[Plan]("interval_plans", "period", codec.Interval(), v))
	}
	return foundryquery.Change(assignments...), nil
}

// PlanRelationSet requires typed descriptors matching every declared relation slot.
type PlanRelationSet struct {
	Samples foundryquery.ManyRelation[Plan, Sample]
	Labels  foundryquery.ThroughRelation[Plan, Label, Link]
}

// PlanRelations binds handwritten key declarations to generated model metadata and typed slots.
func PlanRelations() PlanRelationSet {
	relations := (Plan{}).DefineRelations()
	relations.Samples = relations.Samples.Bind("Samples", QueryIntervalPlans().Query, (Sample{}).FoundryQuery(), func(m Plan) relation.Many[Sample] { return m.Samples }, func(m Plan, loaded relation.Many[Sample]) Plan { m.Samples = loaded; return m })
	relations.Labels = relations.Labels.Bind("Labels", QueryIntervalPlans().Query, (Label{}).FoundryQuery(), (Link{}).FoundryQuery(), func(m Plan) relation.Through[Label, Link] { return m.Labels }, func(m Plan, loaded relation.Through[Label, Link]) Plan { m.Labels = loaded; return m })
	return relations
}

// PlanAggregateSet checks the source model and result type of every computed slot.
type PlanAggregateSet struct {
	SampleCount foundryquery.AggregateRelation[Plan, int64]
	TotalPeriod foundryquery.AggregateRelation[Plan, foundryvalue.Nullable[temporal.Interval]]
}

// PlanAggregates binds handwritten computations to generated typed result slots.
func PlanAggregates() PlanAggregateSet {
	aggregates := (Plan{}).DefineAggregates()
	aggregates.SampleCount = aggregates.SampleCount.Bind("SampleCount", QueryIntervalPlans().Query, func(m Plan) relation.Value[int64] { return m.SampleCount }, func(m Plan, computed relation.Value[int64]) Plan { m.SampleCount = computed; return m })
	aggregates.TotalPeriod = aggregates.TotalPeriod.Bind("TotalPeriod", QueryIntervalPlans().Query, func(m Plan) relation.Value[foundryvalue.Nullable[temporal.Interval]] { return m.TotalPeriod }, func(m Plan, computed relation.Value[foundryvalue.Nullable[temporal.Interval]]) Plan {
		m.TotalPeriod = computed
		return m
	})
	return aggregates
}

// PlanDraft tracks explicitly selected mutation fields, preserving omitted, zero and null states.
type PlanDraft struct {
	fieldID     foundryvalue.Optional[int]
	fieldPeriod foundryvalue.Optional[temporal.Interval]
}

// ID returns the typed mutation state for id.
func (d PlanDraft) ID() foundryvalue.Optional[int] { return d.fieldID }

// SetID returns a new draft with id explicitly set.
func (d PlanDraft) SetID(v int) PlanDraft { d.fieldID = foundryvalue.Set(v); return d }

// UnsetID omits id without requesting a zero or null write.
func (d PlanDraft) UnsetID() PlanDraft { d.fieldID = foundryvalue.Optional[int]{}; return d }

// Period returns the typed mutation state for period.
func (d PlanDraft) Period() foundryvalue.Optional[temporal.Interval] { return d.fieldPeriod }

// SetPeriod returns a new draft with period explicitly set.
func (d PlanDraft) SetPeriod(v temporal.Interval) PlanDraft {
	d.fieldPeriod = foundryvalue.Set(v)
	return d
}

// UnsetPeriod omits period without requesting a zero or null write.
func (d PlanDraft) UnsetPeriod() PlanDraft {
	d.fieldPeriod = foundryvalue.Optional[temporal.Interval]{}
	return d
}

// IsEmpty reports whether no fields have been selected for mutation.
func (d PlanDraft) IsEmpty() bool { return !d.fieldID.IsSet() && !d.fieldPeriod.IsSet() }

// Format omits pending draft values, including sensitive mutation inputs, from routine diagnostics.
func (PlanDraft) Format(state fmt.State, _ rune) { _, _ = state.Write([]byte("Plan draft")) }

// PlanFieldChanges contains typed changes for persisted fields only.
type PlanFieldChanges struct {
	// ID retains the typed change for id.
	ID lifecycle.FieldChange[int]
	// Period retains the typed change for period.
	Period lifecycle.FieldChange[temporal.Interval]
}

// PlanChanges contains immutable persisted snapshots and field changes. Relation loads and ignored fields are excluded.
type PlanChanges struct {
	before, after foundryvalue.Optional[Plan]
	fields        PlanFieldChanges
	operation     foundryvalue.Optional[lifecycle.Operation]
}

// Operation identifies an automatically captured lifecycle write. Standalone Compare results have no operation.
func (c PlanChanges) Operation() foundryvalue.Optional[lifecycle.Operation] { return c.operation }

// Before returns the persisted model before the operation, or absence for creation.
func (c PlanChanges) Before() foundryvalue.Optional[Plan] { return c.before }

// After returns the persisted model after the operation, or absence for physical deletion. Soft deletion retains its stored result.
func (c PlanChanges) After() foundryvalue.Optional[Plan] { return c.after }

// Fields returns model-specific field changes by value.
func (c PlanChanges) Fields() PlanFieldChanges { return c.fields }

// Assigned reports whether any persisted field is assigned.
func (c PlanChanges) Assigned() bool { return c.fields.ID.Assigned() || c.fields.Period.Assigned() }

// Changed reports whether any persisted field is changed.
func (c PlanChanges) Changed() bool { return c.fields.ID.Changed() || c.fields.Period.Changed() }

// String and GoString keep model snapshots out of routine diagnostics.
func (PlanChanges) String() string     { return "Plan changes" }
func (c PlanChanges) GoString() string { return c.String() }

// ComparePlan is the generated lifecycle comparison boundary. Pass stored snapshots and the effective assignment draft; its values are not transformed or compared to the result. Both snapshots, when present, must have the same primary key. This function performs no database work or automatic capture.
func ComparePlan(before, after foundryvalue.Optional[Plan], assigned PlanDraft) (PlanChanges, error) {
	before = foundryPlanSnapshot(before)
	after = foundryPlanSnapshot(after)
	var changes PlanChanges
	var err error
	changes.fields.ID, err = lifecycle.CompareModelField(codec.Signed[int](), before, after, assigned.fieldID.IsSet(), func(item Plan) int { return item.ID })
	if err != nil {
		return PlanChanges{}, fmt.Errorf("compare Plan.ID: %w", err)
	}
	if before.IsSet() && after.IsSet() && (changes.fields.ID.Changed() || changes.fields.ID.Assigned()) {
		return PlanChanges{}, foundryfault.New(foundryfault.Invalid, "model change cannot replace or assign its existing primary key")
	}
	changes.fields.Period, err = lifecycle.CompareModelField(codec.Interval(), before, after, assigned.fieldPeriod.IsSet(), func(item Plan) temporal.Interval { return item.Period })
	if err != nil {
		return PlanChanges{}, fmt.Errorf("compare Plan.Period: %w", err)
	}
	changes.before = before
	changes.after = after
	return changes, nil
}
func foundryPlanSnapshot(snapshot foundryvalue.Optional[Plan]) foundryvalue.Optional[Plan] {
	item, present := snapshot.Get()
	if !present {
		return foundryvalue.Optional[Plan]{}
	}
	return foundryvalue.Set(Plan{
		ID:     item.ID,
		Period: item.Period,
	})
}

// PlanHooks declares typed normal-write callbacks. Reference a factory with hooks=Factory on the model directive. Callbacks run synchronously; do not retain draft or transaction pointers. Nil callbacks are skipped.
type PlanHooks struct {
	// Saving runs before Creating or Updating and may change assigned fields.
	Saving func(context.Context, *database.Tx, foundryvalue.Optional[Plan], *PlanDraft) error
	// Creating runs before insert mutators; omitted required fields may be supplied here.
	Creating func(context.Context, *database.Tx, *PlanDraft) error
	// Updating receives the locked stored model before the write.
	Updating func(context.Context, *database.Tx, Plan, *PlanDraft) error
	// Deleting receives the locked stored model before soft or physical deletion.
	Deleting func(context.Context, *database.Tx, Plan) error
	// Restoring receives the locked stored model before its special lifecycle write.
	Restoring func(context.Context, *database.Tx, Plan) error
	// ForceDeleting receives the locked stored model before its special lifecycle write.
	ForceDeleting func(context.Context, *database.Tx, Plan) error
	// Created runs after SQL inside the transaction; returning an error rolls back the write.
	Created func(context.Context, *database.Tx, PlanChanges) error
	// Updated runs after SQL inside the transaction; returning an error rolls back the write.
	Updated func(context.Context, *database.Tx, PlanChanges) error
	// Deleted runs after SQL inside the transaction; returning an error rolls back the write.
	Deleted func(context.Context, *database.Tx, PlanChanges) error
	// Saved runs after SQL inside the transaction; returning an error rolls back the write.
	Saved func(context.Context, *database.Tx, PlanChanges) error
	// Restored runs after SQL inside the transaction; returning an error rolls back the write.
	Restored func(context.Context, *database.Tx, PlanChanges) error
	// ForceDeleted runs after SQL inside the transaction; returning an error rolls back the write.
	ForceDeleted func(context.Context, *database.Tx, PlanChanges) error
	// AfterCommit runs only after the outer transaction commits. Failures cannot roll back committed data; this callback is not crash durable.
	AfterCommit func(context.Context, lifecycle.Operation, PlanChanges) error
}

// PlanObserver retains this model's concrete hook factory type. Names are unique within the selected database.
type PlanObserver = lifecycle.Observer[Plan, PlanHooks]

// NewPlanObserver declares a reusable typed observer identifier without registering or constructing hooks.
func NewPlanObserver(observer string) PlanObserver {
	return lifecycle.NewObserver[Plan, PlanHooks](observer)
}

// RegisterPlanObserver binds dependency construction to a database module. Its returned factory runs once per normal write; reads and set-based writes skip it.
func RegisterPlanObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer PlanObserver, construct func(foundation.Resolver) (func() PlanHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (PlanHooks) foundryWriteHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.WriteHooks[Plan], error) {
	factories, err := lifecycle.ObserverFactories[Plan, PlanHooks](observerSet)
	if err != nil {
		return foundryquery.WriteHooks[Plan]{}, err
	}
	var allHooks []PlanHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Plan]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.WriteHooks[Plan]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.WriteHooks[Plan]{}, err
	}
	return foundryquery.WriteHooks[Plan]{
		Before: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before foundryvalue.Optional[Plan], mutation foundryquery.Mutation[Plan]) (foundryquery.Mutation[Plan], error) {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			var draft PlanDraft
			draft.fieldID, err = foundryquery.MutationValue[Plan, int](values, "interval_plans", "id")
			if err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			draft.fieldPeriod, err = foundryquery.MutationValue[Plan, temporal.Interval](values, "interval_plans", "period")
			if err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			if err := ctx.Err(); err != nil {
				return foundryquery.Mutation[Plan]{}, err
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saving != nil {
						if err := hooks.Saving(ctx, tx, before, &draft); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Plan]{}, err
					}
				}
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Creating != nil {
						if err := hooks.Creating(ctx, tx, &draft); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
					if err := ctx.Err(); err != nil {
						return foundryquery.Mutation[Plan]{}, err
					}
				}
			case lifecycle.Update, lifecycle.Delete, lifecycle.SoftDelete, lifecycle.Restore, lifecycle.ForceDelete:
				current, present := before.Get()
				if !present {
					return foundryquery.Mutation[Plan]{}, foundryfault.New(foundryfault.Invalid, "model hook requires a stored snapshot")
				}
				switch operation {
				case lifecycle.Update:
					for _, hooks := range allHooks {
						if hooks.Updating != nil {
							if err := hooks.Updating(ctx, tx, current, &draft); err != nil {
								return foundryquery.Mutation[Plan]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
				case lifecycle.Delete, lifecycle.SoftDelete:
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Plan]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
				case lifecycle.Restore:
					for _, hooks := range allHooks {
						if hooks.Restoring != nil {
							if err := hooks.Restoring(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Plan]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
				case lifecycle.ForceDelete:
					for _, hooks := range allHooks {
						if hooks.ForceDeleting != nil {
							if err := hooks.ForceDeleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Plan]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
					for _, hooks := range allHooks {
						if hooks.Deleting != nil {
							if err := hooks.Deleting(ctx, tx, current); err != nil {
								return foundryquery.Mutation[Plan]{}, err
							}
						}
						if err := ctx.Err(); err != nil {
							return foundryquery.Mutation[Plan]{}, err
						}
					}
				}
			default:
				return foundryquery.Mutation[Plan]{}, foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			return draft.foundryMutation(false)
		},
		After: func(ctx context.Context, tx *database.Tx, operation lifecycle.Operation, before, after foundryvalue.Optional[Plan], mutation foundryquery.Mutation[Plan]) error {
			values, err := foundryquery.ReadMutation(mutation)
			if err != nil {
				return err
			}
			var draft PlanDraft
			if values.Has("interval_plans", "id") {
				var zero int
				draft.fieldID = foundryvalue.Set(zero)
			}
			if values.Has("interval_plans", "period") {
				var zero temporal.Interval
				draft.fieldPeriod = foundryvalue.Set(zero)
			}
			changes, err := ComparePlan(before, after, draft)
			if err != nil {
				return err
			}
			changes.operation = foundryvalue.Set(operation)
			if err := ctx.Err(); err != nil {
				return err
			}
			switch operation {
			case lifecycle.Create:
				for _, hooks := range allHooks {
					if hooks.Created != nil {
						if err := hooks.Created(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Update:
				for _, hooks := range allHooks {
					if hooks.Updated != nil {
						if err := hooks.Updated(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Delete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.SoftDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.Restore:
				for _, hooks := range allHooks {
					if hooks.Restored != nil {
						if err := hooks.Restored(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			case lifecycle.ForceDelete:
				for _, hooks := range allHooks {
					if hooks.Deleted != nil {
						if err := hooks.Deleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
				for _, hooks := range allHooks {
					if hooks.ForceDeleted != nil {
						if err := hooks.ForceDeleted(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			default:
				return foundryfault.New(foundryfault.Invalid, "invalid model hook operation")
			}
			if operation == lifecycle.Create || operation == lifecycle.Update {
				for _, hooks := range allHooks {
					if hooks.Saved != nil {
						if err := hooks.Saved(ctx, tx, changes); err != nil {
							return err
						}
					}
					if err := ctx.Err(); err != nil {
						return err
					}
				}
			}
			for _, hooks := range allHooks {
				if hooks.AfterCommit != nil {
					if err := tx.AfterCommit(func(ctx context.Context) error { return hooks.AfterCommit(ctx, operation, changes) }); err != nil {
						return err
					}
				}
			}
			return nil
		}}, nil
}

// PlanRetrievalHooks declares complete-model read callbacks. Reference a local factory with retrieval=Factory on the model directive. The stored model is a read-only value; getters remain explicit.
type PlanRetrievalHooks struct {
	// Retrieved runs after successful stored hydration and row closure. The executor retains the caller's capability and wrappers; no write transaction is created implicitly. Return an error to stop this read. Nil is skipped.
	Retrieved func(context.Context, database.Executor, Plan) error
}

// PlanRetrievalObserver retains this model's concrete retrieval factory type. Names share the selected database's write/retrieval namespace.
type PlanRetrievalObserver = lifecycle.Observer[Plan, PlanRetrievalHooks]

// NewPlanRetrievalObserver declares a typed retrieval observer without registering or constructing hooks.
func NewPlanRetrievalObserver(observer string) PlanRetrievalObserver {
	return lifecycle.NewRetrievalObserver[Plan, PlanRetrievalHooks](observer)
}

// RegisterPlanRetrievalObserver binds dependency construction to a database module. Its factory runs once per nonempty complete fetch/batch and selected model role; write hydration, DTOs and scalar reads skip it.
func RegisterPlanRetrievalObserver(registrar *foundation.Registrar, pool foundation.Key[*database.DB], observer PlanRetrievalObserver, construct func(foundation.Resolver) (func() PlanRetrievalHooks, error)) error {
	return database.RegisterObserver(registrar, pool, observer, construct)
}
func (PlanRetrievalHooks) foundryRetrievalHooks(ctx context.Context, observerSet lifecycle.Observers) (foundryquery.RetrievalHooks[Plan], error) {
	factories, err := lifecycle.RetrievalObserverFactories[Plan, PlanRetrievalHooks](observerSet)
	if err != nil {
		return foundryquery.RetrievalHooks[Plan]{}, err
	}
	var allHooks []PlanRetrievalHooks
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Plan]{}, err
	}
	for _, factory := range factories {
		if err := ctx.Err(); err != nil {
			return foundryquery.RetrievalHooks[Plan]{}, err
		}
		allHooks = append(allHooks, factory())
	}
	if err := ctx.Err(); err != nil {
		return foundryquery.RetrievalHooks[Plan]{}, err
	}
	return foundryquery.RetrievalHooks[Plan]{Retrieved: func(ctx context.Context, executor database.Executor, item Plan) error {
		for _, hooks := range allHooks {
			if err := ctx.Err(); err != nil {
				return err
			}
			if hooks.Retrieved != nil {
				if err := hooks.Retrieved(ctx, executor, item); err != nil {
					return err
				}
			}
		}
		return ctx.Err()
	}}, nil
}

// PlanAuditPolicy selects stored fields for auditing. Zero applies automatic sensitive-name redaction.
// Exclusion/redaction cannot hide the primary key while retaining it as the subject identity; that policy fails capture.
type PlanAuditPolicy struct {
	_ [0]*Plan
	// ID controls the audit representation of stored interval_plans.id.
	ID record.Disclosure
	// Period controls the audit representation of stored interval_plans.period.
	Period record.Disclosure
}

// Audit captures this operation's existing stored changes without getters, mutators or additional database work.
// Standalone Compare results have no captured operation and cannot become lifecycle audit records.
func (changes PlanChanges) Audit(policy PlanAuditPolicy) (record.Model[Plan, int], error) {
	operation, present := changes.operation.Get()
	if !present {
		return record.Model[Plan, int]{}, foundryfault.New(foundryfault.Missing, "audit requires captured model changes")
	}
	item, present := changes.after.Get()
	if !present {
		item, present = changes.before.Get()
	}
	if !present {
		return record.Model[Plan, int]{}, foundryfault.New(foundryfault.Missing, "audit requires a stored model snapshot")
	}
	builder, err := record.NewBuilder(item.FoundryReference(), operation, "id", policy.ID)
	if err != nil {
		return record.Model[Plan, int]{}, err
	}
	var captured record.Field[Plan]
	captured, err = record.CaptureField[Plan]("id", codec.Signed[int](), changes.fields.ID, policy.ID)
	if err != nil {
		return record.Model[Plan, int]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Plan, int]{}, err
	}
	captured, err = record.CaptureField[Plan]("period", codec.Interval(), changes.fields.Period, policy.Period)
	if err != nil {
		return record.Model[Plan, int]{}, err
	}
	if err = builder.Add(captured); err != nil {
		return record.Model[Plan, int]{}, err
	}
	return builder.Build()
}

// PlanAuditFieldSet contains typed historical fields. An omitted field differs from an absent model or SQL NULL.
type PlanAuditFieldSet struct {
	_ [0]*Plan
	// ID retains stored interval_plans.id after write mutators; read accessors do not replace audit values.
	ID foundryvalue.Optional[record.FieldChange[int]]
	// Period retains stored interval_plans.period after write mutators; read accessors do not replace audit values.
	Period foundryvalue.Optional[record.FieldChange[temporal.Interval]]
}

// PlanAuditFields reads model-owned history through its declared codecs, without populating a partial model.
// Get on a redacted field reports an explicit error; its Snapshot remains available for deliberate audit export.
func PlanAuditFields(history record.Model[Plan, int]) (PlanAuditFieldSet, error) {
	view, err := record.Inspect(history)
	if err != nil {
		return PlanAuditFieldSet{}, err
	}
	var fields PlanAuditFieldSet
	fields.ID, err = record.ReadField(view, "id", codec.Signed[int]())
	if err != nil {
		return PlanAuditFieldSet{}, err
	}
	fields.Period, err = record.ReadField(view, "period", codec.Interval())
	if err != nil {
		return PlanAuditFieldSet{}, err
	}
	return fields, nil
}

// PlanAuditing declares automatic auditing for normal lifecycle writes. Register it once through audit.Register.
// Existing observer registration owns dependency construction, duplicate detection and transaction lifetime.
func PlanAuditing(policy PlanAuditPolicy) record.Declaration {
	return record.Declare(func(registrar *foundation.Registrar, pool foundation.Key[*database.DB], resolve record.ResolveWriter) error {
		name, err := record.ObserverName[Plan]()
		if err != nil {
			return err
		}
		return RegisterPlanObserver(registrar, pool, NewPlanObserver(name), func(resolver foundation.Resolver) (func() PlanHooks, error) {
			writer, err := resolve(resolver)
			if err != nil {
				return nil, err
			}
			if writer == nil {
				return nil, foundryfault.New(foundryfault.Invalid, "audit writer is not initialized")
			}
			return func() PlanHooks {
				write := func(ctx context.Context, tx *database.Tx, changes PlanChanges) error {
					captured, err := changes.Audit(policy)
					if err != nil {
						return err
					}
					return writer.RecordModel(ctx, tx, captured.Entry())
				}
				return PlanHooks{Created: write, Updated: write, Deleted: write, Restored: write}
			}, nil
		})
	})
}
