// Code generated by foundry generate; DO NOT EDIT.
// Source: settings.go:33.

package infrastructure

import (
	cache "github.com/weiloon1234/Foundry-Go/cache"
	config "github.com/weiloon1234/Foundry-Go/config"
	database "github.com/weiloon1234/Foundry-Go/database"
	email "github.com/weiloon1234/Foundry-Go/email"
	httpclient "github.com/weiloon1234/Foundry-Go/httpclient"
	jobs "github.com/weiloon1234/Foundry-Go/jobs"
	pubsub "github.com/weiloon1234/Foundry-Go/pubsub"
	redis "github.com/weiloon1234/Foundry-Go/redis"
	storage "github.com/weiloon1234/Foundry-Go/storage"
	websocket "github.com/weiloon1234/Foundry-Go/websocket"
	time "time"
)

// SettingsConfigKeySet exposes compiler-checked configuration overrides.
type SettingsConfigKeySet struct {
	Namespace    SettingsNamespaceConfigKeySet
	Database     SettingsDatabaseConfigKeySet
	Redis        SettingsRedisConfigKeySet
	Storage      SettingsStorageConfigKeySet
	Cache        SettingsCacheConfigKeySet
	Mail         SettingsMailConfigKeySet
	Jobs         SettingsJobsConfigKeySet
	HTTPClients  SettingsHTTPClientsConfigKeySet
	PubSub       SettingsPubSubConfigKeySet
	Realtime     SettingsRealtimeConfigKeySet
	Coordination SettingsCoordinationConfigKeySet
	// Credentials selects credentials. Set accepts CredentialSources.
	Credentials config.Key[Settings, CredentialSources]
}

// SettingsNamespaceConfigKeySet exposes compiler-checked configuration overrides.
type SettingsNamespaceConfigKeySet struct {
	// Application selects namespace.application. Set accepts string.
	Application config.Key[Settings, string]
	// Environment selects namespace.environment. Set accepts string.
	Environment config.Key[Settings, string]
}

// SettingsDatabaseConfigKeySet exposes compiler-checked configuration overrides.
type SettingsDatabaseConfigKeySet struct {
	// Default selects database.default. Set accepts database.ConnectionName.
	Default config.Key[Settings, database.ConnectionName]
	// MaxConnections selects database.max_connections. Set accepts int.
	MaxConnections config.Key[Settings, int]
	// Connections selects database.connections. Set accepts DatabaseConnections.
	Connections config.Key[Settings, DatabaseConnections]
}

// SettingsRedisConfigKeySet exposes compiler-checked configuration overrides.
type SettingsRedisConfigKeySet struct {
	// Default selects redis.default. Set accepts redis.ConnectionName.
	Default config.Key[Settings, redis.ConnectionName]
	// MaxConnections selects redis.max_connections. Set accepts int.
	MaxConnections config.Key[Settings, int]
	// Connections selects redis.connections. Set accepts RedisConnections.
	Connections config.Key[Settings, RedisConnections]
}

// SettingsStorageConfigKeySet exposes compiler-checked configuration overrides.
type SettingsStorageConfigKeySet struct {
	// Default selects storage.default. Set accepts storage.DiskID.
	Default config.Key[Settings, storage.DiskID]
	// Disks selects storage.disks. Set accepts Disks.
	Disks config.Key[Settings, Disks]
}

// SettingsCacheConfigKeySet exposes compiler-checked configuration overrides.
type SettingsCacheConfigKeySet struct {
	// Default selects cache.default. Set accepts cache.StoreName.
	Default config.Key[Settings, cache.StoreName]
	// Stores selects cache.stores. Set accepts CacheStores.
	Stores config.Key[Settings, CacheStores]
}

// SettingsMailConfigKeySet exposes compiler-checked configuration overrides.
type SettingsMailConfigKeySet struct {
	// Default selects mail.default. Set accepts email.MailerName.
	Default config.Key[Settings, email.MailerName]
	// Mailers selects mail.mailers. Set accepts Mailers.
	Mailers config.Key[Settings, Mailers]
}

// SettingsJobsConfigKeySet exposes compiler-checked configuration overrides.
type SettingsJobsConfigKeySet struct {
	// Default selects jobs.default. Set accepts jobs.ConnectionName.
	Default config.Key[Settings, jobs.ConnectionName]
	// Connections selects jobs.connections. Set accepts JobConnections.
	Connections config.Key[Settings, JobConnections]
}

// SettingsHTTPClientsConfigKeySet exposes compiler-checked configuration overrides.
type SettingsHTTPClientsConfigKeySet struct {
	// Default selects http_clients.default. Set accepts httpclient.Name.
	Default config.Key[Settings, httpclient.Name]
	// Clients selects http_clients.clients. Set accepts HTTPClients.
	Clients config.Key[Settings, HTTPClients]
}

// SettingsPubSubConfigKeySet exposes compiler-checked configuration overrides.
type SettingsPubSubConfigKeySet struct {
	// Default selects pub_sub.default. Set accepts pubsub.ConnectionName.
	Default config.Key[Settings, pubsub.ConnectionName]
	// Connections selects pub_sub.connections. Set accepts Brokers.
	Connections config.Key[Settings, Brokers]
}

// SettingsRealtimeConfigKeySet exposes compiler-checked configuration overrides.
type SettingsRealtimeConfigKeySet struct {
	// Default selects realtime.default. Set accepts websocket.ConnectionName.
	Default config.Key[Settings, websocket.ConnectionName]
	// Connections selects realtime.connections. Set accepts RealtimeConnections.
	Connections config.Key[Settings, RealtimeConnections]
}

// SettingsCoordinationConfigKeySet exposes compiler-checked configuration overrides.
type SettingsCoordinationConfigKeySet struct {
	// Enabled selects coordination.enabled. Set accepts bool.
	Enabled config.Key[Settings, bool]
	// Driver selects coordination.driver. Set accepts CoordinationDriver.
	Driver config.Key[Settings, CoordinationDriver]
	// Redis selects coordination.redis. Set accepts redis.ConnectionName.
	Redis  config.Key[Settings, redis.ConnectionName]
	Config SettingsCoordinationConfigConfigKeySet
	// MaxEntries selects coordination.max_entries. Set accepts int.
	MaxEntries config.Key[Settings, int]
}

// SettingsCoordinationConfigConfigKeySet exposes compiler-checked configuration overrides.
type SettingsCoordinationConfigConfigKeySet struct {
	Namespace SettingsCoordinationConfigNamespaceConfigKeySet
	// MaxActive selects coordination.config.max_active. Set accepts int.
	MaxActive config.Key[Settings, int]
	// MaxDeclarations selects coordination.config.max_declarations. Set accepts int.
	MaxDeclarations config.Key[Settings, int]
	// MaxKeyBytes selects coordination.config.max_key_bytes. Set accepts int.
	MaxKeyBytes config.Key[Settings, int]
	// OperationTimeout selects coordination.config.operation_timeout. Set accepts time.Duration.
	OperationTimeout config.Key[Settings, time.Duration]
	// MaxWait selects coordination.config.max_wait. Set accepts time.Duration.
	MaxWait config.Key[Settings, time.Duration]
	// PollInterval selects coordination.config.poll_interval. Set accepts time.Duration.
	PollInterval config.Key[Settings, time.Duration]
}

// SettingsCoordinationConfigNamespaceConfigKeySet exposes compiler-checked configuration overrides.
type SettingsCoordinationConfigNamespaceConfigKeySet struct {
	// Application selects coordination.config.namespace.application. Set accepts string.
	Application config.Key[Settings, string]
	// Environment selects coordination.config.namespace.environment. Set accepts string.
	Environment config.Key[Settings, string]
}

// SettingsConfigKeys derives keys from the handwritten settings declaration.
func SettingsConfigKeys() SettingsConfigKeySet {
	return SettingsConfigKeySet{
		Namespace: SettingsNamespaceConfigKeySet{
			Application: config.Scalar[Settings, string]("namespace.application", func(settings *Settings) *string { return &settings.Namespace.Application }),
			Environment: config.Scalar[Settings, string]("namespace.environment", func(settings *Settings) *string { return &settings.Namespace.Environment }),
		},
		Database: SettingsDatabaseConfigKeySet{
			Default:        config.Scalar[Settings, database.ConnectionName]("database.default", func(settings *Settings) *database.ConnectionName { return &settings.Database.Default }),
			MaxConnections: config.Scalar[Settings, int]("database.max_connections", func(settings *Settings) *int { return &settings.Database.MaxConnections }),
			Connections:    config.Text[Settings, DatabaseConnections, *DatabaseConnections]("database.connections", func(settings *Settings) *DatabaseConnections { return &settings.Database.Connections }).Sensitive(),
		},
		Redis: SettingsRedisConfigKeySet{
			Default:        config.Scalar[Settings, redis.ConnectionName]("redis.default", func(settings *Settings) *redis.ConnectionName { return &settings.Redis.Default }),
			MaxConnections: config.Scalar[Settings, int]("redis.max_connections", func(settings *Settings) *int { return &settings.Redis.MaxConnections }),
			Connections:    config.Text[Settings, RedisConnections, *RedisConnections]("redis.connections", func(settings *Settings) *RedisConnections { return &settings.Redis.Connections }).Sensitive(),
		},
		Storage: SettingsStorageConfigKeySet{
			Default: config.Scalar[Settings, storage.DiskID]("storage.default", func(settings *Settings) *storage.DiskID { return &settings.Storage.Default }),
			Disks:   config.Text[Settings, Disks, *Disks]("storage.disks", func(settings *Settings) *Disks { return &settings.Storage.Disks }),
		},
		Cache: SettingsCacheConfigKeySet{
			Default: config.Scalar[Settings, cache.StoreName]("cache.default", func(settings *Settings) *cache.StoreName { return &settings.Cache.Default }),
			Stores:  config.Text[Settings, CacheStores, *CacheStores]("cache.stores", func(settings *Settings) *CacheStores { return &settings.Cache.Stores }),
		},
		Mail: SettingsMailConfigKeySet{
			Default: config.Scalar[Settings, email.MailerName]("mail.default", func(settings *Settings) *email.MailerName { return &settings.Mail.Default }),
			Mailers: config.Text[Settings, Mailers, *Mailers]("mail.mailers", func(settings *Settings) *Mailers { return &settings.Mail.Mailers }).Sensitive(),
		},
		Jobs: SettingsJobsConfigKeySet{
			Default:     config.Scalar[Settings, jobs.ConnectionName]("jobs.default", func(settings *Settings) *jobs.ConnectionName { return &settings.Jobs.Default }),
			Connections: config.Text[Settings, JobConnections, *JobConnections]("jobs.connections", func(settings *Settings) *JobConnections { return &settings.Jobs.Connections }),
		},
		HTTPClients: SettingsHTTPClientsConfigKeySet{
			Default: config.Scalar[Settings, httpclient.Name]("http_clients.default", func(settings *Settings) *httpclient.Name { return &settings.HTTPClients.Default }),
			Clients: config.Text[Settings, HTTPClients, *HTTPClients]("http_clients.clients", func(settings *Settings) *HTTPClients { return &settings.HTTPClients.Clients }).Sensitive(),
		},
		PubSub: SettingsPubSubConfigKeySet{
			Default:     config.Scalar[Settings, pubsub.ConnectionName]("pub_sub.default", func(settings *Settings) *pubsub.ConnectionName { return &settings.PubSub.Default }),
			Connections: config.Text[Settings, Brokers, *Brokers]("pub_sub.connections", func(settings *Settings) *Brokers { return &settings.PubSub.Connections }),
		},
		Realtime: SettingsRealtimeConfigKeySet{
			Default:     config.Scalar[Settings, websocket.ConnectionName]("realtime.default", func(settings *Settings) *websocket.ConnectionName { return &settings.Realtime.Default }),
			Connections: config.Text[Settings, RealtimeConnections, *RealtimeConnections]("realtime.connections", func(settings *Settings) *RealtimeConnections { return &settings.Realtime.Connections }),
		},
		Coordination: SettingsCoordinationConfigKeySet{
			Enabled: config.Scalar[Settings, bool]("coordination.enabled", func(settings *Settings) *bool { return &settings.Coordination.Enabled }),
			Driver:  config.Scalar[Settings, CoordinationDriver]("coordination.driver", func(settings *Settings) *CoordinationDriver { return &settings.Coordination.Driver }),
			Redis:   config.Scalar[Settings, redis.ConnectionName]("coordination.redis", func(settings *Settings) *redis.ConnectionName { return &settings.Coordination.Redis }),
			Config: SettingsCoordinationConfigConfigKeySet{
				Namespace: SettingsCoordinationConfigNamespaceConfigKeySet{
					Application: config.Scalar[Settings, string]("coordination.config.namespace.application", func(settings *Settings) *string { return &settings.Coordination.Config.Namespace.Application }),
					Environment: config.Scalar[Settings, string]("coordination.config.namespace.environment", func(settings *Settings) *string { return &settings.Coordination.Config.Namespace.Environment }),
				},
				MaxActive:        config.Scalar[Settings, int]("coordination.config.max_active", func(settings *Settings) *int { return &settings.Coordination.Config.MaxActive }),
				MaxDeclarations:  config.Scalar[Settings, int]("coordination.config.max_declarations", func(settings *Settings) *int { return &settings.Coordination.Config.MaxDeclarations }),
				MaxKeyBytes:      config.Scalar[Settings, int]("coordination.config.max_key_bytes", func(settings *Settings) *int { return &settings.Coordination.Config.MaxKeyBytes }),
				OperationTimeout: config.Duration[Settings]("coordination.config.operation_timeout", func(settings *Settings) *time.Duration { return &settings.Coordination.Config.OperationTimeout }),
				MaxWait:          config.Duration[Settings]("coordination.config.max_wait", func(settings *Settings) *time.Duration { return &settings.Coordination.Config.MaxWait }),
				PollInterval:     config.Duration[Settings]("coordination.config.poll_interval", func(settings *Settings) *time.Duration { return &settings.Coordination.Config.PollInterval }),
			},
			MaxEntries: config.Scalar[Settings, int]("coordination.max_entries", func(settings *Settings) *int { return &settings.Coordination.MaxEntries }),
		},
		Credentials: config.Text[Settings, CredentialSources, *CredentialSources]("credentials", func(settings *Settings) *CredentialSources { return &settings.Credentials }).Sensitive(),
	}
}

// SettingsConfigSchema reuses the shared file/environment/override loader.
func SettingsConfigSchema() (*config.Schema[Settings], error) {
	keys1 := SettingsConfigKeys()
	return config.New[Settings](
		keys1.Namespace.Application,
		keys1.Namespace.Environment,
		keys1.Database.Default,
		keys1.Database.MaxConnections,
		keys1.Database.Connections,
		keys1.Redis.Default,
		keys1.Redis.MaxConnections,
		keys1.Redis.Connections,
		keys1.Storage.Default,
		keys1.Storage.Disks,
		keys1.Cache.Default,
		keys1.Cache.Stores,
		keys1.Mail.Default,
		keys1.Mail.Mailers,
		keys1.Jobs.Default,
		keys1.Jobs.Connections,
		keys1.HTTPClients.Default,
		keys1.HTTPClients.Clients,
		keys1.PubSub.Default,
		keys1.PubSub.Connections,
		keys1.Realtime.Default,
		keys1.Realtime.Connections,
		keys1.Coordination.Enabled,
		keys1.Coordination.Driver,
		keys1.Coordination.Redis,
		keys1.Coordination.Config.Namespace.Application,
		keys1.Coordination.Config.Namespace.Environment,
		keys1.Coordination.Config.MaxActive,
		keys1.Coordination.Config.MaxDeclarations,
		keys1.Coordination.Config.MaxKeyBytes,
		keys1.Coordination.Config.OperationTimeout,
		keys1.Coordination.Config.MaxWait,
		keys1.Coordination.Config.PollInterval,
		keys1.Coordination.MaxEntries,
		keys1.Credentials,
	)
}
