// Code generated by foundry generate; DO NOT EDIT.
// Source: sample.go.

package scalarqueries

import (
	database "github.com/weiloon1234/Foundry-Go/database"
	codec "github.com/weiloon1234/Foundry-Go/database/codec"
	foundryquery "github.com/weiloon1234/Foundry-Go/database/query"
	decimal "github.com/weiloon1234/Foundry-Go/decimal"
	foundryvalue "github.com/weiloon1234/Foundry-Go/value"
)

// CalculationFieldSet exposes the declared result fields and their exact value types.
type CalculationFieldSet struct {
	ID            foundryquery.ProjectionField[Calculation, int]
	Caption       foundryquery.ProjectionField[Calculation, string]
	LineTotal     foundryquery.ProjectionField[Calculation, decimal.Decimal]
	AmountWithTax foundryquery.ProjectionField[Calculation, foundryvalue.Nullable[decimal.Decimal]]
}

// CalculationFields returns typed projection output declarations.
func CalculationFields() CalculationFieldSet {
	return CalculationFieldSet{
		ID:            foundryquery.NewProjectionField[Calculation, int]("id"),
		Caption:       foundryquery.NewProjectionField[Calculation, string]("caption"),
		LineTotal:     foundryquery.NewProjectionField[Calculation, decimal.Decimal]("line_total"),
		AmountWithTax: foundryquery.NewProjectionField[Calculation, foundryvalue.Nullable[decimal.Decimal]]("amount_with_tax"),
	}
}

// CalculationProjection provides the complete result schema and generated decoder.
func CalculationProjection() foundryquery.ProjectionDefinition[Calculation] {
	fields := CalculationFields()
	return foundryquery.DefineProjection([]foundryquery.ProjectionColumn[Calculation]{
		fields.ID.Column(),
		fields.Caption.Column(),
		fields.LineTotal.Column(),
		fields.AmountWithTax.Column(),
	}, func(row database.Row) (Calculation, error) {
		var item Calculation
		if err := row.Scan(
			codec.Signed[int]().Scan(&item.ID),
			codec.String[string]().Scan(&item.Caption),
			codec.Decimal().Scan(&item.LineTotal),
			codec.Nullable(codec.Decimal()).Scan(&item.AmountWithTax),
		); err != nil {
			return Calculation{}, err
		}
		return item, nil
	},
		foundryquery.NewRecordField("id", codec.Signed[int](), func(item Calculation) int { return item.ID }),
		foundryquery.NewRecordField("caption", codec.String[string](), func(item Calculation) string { return item.Caption }),
		foundryquery.NewRecordField("line_total", codec.Decimal(), func(item Calculation) decimal.Decimal { return item.LineTotal }),
		foundryquery.NewRecordField("amount_with_tax", codec.Nullable(codec.Decimal()), func(item Calculation) foundryvalue.Nullable[decimal.Decimal] { return item.AmountWithTax }),
	)
}

// CalculationSelection requires a type-compatible expression for every result field.
type CalculationSelection[FoundryScope any] struct {
	ID            foundryquery.Expression[FoundryScope, int]
	Caption       foundryquery.Expression[FoundryScope, string]
	LineTotal     foundryquery.Expression[FoundryScope, decimal.Decimal]
	AmountWithTax foundryquery.Expression[FoundryScope, foundryvalue.Nullable[decimal.Decimal]]
}

// SelectCalculation retains source ownership and exact result field types.
func SelectCalculation[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope], selection CalculationSelection[FoundryScope]) foundryquery.ProjectionQuery[FoundryScope, Calculation] {
	fields := CalculationFields()
	return foundryquery.Project(source, CalculationProjection(),
		foundryquery.Map(fields.ID, selection.ID),
		foundryquery.Map(fields.Caption, selection.Caption),
		foundryquery.Map(fields.LineTotal, selection.LineTotal),
		foundryquery.Map(fields.AmountWithTax, selection.AmountWithTax),
	)
}

// CalculationProject infers input ownership and selects typed result fields.
type CalculationProject[FoundryScope any] struct {
	source    foundryquery.ProjectionSource[FoundryScope]
	selection CalculationSelection[FoundryScope]
}

// ProjectCalculation starts a fluent projection selection without executing it.
func ProjectCalculation[FoundryScope any](source foundryquery.ProjectionSource[FoundryScope]) CalculationProject[FoundryScope] {
	return CalculationProject[FoundryScope]{source: source}
}

// SelectID supplies the typed expression for id.
func (p CalculationProject[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, int]) CalculationProject[FoundryScope] {
	p.selection.ID = v
	return p
}

// SelectCaption supplies the typed expression for caption.
func (p CalculationProject[FoundryScope]) SelectCaption(v foundryquery.Expression[FoundryScope, string]) CalculationProject[FoundryScope] {
	p.selection.Caption = v
	return p
}

// SelectLineTotal supplies the typed expression for line_total.
func (p CalculationProject[FoundryScope]) SelectLineTotal(v foundryquery.Expression[FoundryScope, decimal.Decimal]) CalculationProject[FoundryScope] {
	p.selection.LineTotal = v
	return p
}

// SelectAmountWithTax supplies the typed expression for amount_with_tax.
func (p CalculationProject[FoundryScope]) SelectAmountWithTax(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[decimal.Decimal]]) CalculationProject[FoundryScope] {
	p.selection.AmountWithTax = v
	return p
}

// Query retains the source requirements and complete selection mapping.
func (p CalculationProject[FoundryScope]) Query() foundryquery.ProjectionQuery[FoundryScope, Calculation] {
	return SelectCalculation(p.source, p.selection)
}

// SelectCorrelatedCalculation retains source ownership and exact result field types.
func SelectCorrelatedCalculation[FoundryOuter, FoundryInner any](source foundryquery.CorrelatedSource[FoundryOuter, FoundryInner], selection CalculationSelection[foundryquery.Correlation[FoundryOuter, FoundryInner]]) foundryquery.CorrelatedRecordQuery[FoundryOuter, FoundryInner, Calculation] {
	fields := CalculationFields()
	return foundryquery.ProjectCorrelated(source, CalculationProjection(),
		foundryquery.Map(fields.ID, selection.ID),
		foundryquery.Map(fields.Caption, selection.Caption),
		foundryquery.Map(fields.LineTotal, selection.LineTotal),
		foundryquery.Map(fields.AmountWithTax, selection.AmountWithTax),
	)
}

// CalculationCorrelatedProject infers input ownership and selects typed result fields.
type CalculationCorrelatedProject[FoundryOuter, FoundryInner any] struct {
	source    foundryquery.CorrelatedSource[FoundryOuter, FoundryInner]
	selection CalculationSelection[foundryquery.Correlation[FoundryOuter, FoundryInner]]
}

// ProjectCorrelatedCalculation starts a fluent projection selection without executing it.
func ProjectCorrelatedCalculation[FoundryOuter, FoundryInner any](source foundryquery.CorrelatedSource[FoundryOuter, FoundryInner]) CalculationCorrelatedProject[FoundryOuter, FoundryInner] {
	return CalculationCorrelatedProject[FoundryOuter, FoundryInner]{source: source}
}

// SelectID supplies the typed expression for id.
func (p CalculationCorrelatedProject[FoundryOuter, FoundryInner]) SelectID(v foundryquery.Expression[foundryquery.Correlation[FoundryOuter, FoundryInner], int]) CalculationCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.ID = v
	return p
}

// SelectCaption supplies the typed expression for caption.
func (p CalculationCorrelatedProject[FoundryOuter, FoundryInner]) SelectCaption(v foundryquery.Expression[foundryquery.Correlation[FoundryOuter, FoundryInner], string]) CalculationCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.Caption = v
	return p
}

// SelectLineTotal supplies the typed expression for line_total.
func (p CalculationCorrelatedProject[FoundryOuter, FoundryInner]) SelectLineTotal(v foundryquery.Expression[foundryquery.Correlation[FoundryOuter, FoundryInner], decimal.Decimal]) CalculationCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.LineTotal = v
	return p
}

// SelectAmountWithTax supplies the typed expression for amount_with_tax.
func (p CalculationCorrelatedProject[FoundryOuter, FoundryInner]) SelectAmountWithTax(v foundryquery.Expression[foundryquery.Correlation[FoundryOuter, FoundryInner], foundryvalue.Nullable[decimal.Decimal]]) CalculationCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.AmountWithTax = v
	return p
}

// Query retains the source requirements and complete selection mapping.
func (p CalculationCorrelatedProject[FoundryOuter, FoundryInner]) Query() foundryquery.CorrelatedRecordQuery[FoundryOuter, FoundryInner, Calculation] {
	return SelectCorrelatedCalculation(p.source, p.selection)
}

// SelectTransactionCalculation retains source ownership and exact result field types.
func SelectTransactionCalculation[FoundryScope foundryquery.TransactionScope](source foundryquery.TransactionProjectionSource[FoundryScope], selection CalculationSelection[FoundryScope]) foundryquery.TransactionQuery[FoundryScope, Calculation] {
	fields := CalculationFields()
	return foundryquery.ProjectTransaction(source, CalculationProjection(),
		foundryquery.Map(fields.ID, selection.ID),
		foundryquery.Map(fields.Caption, selection.Caption),
		foundryquery.Map(fields.LineTotal, selection.LineTotal),
		foundryquery.Map(fields.AmountWithTax, selection.AmountWithTax),
	)
}

// CalculationTransactionProject infers input ownership and selects typed result fields.
type CalculationTransactionProject[FoundryScope foundryquery.TransactionScope] struct {
	source    foundryquery.TransactionProjectionSource[FoundryScope]
	selection CalculationSelection[FoundryScope]
}

// ProjectTransactionCalculation starts a fluent projection selection without executing it.
func ProjectTransactionCalculation[FoundryScope foundryquery.TransactionScope](source foundryquery.TransactionProjectionSource[FoundryScope]) CalculationTransactionProject[FoundryScope] {
	return CalculationTransactionProject[FoundryScope]{source: source}
}

// SelectID supplies the typed expression for id.
func (p CalculationTransactionProject[FoundryScope]) SelectID(v foundryquery.Expression[FoundryScope, int]) CalculationTransactionProject[FoundryScope] {
	p.selection.ID = v
	return p
}

// SelectCaption supplies the typed expression for caption.
func (p CalculationTransactionProject[FoundryScope]) SelectCaption(v foundryquery.Expression[FoundryScope, string]) CalculationTransactionProject[FoundryScope] {
	p.selection.Caption = v
	return p
}

// SelectLineTotal supplies the typed expression for line_total.
func (p CalculationTransactionProject[FoundryScope]) SelectLineTotal(v foundryquery.Expression[FoundryScope, decimal.Decimal]) CalculationTransactionProject[FoundryScope] {
	p.selection.LineTotal = v
	return p
}

// SelectAmountWithTax supplies the typed expression for amount_with_tax.
func (p CalculationTransactionProject[FoundryScope]) SelectAmountWithTax(v foundryquery.Expression[FoundryScope, foundryvalue.Nullable[decimal.Decimal]]) CalculationTransactionProject[FoundryScope] {
	p.selection.AmountWithTax = v
	return p
}

// Query retains the source requirements and complete selection mapping.
func (p CalculationTransactionProject[FoundryScope]) Query() foundryquery.TransactionQuery[FoundryScope, Calculation] {
	return SelectTransactionCalculation(p.source, p.selection)
}

// SelectTransactionCorrelatedCalculation retains source ownership and exact result field types.
func SelectTransactionCorrelatedCalculation[FoundryOuter, FoundryInner foundryquery.TransactionScope](source foundryquery.TransactionCorrelatedSource[FoundryOuter, FoundryInner], selection CalculationSelection[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner]]) foundryquery.TransactionCorrelatedRecordQuery[FoundryOuter, FoundryInner, Calculation] {
	fields := CalculationFields()
	return foundryquery.ProjectTransactionCorrelated(source, CalculationProjection(),
		foundryquery.Map(fields.ID, selection.ID),
		foundryquery.Map(fields.Caption, selection.Caption),
		foundryquery.Map(fields.LineTotal, selection.LineTotal),
		foundryquery.Map(fields.AmountWithTax, selection.AmountWithTax),
	)
}

// CalculationTransactionCorrelatedProject infers input ownership and selects typed result fields.
type CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner foundryquery.TransactionScope] struct {
	source    foundryquery.TransactionCorrelatedSource[FoundryOuter, FoundryInner]
	selection CalculationSelection[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner]]
}

// ProjectTransactionCorrelatedCalculation starts a fluent projection selection without executing it.
func ProjectTransactionCorrelatedCalculation[FoundryOuter, FoundryInner foundryquery.TransactionScope](source foundryquery.TransactionCorrelatedSource[FoundryOuter, FoundryInner]) CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner] {
	return CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]{source: source}
}

// SelectID supplies the typed expression for id.
func (p CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]) SelectID(v foundryquery.Expression[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner], int]) CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.ID = v
	return p
}

// SelectCaption supplies the typed expression for caption.
func (p CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]) SelectCaption(v foundryquery.Expression[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner], string]) CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.Caption = v
	return p
}

// SelectLineTotal supplies the typed expression for line_total.
func (p CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]) SelectLineTotal(v foundryquery.Expression[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner], decimal.Decimal]) CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.LineTotal = v
	return p
}

// SelectAmountWithTax supplies the typed expression for amount_with_tax.
func (p CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]) SelectAmountWithTax(v foundryquery.Expression[foundryquery.TransactionCorrelation[FoundryOuter, FoundryInner], foundryvalue.Nullable[decimal.Decimal]]) CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner] {
	p.selection.AmountWithTax = v
	return p
}

// Query retains the source requirements and complete selection mapping.
func (p CalculationTransactionCorrelatedProject[FoundryOuter, FoundryInner]) Query() foundryquery.TransactionCorrelatedRecordQuery[FoundryOuter, FoundryInner, Calculation] {
	return SelectTransactionCorrelatedCalculation(p.source, p.selection)
}

// CalculationScopedFieldSet preserves typed field operators in a declared query scope.
type CalculationScopedFieldSet[FoundryScope any] struct {
	// ID describes Calculation.id.
	ID foundryquery.ExactField[FoundryScope, int]
	// Caption describes Calculation.caption.
	Caption foundryquery.TextField[FoundryScope, string]
	// LineTotal describes Calculation.line_total.
	LineTotal foundryquery.ExactField[FoundryScope, decimal.Decimal]
	// AmountWithTax describes Calculation.amount_with_tax.
	AmountWithTax foundryquery.NullableExactField[FoundryScope, decimal.Decimal]
}

// CalculationFieldsAt binds these record fields to an alias or joined scope.
func CalculationFieldsAt[FoundryScope any](scope foundryquery.RecordScope[FoundryScope, Calculation]) CalculationScopedFieldSet[FoundryScope] {
	return CalculationScopedFieldSet[FoundryScope]{
		ID:            foundryquery.NewExactField[FoundryScope, int](scope.Table(), "id", codec.Signed[int]()),
		Caption:       foundryquery.NewTextField[FoundryScope, string](scope.Table(), "caption", codec.String[string]()),
		LineTotal:     foundryquery.NewExactField[FoundryScope, decimal.Decimal](scope.Table(), "line_total", codec.Decimal()),
		AmountWithTax: foundryquery.NewNullableExactField[FoundryScope, decimal.Decimal](scope.Table(), "amount_with_tax", codec.Decimal()),
	}
}

// CalculationNullableFieldSet preserves typed field operators in a declared query scope.
type CalculationNullableFieldSet[FoundryScope any] struct {
	// ID describes Calculation.id.
	ID foundryquery.NullableExactField[FoundryScope, int]
	// Caption describes Calculation.caption.
	Caption foundryquery.NullableTextField[FoundryScope, string]
	// LineTotal describes Calculation.line_total.
	LineTotal foundryquery.NullableExactField[FoundryScope, decimal.Decimal]
	// AmountWithTax describes Calculation.amount_with_tax.
	AmountWithTax foundryquery.NullableExactField[FoundryScope, decimal.Decimal]
}

// CalculationNullableFieldsAt binds these record fields to an alias or joined scope.
func CalculationNullableFieldsAt[FoundryScope any](scope foundryquery.NullableRecordScope[FoundryScope, Calculation]) CalculationNullableFieldSet[FoundryScope] {
	return CalculationNullableFieldSet[FoundryScope]{
		ID:            foundryquery.NewNullableExactField[FoundryScope, int](scope.Table(), "id", codec.Signed[int]()),
		Caption:       foundryquery.NewNullableTextField[FoundryScope, string](scope.Table(), "caption", codec.String[string]()),
		LineTotal:     foundryquery.NewNullableExactField[FoundryScope, decimal.Decimal](scope.Table(), "line_total", codec.Decimal()),
		AmountWithTax: foundryquery.NewNullableExactField[FoundryScope, decimal.Decimal](scope.Table(), "amount_with_tax", codec.Decimal()),
	}
}
