// Code generated by foundry generate; DO NOT EDIT.
// Source: forms.go.

package requestflow

import (
	foundrycontract "github.com/weiloon1234/Foundry-Go/contract"
	foundryvalidation "github.com/weiloon1234/Foundry-Go/validation"
	sync "sync"
)

// JSONSubmissionJSON describes the concrete JSONSubmission JSON boundary.
// Reuse this immutable descriptor for decoding and client contract export.
// Fields are discovered from Go declarations; persistence models are not response DTOs.
func JSONSubmissionJSON() foundrycontract.JSON[JSONSubmission] { return foundryJSONSubmissionJSON() }

var foundryJSONSubmissionJSON = sync.OnceValue(func() foundrycontract.JSON[JSONSubmission] {
	return foundrycontract.DefineJSON[JSONSubmission](foundrycontract.Schema{Root: "foundry.test/consumer/requestflow.JSONSubmission", Types: []foundrycontract.Type{
		{ID: "foundry.test/consumer/requestflow.JSONSubmission", Kind: foundrycontract.Kind("object"), Nullable: false,
			Properties: []foundrycontract.Property{
				{Name: "name", Type: "string", Required: true},
			},
		},
		{ID: "string", Kind: foundrycontract.Kind("string"), Nullable: false},
	}})
})

// JSONSubmissionValidationFieldSet retains concrete DTO and value types for validation.
type JSONSubmissionValidationFieldSet struct {
	// Name validates the declared JSON property "name".
	Name foundryvalidation.Field[JSONSubmission, string]
}

// JSONSubmissionValidationFields returns typed field descriptors.
// Compose rules with these fields; JSON names and selectors are generated.
func JSONSubmissionValidationFields() JSONSubmissionValidationFieldSet {
	return foundryJSONSubmissionValidationFields()
}

var foundryJSONSubmissionValidationFields = sync.OnceValue(func() JSONSubmissionValidationFieldSet {
	return JSONSubmissionValidationFieldSet{
		Name: foundryvalidation.DefineField("name", func(input JSONSubmission) string {
			return input.Name
		}),
	}
})
